### ISSUE TITLE
Improve exception on AccumuloOutputFormat if store(job) not called.

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#1039]
I wrote the following code that successfully compiled and ran:

```java
    AccumuloOutputFormat.configure().clientProperties(env.getClientProps()).createTables(true)
        .defaultTable(tableName);
```
I should have called store(job) at end.

```java
    AccumuloOutputFormat.configure().clientProperties(env.getClientProps()).createTables(true)
        .defaultTable(tableName).store(job);
```

The code gave me the following exception (which was confusing to debug). I think this message can be improved at a minimum:

```
Exception in thread "main" java.lang.IllegalArgumentException: auth.token must be set!
	at org.apache.accumulo.core.conf.ClientProperty.getValue(ClientProperty.java:171)
	at org.apache.accumulo.core.conf.ClientProperty.getAuthenticationToken(ClientProperty.java:277)
	at org.apache.accumulo.hadoop.mapreduce.AccumuloOutputFormat.checkOutputSpecs(AccumuloOutputFormat.java:62)
	at org.apache.hadoop.mapreduce.JobSubmitter.checkSpecs(JobSubmitter.java:277)
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:143)
	at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1570)
	at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1567)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
```

**Comment by milleruntime** [comment]
The only required method is clientProperties() so I think the only way we could check if store() has been called would be to have a property like `ClientOpts.IS_CONFIGURED` and check if it is set in AccumuloOutputFormat.checkOutputSpecs.

**Comment by milleruntime** [comment]
@mikewalch what do you think about AccumuloFileOutputFormat? There really isn't any validation for this one but the output path not being set should throw a useful error.
