### ISSUE TITLE
Transient FateConcurrencyIT failure

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1079]
After merging #1061 , I saw the test pass several times, but then I saw it fail with the following. It looks like we still have some transient test bug.

```java
java.lang.RuntimeException: java.lang.RuntimeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /accumulo/47677c30-f146-4b03-87c3-046ede7590e9/fate/tx_01f0ea8461b6e428
	at org.apache.accumulo.test.functional.FateConcurrencyIT.findFate(FateConcurrencyIT.java:379)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.blockUntilCompactionRunning(FateConcurrencyIT.java:355)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.startCompactTask(FateConcurrencyIT.java:314)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.getFateStatus(FateConcurrencyIT.java:221)
Caused by: java.lang.RuntimeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /accumulo/47677c30-f146-4b03-87c3-046ede7590e9/fate/tx_01f0ea8461b6e428
	at org.apache.accumulo.test.functional.FateConcurrencyIT.findFate(FateConcurrencyIT.java:379)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.blockUntilCompactionRunning(FateConcurrencyIT.java:355)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.startCompactTask(FateConcurrencyIT.java:314)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.getFateStatus(FateConcurrencyIT.java:221)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /accumulo/47677c30-f146-4b03-87c3-046ede7590e9/fate/tx_01f0ea8461b6e428
	at org.apache.accumulo.test.functional.FateConcurrencyIT.findFate(FateConcurrencyIT.java:379)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.blockUntilCompactionRunning(FateConcurrencyIT.java:355)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.startCompactTask(FateConcurrencyIT.java:314)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.getFateStatus(FateConcurrencyIT.java:221)
```

**Comment by ctubbsii** [comment]
Haven't seen this recently. It looks like #1082 probably fixed this.
