### ISSUE TITLE
Unable to upgrade from 1.9 to 2.0 with walogs

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1111]
I tried to upgrade a 1.9 instance that was not cleanly shutdown to 2.0.  The upgrade failed because the write ahead logs were unreadable.

```
2019-04-18 19:17:17,468 [log.DfsLogger] ERROR: Unsupported WAL version.
2019-04-18 19:17:17,468 [log.DfsLogger] ERROR: Unsupported WAL version.
2019-04-18 19:17:17,504 [log.LogSorter] ERROR: Caught throwable
java.io.IOException: Invalid LogEvent type, got ordinal 45, but only know about 6 possible types.
        at org.apache.accumulo.tserver.logger.LogFileKey.readFields(LogFileKey.java:46)
        at org.apache.accumulo.tserver.log.LogSorter$LogProcessor.sort(LogSorter.java:138)
        at org.apache.accumulo.tserver.log.LogSorter$LogProcessor.process(LogSorter.java:92)
        at org.apache.accumulo.server.zookeeper.DistributedWorkQueue$1.run(DistributedWorkQueue.java:111)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at java.lang.Thread.run(Thread.java:748)
2019-04-18 19:17:17,508 [log.LogSorter] ERROR: Caught throwable
java.io.IOException: Invalid LogEvent type, got ordinal 45, but only know about 6 possible types.
        at org.apache.accumulo.tserver.logger.LogFileKey.readFields(LogFileKey.java:46)
        at org.apache.accumulo.tserver.log.LogSorter$LogProcessor.sort(LogSorter.java:138)
        at org.apache.accumulo.tserver.log.LogSorter$LogProcessor.process(LogSorter.java:92)
        at org.apache.accumulo.server.zookeeper.DistributedWorkQueue$1.run(DistributedWorkQueue.java:111)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ctubbsii** [comment]
Could this be related to the crypto work done in 2.0? I can imagine not supporting upgrades from WALs encrypted with the previous experimental version of file encryption (if doing so is cumbersome), but we should still support upgrades under normal (non-experimental) use cases.
