### ISSUE TITLE
NoSuchMethodError on Initialize

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1228]
Saw this today when trying to run Uno on Master with Java 11.  
```
11:59:47 {master} /local/uno$ cat install/logs/setup/accumulo.stdout 
2018-11-08 11:58:40,688 [start.Main] ERROR: Uncaught exception
java.util.ServiceConfigurationError: org.apache.accumulo.start.spi.KeywordExecutable: Provider org.apache.accumulo.server.init.Initialize could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.apache.accumulo.start.Main.checkDuplicates(Main.java:237)
	at org.apache.accumulo.start.Main.getExecutables(Main.java:228)
	at org.apache.accumulo.start.Main.main(Main.java:84)
Caused by: java.lang.NoSuchMethodError: org.apache.commons.configuration.MapConfiguration.<init>(Ljava/util/Properties;)V
	at org.apache.accumulo.core.conf.Property.precomputeDefaultValue(Property.java:969)
	at org.apache.accumulo.core.conf.Property.<clinit>(Property.java:1345)
	at org.apache.accumulo.server.init.Initialize.<clinit>(Initialize.java:165)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 5 more

11:59:55 {master} /local/uno$ java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)

```

**Comment by ctubbsii** [comment]
What JDK version did you build with? The same as the version running?

**Comment by ctubbsii** [comment]
I cannot reproduce this.

**Comment by milleruntime** [comment]
I am still seeing this on my laptop.  
```09:02:59 {master} /local/uno/install/logs/setup$ java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)

09:05:16 (master) /local/workspace/accumulo$ git log -1 --oneline 
309833ae2 (HEAD -> master, upstream/master) Merge branch '2.0'

cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

```

Here is my uno env:
```09:04:26 {master} /local/uno$ uno env
export HADOOP_HOME="/local/uno/install/hadoop-3.2.0"
export HADOOP_CONF_DIR="/local/uno/install/hadoop-3.2.0/etc/hadoop"
export ZOOKEEPER_HOME="/local/uno/install/zookeeper-3.4.14"
export SPARK_HOME="/local/uno/install/spark-2.3.2-bin-without-hadoop"
export ACCUMULO_HOME="/local/uno/install/accumulo-2.0.0-SNAPSHOT"
export FLUO_HOME="/local/uno/install/fluo-1.2.0"
export FLUO_YARN_HOME="/local/uno/install/fluo-yarn-1.0.0"
export PATH="$PATH:/local/uno/bin:/local/uno/install/hadoop-3.2.0/bin:/local/uno/install/zookeeper-3.4.14/bin:/local/uno/install/accumulo-2.0.0-SNAPSHOT/bin"
```

**Comment by milleruntime** [comment]
Nevermind.  Was using an outdated Uno.  Updated Uno and its now fixed

**Comment by milleruntime** [comment]
This must be related to my environment.  I am seeing this error again but now on the 2.0 branch SNAPSHOT and using java 8.

**Comment by ctubbsii** [comment]
Are you using OpenJDK8 or OracleJDK8? I have never seen this with OpenJDK8.

**Comment by milleruntime** [comment]
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

**Comment by milleruntime** [comment]
Maybe this is an issue with Uno not deleting files properly when calling setup?

**Comment by milleruntime** [comment]
I deleted my install directory and had to unset HADOOP_PREFIX leftover from previous version, working again.
