### ISSUE TITLE
Saw partial bulk import when master killed

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1231]
I was running the [bulk ingest test](https://github.com/apache/accumulo-testing/blob/master/docs/bulk-test.md) with agitation and  I saw the following.  These test were using the new bulk import API.  

```
root@muchos> table ci
root@muchos ci> importdirectory /tmp/bt/82/files true
2019-06-21 18:33:23,305 [shell.Shell] ERROR: org.apache.accumulo.core.client.AccumuloException: Internal error processing waitForFateOperation
```

The master logs contained the following errors.  I suspect the processes was killed with SIGTERM which caused the Hadoop shutdown hook to close the file system.  This caused the bulk FATE op to fail mid way through which resulted in only some of the files being imported.

```
2019-06-21 18:33:23,260 [fate.Fate] WARN : Failed to execute Repo, tid=0bb9e3097f19b61c
com.google.gson.JsonSyntaxException: java.io.IOException: Filesystem closed
        at com.google.gson.Gson.fromJson(Gson.java:942)
        at org.apache.accumulo.core.clientImpl.bulk.LoadMappingIterator.next(LoadMappingIterator.java:73)
        at org.apache.accumulo.core.clientImpl.bulk.LoadMappingIterator.next(LoadMappingIterator.java:40)
        at org.apache.accumulo.core.util.PeekingIterator.next(PeekingIterator.java:69)
        at org.apache.accumulo.master.tableOps.bulkVer2.LoadFiles.loadFiles(LoadFiles.java:329)
        at org.apache.accumulo.master.tableOps.bulkVer2.LoadFiles.isReady(LoadFiles.java:92)
        at org.apache.accumulo.master.tableOps.bulkVer2.LoadFiles.isReady(LoadFiles.java:70)
        at org.apache.accumulo.master.tableOps.TraceRepo.isReady(TraceRepo.java:42)
        at org.apache.accumulo.fate.Fate$TransactionRunner.run(Fate.java:68)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.io.IOException: Filesystem closed
                at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:474)
                at org.apache.hadoop.hdfs.DFSInputStream.close(DFSInputStream.java:656)
                at java.io.FilterInputStream.close(FilterInputStream.java:181)
                at sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:378)
                at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:193)
                at java.io.InputStreamReader.close(InputStreamReader.java:199)
                at java.io.BufferedReader.close(BufferedReader.java:525)
                at com.google.gson.stream.JsonReader.close(JsonReader.java:1219)
                at org.apache.accumulo.core.clientImpl.bulk.LoadMappingIterator.close(LoadMappingIterator.java:59)
                at org.apache.accumulo.master.tableOps.bulkVer2.LoadFiles.isReady(LoadFiles.java:93)
                ... 7 more
Caused by: java.io.IOException: Filesystem closed
        at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:474)
        at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:742)
        at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:829)
        at java.io.DataInputStream.read(DataInputStream.java:149)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.read1(BufferedReader.java:212)
        at java.io.BufferedReader.read(BufferedReader.java:289)
        at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1295)
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1333)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:519)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:207)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        ... 12 more
2019-06-21 18:33:23,274 [fate.Fate] INFO : Updated status for Repo with tid=0bb9e3097f19b61c to FAILED_IN_PROGRESS
2019-06-21 18:33:23,290 [thrift.ProcessFunction] ERROR: Internal error processing waitForFateOperation
com.google.gson.JsonSyntaxException: java.io.IOException: Filesystem closed
        at com.google.gson.Gson.fromJson(Gson.java:942)
        at org.apache.accumulo.core.clientImpl.bulk.LoadMappingIterator.next(LoadMappingIterator.java:73)
        at org.apache.accumulo.core.clientImpl.bulk.LoadMappingIterator.next(LoadMappingIterator.java:40)
        at org.apache.accumulo.core.util.PeekingIterator.next(PeekingIterator.java:69)
        at org.apache.accumulo.master.tableOps.bulkVer2.LoadFiles.loadFiles(LoadFiles.java:329)
        at org.apache.accumulo.master.tableOps.bulkVer2.LoadFiles.isReady(LoadFiles.java:92)
        at org.apache.accumulo.master.tableOps.bulkVer2.LoadFiles.isReady(LoadFiles.java:70)
        at org.apache.accumulo.master.tableOps.TraceRepo.isReady(TraceRepo.java:42)
        at org.apache.accumulo.fate.Fate$TransactionRunner.run(Fate.java:68)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.io.IOException: Filesystem closed
                at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:474)
                at org.apache.hadoop.hdfs.DFSInputStream.close(DFSInputStream.java:656)
                at java.io.FilterInputStream.close(FilterInputStream.java:181)
                at sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:378)
                at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:193)
                at java.io.InputStreamReader.close(InputStreamReader.java:199)
                at java.io.BufferedReader.close(BufferedReader.java:525)
                at com.google.gson.stream.JsonReader.close(JsonReader.java:1219)
                at org.apache.accumulo.core.clientImpl.bulk.LoadMappingIterator.close(LoadMappingIterator.java:59)
                at org.apache.accumulo.master.tableOps.bulkVer2.LoadFiles.isReady(LoadFiles.java:93)
                ... 7 more
Caused by: java.io.IOException: Filesystem closed
        at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:474)
        at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:742)
        at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:829)
        at java.io.DataInputStream.read(DataInputStream.java:149)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.read1(BufferedReader.java:212)
        at java.io.BufferedReader.read(BufferedReader.java:289)
        at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1295)
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1333)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:519)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:207)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        ... 12 more
```

I ran continuous ingest verify after this failure and as expected it detected missing data because only some of the files were imported.  In the output below a non zero UNDEFINED counter indicates data was missing.

```
	org.apache.accumulo.testing.continuous.ContinuousVerify$Counts
		REFERENCED=1988124872
		UNDEFINED=4621488
		UNREFERENCED=4625473
```

**Comment by milleruntime** [comment]
> I suspect the processes was killed with SIGTERM which caused the Hadoop shutdown hook to close the file system

Which process are you referring to?  Master was killed?  Or some other thread?

**Comment by milleruntime** [comment]
I was looking at this some and I am not sure how data could be lost.  If the FATE operation was marked FAILED_IN_PROGRESS then it should have restarted when the Master restarted.  This would have re-read the LoadPlan and loaded all the files again.

**Comment by keith-turner** [comment]
> Which process are you referring to? Master was killed? Or some other thread?

Master process was killed.

> If the FATE operation was marked FAILED_IN_PROGRESS then it should have restarted when the Master restarted.

I think FAILED_IN_PROGRESS means its currently working on executing the undo operations for the fate transaction stack.

> This would have re-read the LoadPlan and loaded all the files again.

No, not in this case.  When a FATE transaction throws an unexpected exception it marks it failed in ZK and starts calling undo operations.

**Comment by keith-turner** [comment]
I am still looking into this and thinking about the best course of action.  Below is some information I have discovered while looking into this.

 * Hadoop has a config property `fs.automatic.close` that disables its shutdown hook if set to `false`.  It defaults to `true`.
 * Accumulo's tablet code tries to detect io excetptions caused by shutdown during scanning a tablet in order to prevent sending spurious error message to the client.  See [Tablet.java line 593](https://github.com/apache/accumulo/blob/f81516e18ddd62916fa80784e45821917534f5b9/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L593) and [Tablet.java line 805](https://github.com/apache/accumulo/blob/f81516e18ddd62916fa80784e45821917534f5b9/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L805).
 * The file move operation is not idempotent.  It needs to handle the case of the file already being moved.  Need to see if old bulk import code has this issue.

**Comment by milleruntime** [comment]
I found this [ShutdownHookmanager](http://hadoop.apache.org/docs/r2.8.0/hadoop-project-dist/hadoop-common/api/org/apache/hadoop/util/ShutdownHookManager.html) in Hadoop, which I thought was interesting and may be worth looking into.
