### ISSUE TITLE
Bulk importing empty directory resulted in error

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1286]
I accidentally bulk imported a directory that I had previously imported.  So the directory had no files in it.  I saw the following in the shell.   I am thinking it should not be an error in this case.  If we actually want an error for zero files, then it should be a nice clear error message.

```
root@muchos ci> importdirectory /tmp/bt/1/files true
2019-07-23 16:37:22,511 [shell.Shell] ERROR: org.apache.accumulo.core.client.AccumuloException: Internal error processing waitForFateOperation
```

I saw the following in the master logs.

```
2019-07-23 16:37:29,937 [thrift.ProcessFunction] ERROR: Internal error processing waitForFateOperation
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was END_ARRAY at line 1 column 3 path $[0]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at org.apache.accumulo.core.clientImpl.bulk.LoadMappingIterator.next(LoadMappingIterator.java:73)
        at org.apache.accumulo.core.clientImpl.bulk.LoadMappingIterator.next(LoadMappingIterator.java:40)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
        at org.apache.accumulo.master.tableOps.bulkVer2.PrepBulkImport.checkForMerge(PrepBulkImport.java:108)
        at org.apache.accumulo.master.tableOps.bulkVer2.PrepBulkImport.checkForMerge(PrepBulkImport.java:167)
        at org.apache.accumulo.master.tableOps.bulkVer2.PrepBulkImport.call(PrepBulkImport.java:175)
        at org.apache.accumulo.master.tableOps.bulkVer2.PrepBulkImport.call(PrepBulkImport.java:68)
        at org.apache.accumulo.master.tableOps.TraceRepo.call(TraceRepo.java:49)
        at org.apache.accumulo.fate.Fate$TransactionRunner.run(Fate.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was END_ARRAY at line 1 column 3 path $[0]
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
        ... 14 more
```

**Comment by ctubbsii** [comment]
Silently succeeding would be surprising behavior, because importing an empty directory is almost certainly a mistake on the user's part (typo: wrong directory specified). But, the above is very unfriendly, so a nice clear error message in the client would be nice.

**Comment by milleruntime** [comment]
One option would be to WARN on the client and then just pass through the server, succeeding.

**Comment by keith-turner** [comment]
I am leaning twoards succeeding on an empty directory because it makes it easier for user to wrote idempotent code.

**Comment by ctubbsii** [comment]
> I am leaning twoards succeeding on an empty directory because it makes it easier for user to write idempotent code.

It also makes it easier for the user to unintentionally write code like:

```java
String dir;
while (dirs.hasMoreDirs()) {
  dirs.nextDir(); // forgot to assign to `dir`
  bulkImport(dir); // no indication whatsoever that there's a problem
}
```

**Comment by hkeebler** [comment]
I'm just glad I now know what that error messages means.  Thanks.

**Comment by keith-turner** [comment]
I like the idea of an explicit parameter and I think that would be easy to do in the Java API.  Not sure about the shell.

**Comment by ctubbsii** [comment]
> I like the idea of an explicit parameter and I think that would be easy to do in the Java API. Not sure about the shell.

Should be easy enough to add a shell option, `--ignore-empty`

**Comment by keith-turner** [comment]
Could make empty dir fail in 2.0 and open a 2.1 issue to add API and shell options to ignore empty.

**Comment by keith-turner** [comment]
> Should be easy enough to add a shell option, --ignore-empty

Just have to consider that the shell may call the old or new API and think through how this option would work with both.

**Comment by ctubbsii** [comment]
> Could make empty dir fail in 2.0 and open a 2.1 issue to add API and shell options to ignore empty.

:+1: That would get us closer to 2.0 release faster.

**Comment by EdColeman** [comment]
I'll create a new issue - but related, it would be really helpful if the shell importdirectory command honored the -t table option.
