### ISSUE TITLE
Still seeing FateConcurrencyIT failures

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1308]
Still seeing #1079 in the 1.9 branch:

## org.apache.accumulo.test.functional.FateConcurrencyIT.getFateStatus

```
Failing for the past 1 build (Since Unstable#143 )
Took 13 sec.
```

### Error Message
```java
java.lang.RuntimeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /accumulo/b3643583-48e6-4729-b04a-92dd02d26a33/fate/tx_4de4bd899b530eb4
```

### Stacktrace

```java
java.lang.RuntimeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /accumulo/b3643583-48e6-4729-b04a-92dd02d26a33/fate/tx_4de4bd899b530eb4
Stacktrace
java.lang.RuntimeException: java.lang.RuntimeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /accumulo/b3643583-48e6-4729-b04a-92dd02d26a33/fate/tx_4de4bd899b530eb4
	at org.apache.accumulo.test.functional.FateConcurrencyIT.findFate(FateConcurrencyIT.java:435)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.blockUntilCompactionRunning(FateConcurrencyIT.java:380)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.startCompactTask(FateConcurrencyIT.java:346)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.getFateStatus(FateConcurrencyIT.java:231)
Caused by: java.lang.RuntimeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /accumulo/b3643583-48e6-4729-b04a-92dd02d26a33/fate/tx_4de4bd899b530eb4
	at org.apache.accumulo.test.functional.FateConcurrencyIT.findFate(FateConcurrencyIT.java:435)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.blockUntilCompactionRunning(FateConcurrencyIT.java:380)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.startCompactTask(FateConcurrencyIT.java:346)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.getFateStatus(FateConcurrencyIT.java:231)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /accumulo/b3643583-48e6-4729-b04a-92dd02d26a33/fate/tx_4de4bd899b530eb4
	at org.apache.accumulo.test.functional.FateConcurrencyIT.findFate(FateConcurrencyIT.java:435)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.blockUntilCompactionRunning(FateConcurrencyIT.java:380)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.startCompactTask(FateConcurrencyIT.java:346)
	at org.apache.accumulo.test.functional.FateConcurrencyIT.getFateStatus(FateConcurrencyIT.java:231)
```

### Standard Output

```java
2019-08-04 17:05:21,436 [zookeeper.ZooSession] DEBUG: Connecting to localhost:41331 with timeout 30000 with auth
2019-08-04 17:05:26,267 [zookeeper.ZooSession] DEBUG: Connecting to localhost:41331 with timeout 30000 with auth
2019-08-04 17:05:27,126 [admin.TableOperations] DEBUG: Failed to call waitForFateOperation(), retrying ... 
org.apache.thrift.transport.TTransportException
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:129)
	at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.accumulo.core.client.impl.ThriftTransportPool$CachedTTransport.readAll(ThriftTransportPool.java:296)
	at org.apache.thrift.protocol.TCompactProtocol.readByte(TCompactProtocol.java:634)
	at org.apache.thrift.protocol.TCompactProtocol.readMessageBegin(TCompactProtocol.java:501)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
	at org.apache.accumulo.core.master.thrift.FateService$Client.recv_waitForFateOperation(FateService.java:175)
	at org.apache.accumulo.core.master.thrift.FateService$Client.waitForFateOperation(FateService.java:160)
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.waitForFateOperation(TableOperationsImpl.java:280)
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.doFateOperation(TableOperationsImpl.java:326)
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.compact(TableOperationsImpl.java:837)
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.compact(TableOperationsImpl.java:791)
	at org.apache.accumulo.test.functional.FateConcurrencyIT$SlowCompactionRunner.run(FateConcurrencyIT.java:650)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Manno15** [comment]
I am going to take a look at this.

**Comment by EdColeman** [comment]
I have implemented a change that may remove this particular error - I'm not ready to merge the rest of the code, but the changes are here (https://github.com/EdColeman/accumulo/tree/add_fate_type_metrics)

I didn't want to step on any changes or work you may have - but I'm working on code that can be exercised by this test.  I didn't have the error occur - but I also use the test method in a debugger so that I can connect via jconsole.  Sort of a long way to say that I was in the neighborhood.

The branch has mainly changes to fate metrics, but does change the FateConcurrencyIT 
I'd like to wrap up the fate metrics this week - as well as any improvements to this test if that fits your schedule.

**Comment by Manno15** [comment]
If I can get around to it today, I will try out your changes to see if I can still replicate this error.

**Comment by Manno15** [comment]
Unfortunately, I was still able to reproduce the error. I will try to debug a little further.

**Comment by EdColeman** [comment]
I pulled the changes from the other branch and created a separate pull request with just the test changes. (https://github.com/apache/accumulo/pull/1342)
Please run future tests with this and see if this resolves the intermittent issues.
