### ISSUE TITLE
Table Status page is broken

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1362]
In the Monitor when on the Tables page... click a table ID link and it should refresh the page with detailed information about that table. I am getting this JS error and an empty table:
```
jQuery.Deferred exception: clearTableBody is not defined ReferenceError: clearTableBody is not defined
    at refreshTableServersTable (http://leader1:9995/resources/js/table.js:39:3)
    at Object.<anonymous> (http://leader1:9995/resources/js/table.js:24:5)
    at mightThrow (http://leader1:9995/resources/external/jquery-3.2.1.js:3583:29)
    at process (http://leader1:9995/resources/external/jquery-3.2.1.js:3651:12) undefined
```
![monitor-table-status](https://user-images.githubusercontent.com/11872539/64889823-352c7a80-d63c-11e9-8984-d56ee6def3cb.png)

**Comment by milleruntime** [comment]
This was an issue with my proxy not refreshing.  A good old "Ctrl + F5" fixed the issue.
