### ISSUE TITLE
Exception related to invalid dir name

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#1466]
I was ran the helloworld.Insert in the examples repo using Accumulo 2.1.0-SNAPSHOT when I received the exception below.

```
2019-12-23 16:34:03,586 [core.clientImpl.TabletServerBatchWriter] ERROR: Error processing mutation set
java.lang.IllegalArgumentException: Saw invalid dir name {} {} [+r< srv:dir [] 1 false, hdfs://localhost:8020/accumulo/tables/+r/root_tablet]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:440)
	at org.apache.accumulo.core.metadata.schema.TabletMetadata.convertRow(TabletMetadata.java:329)
	at org.apache.accumulo.core.metadata.schema.RootTabletMetadata.convertToTabletMetadata(RootTabletMetadata.java:108)
	at org.apache.accumulo.core.metadata.schema.TabletsMetadata.getRootMetadata(TabletsMetadata.java:353)
	at org.apache.accumulo.core.metadata.schema.TabletsMetadata$Builder.build(TabletsMetadata.java:90)
	at org.apache.accumulo.core.metadata.schema.AmpleImpl.readTablet(AmpleImpl.java:41)
	at org.apache.accumulo.core.clientImpl.RootTabletLocator.getRootTabletLocation(RootTabletLocator.java:109)
	at org.apache.accumulo.core.clientImpl.RootTabletLocator.locateTablet(RootTabletLocator.java:132)
	at org.apache.accumulo.core.clientImpl.TabletLocatorImpl.lookupTabletLocation(TabletLocatorImpl.java:485)
	at org.apache.accumulo.core.clientImpl.TabletLocatorImpl.lookupTabletLocationAndCheckLock(TabletLocatorImpl.java:670)
	at org.apache.accumulo.core.clientImpl.TabletLocatorImpl._locateTablet(TabletLocatorImpl.java:655)
	at org.apache.accumulo.core.clientImpl.TabletLocatorImpl.locateTablet(TabletLocatorImpl.java:458)
	at org.apache.accumulo.core.clientImpl.TabletLocatorImpl.lookupTabletLocation(TabletLocatorImpl.java:485)
	at org.apache.accumulo.core.clientImpl.TabletLocatorImpl.lookupTabletLocationAndCheckLock(TabletLocatorImpl.java:670)
	at org.apache.accumulo.core.clientImpl.TabletLocatorImpl._locateTablet(TabletLocatorImpl.java:660)
	at org.apache.accumulo.core.clientImpl.TabletLocatorImpl.binMutations(TabletLocatorImpl.java:214)
	at org.apache.accumulo.core.clientImpl.SyncingTabletLocator.binMutations(SyncingTabletLocator.java:89)
	at org.apache.accumulo.core.clientImpl.TimeoutTabletLocator.binMutations(TimeoutTabletLocator.java:85)
	at org.apache.accumulo.core.clientImpl.TabletServerBatchWriter$MutationWriter.binMutations(TabletServerBatchWriter.java:683)
	at org.apache.accumulo.core.clientImpl.TabletServerBatchWriter$MutationWriter.addMutations(TabletServerBatchWriter.java:736)
	at org.apache.accumulo.core.clientImpl.TabletServerBatchWriter$MutationWriter.lambda$queueMutations$0(TabletServerBatchWriter.java:724)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:37)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "main" org.apache.accumulo.core.client.MutationsRejectedException: # constraint violations : 0  security codes: {}  # server errors 0 # exceptions 1
	at org.apache.accumulo.core.clientImpl.TabletServerBatchWriter.checkForFailures(TabletServerBatchWriter.java:564)
	at org.apache.accumulo.core.clientImpl.TabletServerBatchWriter.close(TabletServerBatchWriter.java:344)
	at org.apache.accumulo.core.clientImpl.BatchWriterImpl.close(BatchWriterImpl.java:57)
	at org.apache.accumulo.examples.helloworld.Insert.main(Insert.java:64)
Caused by: java.lang.IllegalArgumentException: Saw invalid dir name {} {} [+r< srv:dir [] 1 false, hdfs://localhost:8020/accumulo/tables/+r/root_tablet]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:440)
	at org.apache.accumulo.core.metadata.schema.TabletMetadata.convertRow(TabletMetadata.java:329)
	at org.apache.accumulo.core.metadata.schema.RootTabletMetadata.convertToTabletMetadata(RootTabletMetadata.java:108)
	at org.apache.accumulo.core.metadata.schema.TabletsMetadata.getRootMetadata(TabletsMetadata.java:353)
	at org.apache.accumulo.core.metadata.schema.TabletsMetadata$Builder.build(TabletsMetadata.java:90)
	at org.apache.accumulo.core.metadata.schema.AmpleImpl.readTablet(AmpleImpl.java:41)
	at org.apache.accumulo.core.clientImpl.RootTabletLocator.getRootTabletLocation(RootTabletLocator.java:109)
	at org.apache.accumulo.core.clientImpl.RootTabletLocator.locateTablet(RootTabletLocator.java:132)
	at org.apache.accumulo.core.clientImpl.TabletLocatorImpl.lookupTabletLocation(TabletLocatorImpl.java:485)
	at org.apache.accumulo.core.clientImpl.TabletLocatorImpl.lookupTabletLocationAndCheckLock(TabletLocatorImpl.java:670)
	at org.apache.accumulo.core.clientImpl.TabletLocatorImpl._locateTablet(TabletLocatorImpl.java:655)
	at org.apache.accumulo.core.clientImpl.TabletLocatorImpl.locateTablet(TabletLocatorImpl.java:458)
	at org.apache.accumulo.core.clientImpl.TabletLocatorImpl.lookupTabletLocation(TabletLocatorImpl.java:485)
	at org.apache.accumulo.core.clientImpl.TabletLocatorImpl.lookupTabletLocationAndCheckLock(TabletLocatorImpl.java:670)
	at org.apache.accumulo.core.clientImpl.TabletLocatorImpl._locateTablet(TabletLocatorImpl.java:660)
	at org.apache.accumulo.core.clientImpl.TabletLocatorImpl.binMutations(TabletLocatorImpl.java:214)
	at org.apache.accumulo.core.clientImpl.SyncingTabletLocator.binMutations(SyncingTabletLocator.java:89)
	at org.apache.accumulo.core.clientImpl.TimeoutTabletLocator.binMutations(TimeoutTabletLocator.java:85)
	at org.apache.accumulo.core.clientImpl.TabletServerBatchWriter$MutationWriter.binMutations(TabletServerBatchWriter.java:683)
	at org.apache.accumulo.core.clientImpl.TabletServerBatchWriter$MutationWriter.addMutations(TabletServerBatchWriter.java:736)
	at org.apache.accumulo.core.clientImpl.TabletServerBatchWriter$MutationWriter.lambda$queueMutations$0(TabletServerBatchWriter.java:724)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:37)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by milleruntime** [comment]
I was able to run helloworld insert example against 2.1.0-SNAPSHOT with the commit [dfceef696](https://github.com/apache/accumulo/commit/dfceef696e131bc838720ed93cd25179c67153a8) and did not see this error.
