### ISSUE TITLE
Broken GarbageCollectorIT

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1485]
GarbageCollectorIT is consistently failing, I suspect due to @milleruntime changes in #1479  to getting rid of relative path code:

```
12:05:27 [ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 211.051 s <<< FAILURE! - in org.apache.accumulo.test.functional.GarbageCollectorIT
12:05:27 [ERROR] gcLotsOfCandidatesIT(org.apache.accumulo.test.functional.GarbageCollectorIT)  Time elapsed: 11.759 s  <<< ERROR!
12:05:27 java.lang.IllegalArgumentException: Invalid path provided, no scheme in /00000000000000000000/aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeffffffffffgggggggggghhhhhhhhhhiiiiiiiiiijjjjjjjjjj
12:05:27 	at org.apache.accumulo.core.metadata.TabletFileUtil.validate(TabletFileUtil.java:36)
12:05:27 	at org.apache.accumulo.server.metadata.ServerAmpleImpl.createDeleteMutation(ServerAmpleImpl.java:196)
12:05:27 	at org.apache.accumulo.test.functional.GarbageCollectorIT.addEntries(GarbageCollectorIT.java:315)
12:05:27 	at org.apache.accumulo.test.functional.GarbageCollectorIT.gcLotsOfCandidatesIT(GarbageCollectorIT.java:149)
12:05:27 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:05:27 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:05:27 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:05:27 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
12:05:27 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
12:05:27 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
12:05:27 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
12:05:27 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
12:05:27 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
12:05:27 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
12:05:27 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
12:05:27 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
12:05:27 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
12:05:27 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by milleruntime** [comment]
I am working on using TabletFile in this part of the code and it will fix this text.

**Comment by milleruntime** [comment]
> I am working on using TabletFile in this part of the code and it will fix this text.

OK after some tinkering, I believe the IT can be fixed independent of the next TabletFile change I am now working on.  The GC method that takes a string will have to stay like that due to the way the GC deletes directories.
