### ISSUE TITLE
ManyWriteAheadLogsIT is flakey

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1488]
While attempting to tune the timing of many of our ITs, I found that ManyWriteAheadLogsIT occassionally fails with an assertion error:

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 21.762 s <<< FAILURE! - in org.apache.accumulo.test.functional.ManyWriteAheadLogsIT
[ERROR] testMany(org.apache.accumulo.test.functional.ManyWriteAheadLogsIT)  Time elapsed: 21.538 s  <<< FAILURE!
java.lang.AssertionError: Open WALs not in expected range 0
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.apache.accumulo.test.functional.ManyWriteAheadLogsIT.addOpenWals(ManyWriteAheadLogsIT.java:167)
	at org.apache.accumulo.test.functional.ManyWriteAheadLogsIT.testMany(ManyWriteAheadLogsIT.java:140)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

This occurs on the 1.9 branch, at the very least, but probably also affects the master/2.1 branch.

**Comment by ctubbsii** [comment]
Also, the test has a timeout of 10 minutes, but when I ran it on a modest laptop, when it passed, it did so in less than 35 seconds. So, the default timeout setting is way off from what we should expect if the test were working reliably.

**Comment by milleruntime** [comment]
This test is passing for me in master branch.

**Comment by Manno15** [comment]
I am having trouble reproducing this error, both on 1.9 and on the master branch. What command did you use to run this IT or did you run the entire suite of IT's when running into this bug?

**Comment by ctubbsii** [comment]
@Manno15 I was running the entire suite in Jenkins, but to reproduce, I would probably repeatedly run something like: `mvn clean verify -Dtest=blah -Dit.test=ManyWriteAheadLogsIT -Dspotbugs.skip -Dcheckstyle.skip`; the assertion error on the 1.9 branch was particularly concerning to me, since it was more than a simple timeout.

**Comment by Manno15** [comment]
@ctubbsii That's how I am running it. Still not hitting the error. Interesting.

**Comment by ctubbsii** [comment]
It might be rare. We could close it as not reproducible, but I'd feel a bit more comfortable if we had an explanation for how the above error could occur.

**Comment by Manno15** [comment]
I will take a deeper investigation into the IT.

**Comment by jzgithub1** [comment]
@ctubbsii ,  I have run this test inside of IntelliJ IDE on repeat mode for 30 times and have not seen the test fail in the way you show up above.  Maybe allowing the number of open WALs to be 0 is what you want to do.  That way the assertTrue on line 212 in addOpenWals in ManyWriteAheadLogsIT.java won't throw an assertion error:
```java
assertTrue("Open WALs not in expected range " + open, open > 0 && open < 4);
```
changed to:

```java
assertTrue("Open WALs not in expected range " + open, open >= 0 && open < 4);
```

**Comment by ctubbsii** [comment]
I ran the following to try to reproduce, expecting it to take some time:
```bash
while mvn clean verify -Dtest=blah -Dit.test=ManyWriteAheadLogsIT -Dspotbugs.skip -Dcheckstyle.skip; do echo Test passed...; done
```

It failed on the first attempt with:

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 17.589 s <<< FAILURE! - in org.apache.accumulo.test.functional.ManyWriteAheadLogsIT
[ERROR] testMany(org.apache.accumulo.test.functional.ManyWriteAheadLogsIT)  Time elapsed: 17.354 s  <<< FAILURE!
java.lang.AssertionError: Open WALs not in expected range 0
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.apache.accumulo.test.functional.ManyWriteAheadLogsIT.addOpenWals(ManyWriteAheadLogsIT.java:167)
	at org.apache.accumulo.test.functional.ManyWriteAheadLogsIT.testMany(ManyWriteAheadLogsIT.java:140)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

It is possible that @jzgithub1 's suggestion to include `0` as a possible value in the test will "fix" the test, but without investigating further, I suspect, doing so would merely circumvent the test case the IT is looking for.

**Comment by jzgithub1** [comment]
@ctubbsii ,  I tried to force the situation of more WALs being open by reducing the TSERV_WALOG_MAX_SIZE to 850K but that caused the test to fail.  Raising it to 2M caused failure also.  I have reached the point of diminishing returns working on this issue and I really only have the the idea I posted above.  I will disengage from this issue for the time being.  Let me know if you would like me to re-engage this issue.

**Comment by jzgithub1** [comment]
@ctubbsii ,  the addOpenWals function ( where that assert statement exists)  is called on lines 140 and 183.  You are observing it fail on line 140 from the call stack above.  At that point in the test neither of the two BatchWriters have been flushed to at all.  On my system there are two open WALs after the addOpenWals function on line 140 (I would have thought there would be zero at that point).  If you were asserting on the addOpenWals call on line 183 (after data was flushed) I would be more concerned.  

In any case, the intent of this test in explained in the issue #854 which was the reason the test was made.  My understanding of #854 is that the intent of this test is to demonstrate that if a " tablet server   has more than 5 write ahead logs then it should probably minor compact/flush any tablet referencing the WALs created before the 5th one. These tablets themselves may have less than 5 write ahead logs".  Less than five means that zero might be OK.  @keith-turner what do you think about allowing the open WALs to be equal zero?

**Comment by milleruntime** [comment]
The original issue that this IT was added, may still exist in 1.9.  https://github.com/apache/accumulo/issues/1336
