### ISSUE TITLE
Determine if files are deleted from metadata table when using volume.replacements

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1502]
It's possible that when a tablet is loading and it replaces volumes that it may forget the original strings that are stored in the metadata table.  This would cause compactions to not delete the files being compacted from the metadata table.  Not completely sure if this is the case, opening this issue to investigate.  Noticed this while reviewing #1501

**Comment by milleruntime** [comment]
I was able to confirm that "something is not right" when taking your suggestion on #1501 and throwing an Error on TabletFile.getMetadataEntry().  I ran VolumeIT (I think the only test where we use replacements) and it will just hang on the verify scan during testCleanReplaceVolumes().

**Comment by milleruntime** [comment]
Some more info from VolumeIT.testCleanReplaceVolumes() hanging... a jstack on the pid shows:
```
        at org.apache.accumulo.core.clientImpl.ThriftScanner.pause(ThriftScanner.java:232)
        at org.apache.accumulo.core.clientImpl.ThriftScanner.scan(ThriftScanner.java:283)
        at org.apache.accumulo.core.clientImpl.ScannerIterator.readBatch(ScannerIterator.java:155)
        - locked <0x00000000dcab2650> (a org.apache.accumulo.core.clientImpl.ThriftScanner$ScanState)
        at org.apache.accumulo.core.clientImpl.ScannerIterator.getNextBatch(ScannerIterator.java:173)
        at org.apache.accumulo.core.clientImpl.ScannerIterator.hasNext(ScannerIterator.java:109)
        at org.apache.accumulo.test.VolumeIT.verifyData(VolumeIT.java:176)
        at org.apache.accumulo.test.VolumeIT.verifyVolumesUsed(VolumeIT.java:303)
        at org.apache.accumulo.test.VolumeIT.testReplaceVolume(VolumeIT.java:449)
        at org.apache.accumulo.test.VolumeIT.testCleanReplaceVolumes(VolumeIT.java:486)
```
And the client log shows:
```2020-02-11 08:21:23,450 [clientImpl.ThriftScanner] DEBUG: Failed to locate tablet for table : 1 row : ```

**Comment by milleruntime** [comment]
> Some more info from VolumeIT.testCleanReplaceVolumes() hanging... a jstack on the pid shows:
> 
> ```
>         at org.apache.accumulo.core.clientImpl.ThriftScanner.pause(ThriftScanner.java:232)
>         at org.apache.accumulo.core.clientImpl.ThriftScanner.scan(ThriftScanner.java:283)
>         at org.apache.accumulo.core.clientImpl.ScannerIterator.readBatch(ScannerIterator.java:155)
>         - locked <0x00000000dcab2650> (a org.apache.accumulo.core.clientImpl.ThriftScanner$ScanState)
>         at org.apache.accumulo.core.clientImpl.ScannerIterator.getNextBatch(ScannerIterator.java:173)
>         at org.apache.accumulo.core.clientImpl.ScannerIterator.hasNext(ScannerIterator.java:109)
>         at org.apache.accumulo.test.VolumeIT.verifyData(VolumeIT.java:176)
>         at org.apache.accumulo.test.VolumeIT.verifyVolumesUsed(VolumeIT.java:303)
>         at org.apache.accumulo.test.VolumeIT.testReplaceVolume(VolumeIT.java:449)
>         at org.apache.accumulo.test.VolumeIT.testCleanReplaceVolumes(VolumeIT.java:486)
> ```
> 
> And the client log shows:
> `2020-02-11 08:21:23,450 [clientImpl.ThriftScanner] DEBUG: Failed to locate tablet for table : 1 row : `

Nevermind this stacktrace was for a bug I had in my code.

**Comment by milleruntime** [comment]
I was able to see an error when initializing a Tablet with the replaced volumes but this is expected since the file is in the list of fliesToAdd when updating tablet volumes.
```
java.lang.IllegalStateException: TabletFile does not have a metadata entry.
        at org.apache.accumulo.core.metadata.TabletFile.getMetadataEntry(TabletFile.java:111)
        at org.apache.accumulo.core.metadata.TabletFile.getMetadataText(TabletFile.java:119)
        at org.apache.accumulo.server.metadata.TabletMutatorBase.putFile(TabletMutatorBase.java:75)
        at java.base/java.util.TreeMap.forEach(TreeMap.java:1002)
        at org.apache.accumulo.server.util.MetadataTableUtil.updateTabletVolumes(MetadataTableUtil.java:221)
        at org.apache.accumulo.server.fs.VolumeUtil.updateTabletVolumes(VolumeUtil.java:178)
        at org.apache.accumulo.tserver.tablet.Tablet.<init>(Tablet.java:344)
        at org.apache.accumulo.tserver.TabletServer$AssignmentHandler.run(TabletServer.java:2496)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:37)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by keith-turner** [comment]
At the hackathon Tue I worked with @karthick-rn and @milleruntime and determined this not an issue.  @milleruntime found the place in the source where the delete happens, it happens when the tablet is loaded.  @karthick-rn ran a test on an Accumulo 2.0 cluster causing replacement to happen and we saw it functioned correctly.
