### ISSUE TITLE
Saw transient GcMetricsIT failure

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1591]
Stacktrace below. Given the code where this failed and the fact that it failed on Jenkins, I suspect this was because it picked up a metrics test output file from a previous run. This test should be reworked, so it uses a unique temporary file name for the metrics output, so it doesn't have issues when run concurrently with other tests, or accidentally pick up output files from previous runs.

```java
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.apache.accumulo.test.functional.GcMetricsIT.sanity(GcMetricsIT.java:155)
	at org.apache.accumulo.test.functional.GcMetricsIT.gcMetricsPublished(GcMetricsIT.java:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by EdColeman** [comment]
The filename is determined by the metrics config file - so just changing the filename may not be straight forward. Also, concurrent tests will be another issue - normally there would be only one gc running.

**Comment by ctubbsii** [comment]
It's also possible my assumption about how the test failed is wrong. I was going off of the embedded comment in the `gcMetricsPublished()` method, which explains that a previous run or another test could affect what is parsed from the file, since the file is appended to.

In the stack trace above, it appears the value parsed was of an event time that occurred before the current test started, which I thought could only make sense if it was from a different test... but I did not evaluate deeply.

**Comment by EdColeman** [comment]
I didn't look closely either - but I will.  Either this test or possibly one of fate metrics tests was written so that it looked for an update - I'll check that this code does the same thing and that it's working as I intended.
