### ISSUE TITLE
java.util.ServiceConfigurationError: org.apache.accumulo.start.spi.KeywordExecutable: Provider org.apache.accumulo.server.init.Initialize could not be instantiated

### ISSUE THREAD

**Issue by wangxiaofan777** [apache/accumulo#1741]
[vagrant@node-1 accumulo-2.0.0]$ ./bin/accumulo
2020-10-19 09:53:50,343 [start.Main] ERROR: Uncaught exception
java.util.ServiceConfigurationError: org.apache.accumulo.start.spi.KeywordExecutable: Provider org.apache.accumulo.server.init.Initialize could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.apache.accumulo.start.Main.checkDuplicates(Main.java:243)
        at org.apache.accumulo.start.Main.getExecutables(Main.java:234)
        at org.apache.accumulo.start.Main.printUsage(Main.java:213)
        at org.apache.accumulo.start.Main.main(Main.java:77)
Caused by: java.lang.NoClassDefFoundError: org/apache/zookeeper/KeeperException
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.KeeperException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 11 more

**Comment by ctubbsii** [comment]
@wangxiaofan777 If you are having trouble, please provide more than just a stack trace. Please provide information about how you encountered the stack trace... what did you do? What version are you using? What environment? What did you do to configure it?

**Comment by wangxiaofan777** [comment]
Ok, i follow the document(https://accumulo.apache.org/docs/2.x/getting-started/quickstart) to  install it .. My version is 2.0.0, i configured these files:
accumulo.properties
   instance.volumes=hdfs://node-1:8020/accumulo
   instance.zookeeper.host=node-1:2181
   trace.password=123456

accumulo-env.sh
   basedir=/usr/local/software/accumulo-2.0.0
   bin=/usr/local/software/accumulo-2.0.0/bin
   conf=/usr/local/software/accumulo-2.0.0/conf
   lib=/usr/local/software/accumulo-2.0.0/lib
   export ACCUMULO_LOG_DIR="${ACCUMULO_LOG_DIR:-${basedir}/logs}"
   export HADOOP_HOME="${HADOOP_HOME:-/usr/local/software/hadoop-3.3.0}"
   export HADOOP_CONF_DIR="${HADOOP_CONF_DIR:-${HADOOP_HOME}/etc/hadoop}"
   export ZOOKEEPER_HOME="${ZOOKEEPER_HOME:-${ZOOKEEPER_HOME}}"
then,i executed this command: ./bin/accumulo,after this, got exception

**Comment by EdColeman** [comment]
Which version of zookeeper are you using?  There have been recent classpath / directory issues between zookeeper versions – maybe the changes in these issue (https://github.com/apache/accumulo/pull/1716 or https://github.com/apache/accumulo/issues/1503) can help?

**Comment by wangxiaofan777** [comment]
The version of my zookeeper is  3.5.8....

**Comment by ctubbsii** [comment]
> The version of my zookeeper is 3.5.8....

Hi @wangxiaofan777 

Accumulo 2.0.0 was released with support for 3.4.14. However, starting with ZooKeeper 3.5, they moved their jars into a `lib/` subdirectory. So, you will need to modify the instructions slightly to add `$ZOOKEEPER_HOME/lib/*` to your `CLASSPATH` variable in your `accumulo-env.sh` .

I hope that helps.
