### ISSUE TITLE
IteratorEnvironment.getPluginEnv() is not implemented

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1766]
The new IteratorEnvironment.getPluginEnv() is not implemented and throws UnsupportedOperationException.  There was also a bug with the IteratorEnvIT, which was masking the issue.  The bug in IteratorEnvIT was fixed in 02f778a

**Comment by milleruntime** [comment]
From the tserver log when running IteratorEnvIT:
```
java.lang.UnsupportedOperationException: null
        at org.apache.accumulo.core.iterators.IteratorEnvironment.getPluginEnv(IteratorEnvironment.java:180) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.test.IteratorEnvIT.testEnv(IteratorEnvIT.java:157) ~[classes/:?]
        at org.apache.accumulo.test.IteratorEnvIT$ScanIter.init(IteratorEnvIT.java:78) ~[classes/:?]
        at org.apache.accumulo.core.conf.IterConfigUtil.loadIterators(IterConfigUtil.java:221) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.tablet.ScanDataSource.createIterator(ScanDataSource.java:226) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.tablet.ScanDataSource.iterator(ScanDataSource.java:120) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.iteratorsImpl.system.SourceSwitchingIterator.seek(SourceSwitchingIterator.java:228) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.tablet.Tablet.nextBatch(Tablet.java:706) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.tablet.Scanner.read(Scanner.java:108) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.scan.NextBatchTask.run(NextBatchTask.java:74) [accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.session.ScanSession$ScanMeasurer.run(ScanSession.java:54) [accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.htrace.wrappers.TraceRunnable.run(TraceRunnable.java:57) [htrace-core-3.2.0-incubating.jar:3.2.0-incubating]
```

**Comment by ctubbsii** [comment]
This is a simple fix. I'll knock this out.

**Comment by milleruntime** [comment]
> This is a simple fix. I'll knock this out.

Thanks.  I was in the middle of a few other unrelated tasks and didn't want to get side tracked.
