### ISSUE TITLE
Flaky test: FateStarvationIT

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1790]
**Test name(s)**
 - org.apache.accumulo.test.functional.FateStarvationIT

**Describe the failure observed**
The test timed out repeatedly after 120 seconds, and on the final run, failed in the `AccumuloClusterHarness.setupCluster` with an assertion error (probably caused by previous failed runs, but the test framework should try to be robust against such issues):
```java
[ERROR] run(org.apache.accumulo.test.functional.FateStarvationIT)  Time elapsed: 1.95 s  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.apache.accumulo.harness.AccumuloITBase.createTestDir(AccumuloITBase.java:76)
	at org.apache.accumulo.harness.MiniClusterHarness.create(MiniClusterHarness.java:146)
	at org.apache.accumulo.harness.MiniClusterHarness.create(MiniClusterHarness.java:105)
	at org.apache.accumulo.harness.AccumuloClusterHarness.setupCluster(AccumuloClusterHarness.java:127)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Testing Environment:**
 - Version of this project: 2.1.0-SNAPSHOT
 - First commit known to fail (or current commit): 5cb30ed0e9a7f3d481ea49dd126d64cc7ab9ef53
 - Jenkins shows:
```
Executing Maven:  -B -f /home/jenkins/workspace/Accumulo/main/pom.xml -V -e -ntp clean verify -Dstyle.color=always -Dfailsafe.rerunFailingTestsCount=5 -Dsurefire.forkCount=2C
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/asfpackages/maven/apache-maven-3.6.3
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /usr/local/asfpackages/java/jdk-11.0.6
Default locale: en_US, platform encoding: ISO-8859-1
OS name: "linux", version: "4.15.0-74-generic", arch: "amd64", family: "unix"
```

**Comment by ctubbsii** [comment]
I saw this flake out again more recently, while testing #3035:

```
[INFO] Running org.apache.accumulo.test.functional.FateStarvationIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 69.876 s <<< FAILURE! - in org.apache.accumulo.test.functional.FateStarvationIT
[ERROR] org.apache.accumulo.test.functional.FateStarvationIT.run  Time elapsed: 69.234 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /accumulo/6702ad71-c63f-43c1-893e-2846001343c5/fate/tx_69f49eff35439e9a
	at org.apache.accumulo.core.fate.ZooStore.top(ZooStore.java:322)
	at org.apache.accumulo.core.fate.ZooStore.top(ZooStore.java:57)
	at org.apache.accumulo.core.fate.AdminUtil.getTransactionStatus(AdminUtil.java:382)
	at org.apache.accumulo.core.fate.AdminUtil.getStatus(AdminUtil.java:261)
	at org.apache.accumulo.test.functional.FunctionalTestUtils.getFateStatus(FunctionalTestUtils.java:220)
	at org.apache.accumulo.test.functional.FunctionalTestUtils.assertNoDanglingFateLocks(FunctionalTestUtils.java:206)
	at org.apache.accumulo.test.functional.FateStarvationIT.run(FateStarvationIT.java:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.AssertTimeoutPreemptively.lambda$submitTask$3(AssertTimeoutPreemptively.java:95)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /accumulo/6702ad71-c63f-43c1-893e-2846001343c5/fate/tx_69f49eff35439e9a
	at org.apache.accumulo.core.fate.ZooStore.top(ZooStore.java:310)
	... 18 more
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /accumulo/6702ad71-c63f-43c1-893e-2846001343c5/fate/tx_69f49eff35439e9a
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:118)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:2366)
	at org.apache.accumulo.core.fate.zookeeper.ZooReader.lambda$getChildren$6(ZooReader.java:107)
	at org.apache.accumulo.core.fate.zookeeper.ZooReader.retryLoopMutator(ZooReader.java:185)
	at org.apache.accumulo.core.fate.zookeeper.ZooReader.retryLoop(ZooReader.java:164)
	at org.apache.accumulo.core.fate.zookeeper.ZooReader.retryLoop(ZooReader.java:151)
	at org.apache.accumulo.core.fate.zookeeper.ZooReader.getChildren(ZooReader.java:107)
	at org.apache.accumulo.core.fate.ZooStore.findTop(ZooStore.java:329)
	at org.apache.accumulo.core.fate.ZooStore.top(ZooStore.java:305)
	... 18 more
```

**Comment by milleruntime** [comment]
Assuming that ZK couldn't be reached for whatever reason, it looks like the `top()` method in ZooStore has code to retry. But there is an additional try/catch within the retry that will bypass the retry loop and throw a RuntimeException. So if connection is lost at the right moment, it won't retry. Did you see any retries with this messsage: `        log.debug("zookeeper error reading " + txpath + ": " + ex, ex);
`?

It seems like we should just drop the try/catch around this call:
https://github.com/apache/accumulo/blob/2dbdc085390794e7925740a81439c66dc3dfbb7c/core/src/main/java/org/apache/accumulo/core/fate/ZooStore.java#L305

I don't know why we need nested try/catch statements. It doesn't make sense why we would want to retry when making a ZK call to `getData()` but not `getChildren()`.

**Comment by ctubbsii** [comment]
Haven't been able to reproduce this in quite some time.
