### ISSUE TITLE
Flaky test: ManagerMetricsIT

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1793]
**Test name(s)**
 - org.apache.accumulo.test.functional.MasterMetricsIT.compactionMetrics

**Describe the failure observed**
Test timed out after 240 seconds
```java
org.junit.runners.model.TestTimedOutException: test timed out after 240 seconds
	at java.base@11.0.6/java.lang.Thread.sleep(Native Method)
	at app//org.apache.accumulo.test.functional.MasterMetricsIT.blockForRequiredTables(MasterMetricsIT.java:229)
	at app//org.apache.accumulo.test.functional.MasterMetricsIT.compactionMetrics(MasterMetricsIT.java:171)
	at java.base@11.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
<details>
<summary>STDOUT had a curious comment about tasks remaining in a threadpool when stopped (click to expand)</summary>

```
2020-11-17T06:49:27,348 [conf.AccumuloClusterPropertyConfiguration] DEBUG: No properties file found in accumulo.it.properties
2020-11-17T06:49:27,354 [conf.AccumuloClusterPropertyConfiguration] INFO : Using MINI cluster type from system properties
2020-11-17T06:49:27,356 [conf.AccumuloMiniClusterConfiguration] DEBUG: SASL is not enabled
2020-11-17T06:49:45,679 [miniclusterImpl.MiniAccumuloClusterImpl] INFO : Starting MAC against instance miniInstance and zookeeper(s) localhost:41755.
2020-11-17T06:49:49,916 [zookeeper.ZooSession] DEBUG: Connecting to localhost:41755 with timeout 30000 with auth
2020-11-17T06:49:49,942 [common.X509Util] INFO : Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
2020-11-17T06:49:51,197 [rpc.SaslConnectionParams] DEBUG: Kerberos krb5 configuration not found, setting default realm to empty
2020-11-17T06:50:05,351 [util.SlowOps] INFO : Created table id: 1, name 'MasterMetricsIT_compactionMetrics0_0'
2020-11-17T06:50:06,055 [util.SlowOps] INFO : Starting compaction.  Attempt 1
2020-11-17T06:50:09,114 [util.SlowOps] DEBUG: Compaction running for MasterMetricsIT_compactionMetrics0_0
2020-11-17T06:50:09,114 [functional.MasterMetricsIT] INFO : Received metrics LineUpdate{lastUpdate=17612465191, line='1605595803974 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:50:14,125 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=22614571878, line='1605595808974 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:50:24,126 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=32620141516, line='1605595818973 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:50:34,128 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=42626257486, line='1605595828974 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:50:44,129 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=52632010832, line='1605595838974 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:50:54,130 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=62637517121, line='1605595848975 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:51:04,131 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=72643292369, line='1605595858974 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:51:14,132 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=82648823492, line='1605595868975 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:51:24,133 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=92654217724, line='1605595878974 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:51:34,134 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=102659397669, line='1605595888975 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:51:44,135 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=112664955896, line='1605595898974 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:51:54,136 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=122670547662, line='1605595908974 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:52:04,137 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=132676153586, line='1605595918975 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:52:06,760 [clientImpl.ThriftTransportPool] WARN : Thread "pool-3-thread-1" stuck on IO to asf923.gq1.ygridcore.net:40501 (0) for at least 120050 ms
2020-11-17T06:52:14,138 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=142681699199, line='1605595928977 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:52:24,140 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=152687328299, line='1605595938974 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:52:34,141 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=162692910829, line='1605595948975 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:52:44,142 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=172698527676, line='1605595958975 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:52:54,143 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=182704184766, line='1605595968975 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:53:04,144 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=192709622162, line='1605595978974 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:53:14,145 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=202715340702, line='1605595988974 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:53:24,146 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=212721040707, line='1605595998974 master.fate: Context=master, ProcessName=Master, Hostname=asf923.gq1.ygridcore.net, currentFateOps=0, totalFateOps=4, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2020-11-17T06:53:27,377 [miniclusterImpl.MiniAccumuloClusterImpl] WARN : Unexpectedly had 4 task(s) remaining in threadpool for execution when being stopped
```

</details>

**Testing Environment:**
 - Version of this project: 2.1.0-SNAPSHOT
 - First commit known to fail (or current commit): 28ba8434334293d4bff9683464b293cd4540c245
 - Jenkins:
```
Executing Maven:  -B -f /home/jenkins/workspace/Accumulo/main/pom.xml -V -e -ntp clean verify -Dstyle.color=always -Dfailsafe.rerunFailingTestsCount=5 -Dsurefire.forkCount=2C
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/asfpackages/maven/apache-maven-3.6.3
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /usr/local/asfpackages/java/jdk-11.0.6
Default locale: en_US, platform encoding: ISO-8859-1
OS name: "linux", version: "4.15.0-74-generic", arch: "amd64", family: "unix"
```

**Comment by DomGarguilo** [comment]
Normally this test will create a slow op for a compaction then enter into a loop to wait until it shows up in the metrics file. To complete successfully, in the file `currentFateOps` will be ` >= tableCount`. Typically, this takes some time to happen and will appear in the file after about a minute. Somehow `currentFateOps` was always zero and `totalFateOps` was always 4. or comparison, this is how the output of the test should look.

<details>

```
2021-07-29T15:29:06,002 [util.SlowOps] INFO : Created table id: 1, name 'MasterMetricsIT_compactionMetrics0_0'
2021-07-29T15:29:06,263 [util.SlowOps] INFO : Starting compaction.  Attempt 1
2021-07-29T15:29:09,303 [util.SlowOps] DEBUG: Compaction running for MasterMetricsIT_compactionMetrics0_0
2021-07-29T15:29:09,303 [functional.MasterMetricsIT] INFO : Received metrics LineUpdate{lastUpdate=15017606383, line='1627586943249 master.fate: Context=master, ProcessName=Master, Hostname=thor, currentFateOps=0, totalFateOps=0, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2021-07-29T15:29:14,318 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=20019595081, line='1627586948250 master.fate: Context=master, ProcessName=Master, Hostname=thor, currentFateOps=0, totalFateOps=0, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2021-07-29T15:29:24,319 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=30026699322, line='1627586958252 master.fate: Context=master, ProcessName=Master, Hostname=thor, currentFateOps=0, totalFateOps=0, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2021-07-29T15:29:34,319 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=40034605394, line='1627586968244 master.fate: Context=master, ProcessName=Master, Hostname=thor, currentFateOps=0, totalFateOps=0, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2021-07-29T15:29:44,320 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=50042852335, line='1627586978249 master.fate: Context=master, ProcessName=Master, Hostname=thor, currentFateOps=0, totalFateOps=0, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2021-07-29T15:29:54,320 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=60051744888, line='1627586988245 master.fate: Context=master, ProcessName=Master, Hostname=thor, currentFateOps=0, totalFateOps=0, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0'}
2021-07-29T15:30:04,321 [functional.MasterMetricsIT] INFO : Received metrics update LineUpdate{lastUpdate=70056551575, line='1627586998247 master.fate: Context=master, ProcessName=Master, Hostname=thor, currentFateOps=1, totalFateOps=3, totalZkConnErrors=0, FateTxState_NEW=0, FateTxState_IN_PROGRESS=1, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_FAILED=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0, FateTxOpType_CompactRange=1'}
2021-07-29T15:30:04,322 [functional.MasterMetricsIT] INFO : Found required number of fate operations
2021-07-29T15:30:04,322 [functional.MasterMetricsIT] ERROR: IN_PROGRESS: 1
2021-07-29T15:30:09,706 [functional.MasterMetricsIT] INFO : Received metrics {1627587003247 master.fate: Context=master, FateTxOpType_CompactRange=1, FateTxState_FAILED=0, FateTxState_FAILED_IN_PROGRESS=0, FateTxState_IN_PROGRESS=1, FateTxState_NEW=0, FateTxState_SUCCESSFUL=0, FateTxState_UNKNOWN=0, Hostname=thor, ProcessName=Master, currentFateOps=1, totalFateOps=3, totalZkConnErrors=0}
```
</details>

My guess is that this is not an issue with the test. Potentially the slow op was not actually slow and completed faster than expected

**Comment by DomGarguilo** [comment]
> STDOUT had a curious comment about tasks remaining in a threadpool when stopped

As for this comment, I can reproduce it by making it so the test reaches its timeout while in the loop in `ManagerMetricsIT.blockForRequiredTables()`. I think this happens because the compactions are never cancelled (which is taken care of after `blockForRequiredTables()` completes.

**Comment by DomGarguilo** [comment]
It looks like there was a ticket previous to this one, #1598 (and subsequent PR #1599) which aimed to fix this issue by reducing the resources this test uses. It does seem like this error is transient and not easily reproducible. Not to sure what else can be done to make this test more reliable.

**Comment by ctubbsii** [comment]
To be fair, I haven't seen it in awhile, so we can close this for now.
