### ISSUE TITLE
Broken or Flaky test: SuspendedTabletsIT

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1806]
**Test name(s)**
 - org.apache.accumulo.test.master.SuspendedTabletsIT

**Describe the failure observed**
```java
2020-11-24T14:18:55,761 [master.Master] DEBUG: [Metadata Tablets] sleeping for 60.00 seconds        
2020-11-24T14:18:55,762 [master.Master] DEBUG: 3 assigned to dead servers: [1;3;29@(localhost:43027[10003cc6ca20002],null,null), 1;4;3@(localhost:43027[10003cc6ca20002],null,null), 1;5;4@(localhost:43027[10003cc6ca20002],null,null)]...
2020-11-24T14:18:55,762 [master.Master] DEBUG: logs for dead servers: {localhost:43027[10003cc6ca20002]=[file:/home/christopher/git/apache/accumulo/accumulo/test/target/mini-tests/org.apache.accumulo.test.master.SuspendedTabletsIT_shutdownAndResumeTserver/accumulo/wal/localhost+43027/cbc1e3e0-31ed-4408-8edc-afc8ec92d178, file:/home/christopher/git/apache/accumulo/accumulo/test/target/mini-tests/org.apache.accumulo.test.master.SuspendedTabletsIT_shutdownAndResumeTserver/accumulo/wal/localhost+43027/ea5759f4-9818-449b-94b6-19d852dc1f6a]}
2020-11-24T14:18:55,765 [master.Master] ERROR: Error processing table state for store Normal Tablets
java.lang.NullPointerException: Cannot invoke "org.apache.accumulo.core.metadata.TServerInstance.getHostAndPort()" because "tls.current" is null
  at org.apache.accumulo.server.master.state.LoggingTabletStateStore.suspend(LoggingTabletStateStore.java:88) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
  at org.apache.accumulo.master.TabletGroupWatcher.handleDeadTablets(TabletGroupWatcher.java:861) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
  at org.apache.accumulo.master.TabletGroupWatcher.flushChanges(TabletGroupWatcher.java:911) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT] 
  at org.apache.accumulo.master.TabletGroupWatcher.run(TabletGroupWatcher.java:320) [accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
```

**Testing Environment:**
 - Version of this project: 2.1.0-SNAPSHOT
 - First commit known to fail (or current commit): uncertain; current commit on main branch is f279ae8aa5abde0511fdfefbcfc7338e17f4f7ec
```Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/christopher/apps/maven/current
Java version: 15.0.1, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-15-openjdk-15.0.1.9-1.rolling.fc32.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.9.9-100.fc32.x86_64", arch: "amd64", family: "unix"
```

**What have you tried already?**
I tried reverting #1799 but the test timed out, so I was not able to verify it was related.

**Additional context**
The last successful build in Jenkins where this test did not fail is d33e07a12f08063d33dfbeb9e8b6aa95afe0f2f4, so the only commit since then is #1799, which made me think it was related. But, it might not be related.

**Comment by milleruntime** [comment]
I ran this IT prior to my changes for #1774 and it timed out.  It did not have that same error though so that is something different at least.  I do think this IT was flaky before though.

**Comment by ctubbsii** [comment]
Oops, apparently, I've opened similar tickets about this test in the past. While things may have gotten worse for this test recently, the overall problems with this test are already being tracked in another issue: #1791
