### ISSUE TITLE
DefaultCompactionPlanner failing checkArgument preventing compaction

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1853]
I saw this running Randomwalk (conditional test) on 2.1 snapshot.  The randomwalk tests have not been updated to use the new compaction features so this is likely to happen in production if not fixed.  I noticed that something was holding up the test and didn't see this error until switching to DEBUG.  So we also may want to bump this log message up to WARN. 

<pre>
2021-01-05T10:28:03,584 [compactions.CompactionService] DEBUG: Planner failed org.apache.accumulo.core.spi.compaction.DefaultCompactionPlanner h;b200;b100 SYSTEM Optional[Files [allFiles=[[F00000bl.rf, 3371 2000
0], [F0000b1j.rf, 18736 120000], [F00000ca.rf, 6465 40000], [F0000az7.rf, 12610 80000], [F00000dl.rf, 3380 20000], [F00000d4.rf, 7005 44000], [F0000azl.rf, 18734 120000], [F0000b17.rf, 18737 120000], [F0000b13.r
f, 27915 180000], [F00000bv.rf, 6435 40000], [F00000dr.rf, 9529 60000], [F0000azd.rf, 15651 100000], [F00000co.rf, 6469 40000], [F0000b0i.rf, 15649 100000], [F00000l7.rf, 3372 20000], [F0000ayx.rf, 3376 20000], 
[F00000bf.rf, 3370 20000], [F00000dc.rf, 10089 63998], [F00000cu.rf, 5130 32002], [F0000azw.rf, 21810 140000], [F00000m2.rf, 12590 80000], [F0000b09.rf, 18764 120000], [F0000b0q.rf, 24898 160000], [F0000b23.rf, 
21790 140000]], candidates=[[F00000bl.rf, 3371 20000], [F0000b1j.rf, 18736 120000], [F00000ca.rf, 6465 40000], [F0000az7.rf, 12610 80000], [F00000dl.rf, 3380 20000], [F00000d4.rf, 7005 44000], [F0000azl.rf, 1873
4 120000], [F0000b17.rf, 18737 120000], [F0000b13.rf, 27915 180000], [F00000bv.rf, 6435 40000], [F00000dr.rf, 9529 60000], [F0000azd.rf, 15651 100000], [F00000co.rf, 6469 40000], [F0000b0i.rf, 15649 100000], [F0
0000l7.rf, 3372 20000], [F0000ayx.rf, 3376 20000], [F00000bf.rf, 3370 20000], [F00000dc.rf, 10089 63998], [F00000cu.rf, 5130 32002], [F0000azw.rf, 21810 140000], [F00000m2.rf, 12590 80000], [F0000b09.rf, 18764 1
20000], [F0000b0q.rf, 24898 160000], [F0000b23.rf, 21790 140000]], compacting=[], hints={}]]
java.lang.IllegalArgumentException: null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128) ~[guava-28.2-jre.jar:?]
        at org.apache.accumulo.core.spi.compaction.DefaultCompactionPlanner.findMapFilesToCompact(DefaultCompactionPlanner.java:373) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.spi.compaction.DefaultCompactionPlanner.findMapFilesToCompact(DefaultCompactionPlanner.java:320) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.spi.compaction.DefaultCompactionPlanner.makePlan(DefaultCompactionPlanner.java:164) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.compactions.CompactionService.planCompaction(CompactionService.java:285) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.compactions.CompactionService.lambda$compact$3(CompactionService.java:207) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
</pre>

**Comment by milleruntime** [comment]
The check that is failing is here:
`
Preconditions.checkArgument(currSize >= sortedFiles.get(c - 1).getEstimatedEntries());
`
Due to the previous file size exceeding the current file size.  It seems this is indicating that the files are not sorted.

**Comment by milleruntime** [comment]
Looking at the code I think something is wrong with the values being compared.  We are comparing the estimatedSize of one entry with the estimatedEntries of the other.  
https://github.com/apache/accumulo/blob/97de2d819ee5ff4fb09513c662eed6e1368f1318/core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java#L370-L373
It looks like the value of `getEstimatedSize()` should be compared.
