### ISSUE TITLE
ClassCastException in CompactionExecutor cancel

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1875]
Saw this exception running CI on 2.1 snapshot:
<pre>
java.lang.ClassCastException: class org.apache.htrace.wrappers.TraceRunnable cannot be cast to class org.apache.accumulo.tserver.compactions.CompactionExecutor$CompactionTask (org.apache.htrace.wrappers.TraceRunnable and org.apache.accumulo.tserver.compactions.CompactionExecutor$CompactionTask are in unnamed module of loader 'app')
	at org.apache.accumulo.tserver.compactions.CompactionExecutor$CompactionTask.lambda$cancel$0(CompactionExecutor.java:120)
	at java.base/java.util.concurrent.PriorityBlockingQueue.bulkRemove(PriorityBlockingQueue.java:1064)
	at java.base/java.util.concurrent.PriorityBlockingQueue.removeIf(PriorityBlockingQueue.java:1024)
	at org.apache.accumulo.tserver.compactions.CompactionExecutor$CompactionTask.cancel(CompactionExecutor.java:120)
	at org.apache.accumulo.tserver.compactions.CompactionService.reconcile(CompactionService.java:185)
	at org.apache.accumulo.tserver.compactions.CompactionService.planCompaction(CompactionService.java:308)
	at org.apache.accumulo.tserver.compactions.CompactionService.lambda$compact$3(CompactionService.java:209)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
</pre>

**Comment by Manno15** [comment]
I will try to reproduce on my end and investigate. Did you do anything special beyond running CI? Was this running against main and with the most recent commit?

**Comment by milleruntime** [comment]
Not really, I just added some debugging for what I am working on.  I think the commit it was based off was: bbd87a6693fc5cdbbe947b0821a4f05a18cf905b

**Comment by Manno15** [comment]
Okay, I will see what I come up with.

**Comment by milleruntime** [comment]
I was trying to reproduce #1775 and did change `tserver.hold.time.max` to 5s.  Although, I was unable to reproduce the monitor error, I did see this error happen twice.

**Comment by Manno15** [comment]
I got the error now. I wonder if it's tied to the hold time as I wasn't getting it until after I changed that.

**Comment by milleruntime** [comment]
I looks like it only happens when a compaction is cancelled.  It is because the comparator that is used on the queue will sometimes return a `TraceRunnable` object since these can exist on the queue as well.  The cast in the `removeIf` check needs to mirror what is going on in this method:
https://github.com/apache/accumulo/blob/e62ace6a9d37572d95999f5412c6148efbba50b9/server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionExecutor.java#L128-L138

**Comment by milleruntime** [comment]
@Manno15 I think I fixed this issue in #1876 but I wouldn't mind for you to give it a test to see if you can see the error again, since you saw it as well.

**Comment by Manno15** [comment]
I will test and let you know.
