### ISSUE TITLE
TabletStateChangeIteratorIT Failing

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1932]
The test is failing consistently for me. It is timing out while waiting for the batch writer to close.
<pre>
[ERROR] test(org.apache.accumulo.test.functional.TabletStateChangeIteratorIT)  Time elapsed: 180.016 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 180 seconds
	at java.base@11.0.10/java.lang.Object.wait(Native Method)
	at java.base@11.0.10/java.lang.Object.wait(Object.java:328)
	at app//org.apache.accumulo.core.clientImpl.TabletServerBatchWriter.waitRTE(TabletServerBatchWriter.java:470)
	at app//org.apache.accumulo.core.clientImpl.TabletServerBatchWriter.close(TabletServerBatchWriter.java:340)
	at app//org.apache.accumulo.core.clientImpl.BatchWriterImpl.close(BatchWriterImpl.java:57)
	at app//org.apache.accumulo.test.functional.TabletStateChangeIteratorIT.copyTable(TabletStateChangeIteratorIT.java:255)
	at app//org.apache.accumulo.test.functional.TabletStateChangeIteratorIT.test(TabletStateChangeIteratorIT.java:110)
</pre>

**Comment by milleruntime** [comment]
While I was looking at why this test was passing in 1.10, I added improvements to the test so I figured might as well merge them in case we start seeing failures in 1.10 as well. Opened #1933
