### ISSUE TITLE
DefaultContextClassLoaderFactory fails to load

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1978]
**Describe the bug**
DefaultContextClassLoaderFactory fails to load when configured for the "general.context.class.loader.factory" property.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Configure the property: general.context.class.loader.factory=org.apache.accumulo.core.classloader.DefaultContextClassLoaderFactory
2. Start up accumulo
3. Tablet server will start up then die with the following error

<pre>
2021-03-26T17:48:14,259 [classloader.ClassLoaderUtil] INFO : Creating org.apache.accumulo.core.spi.common.ContextClassLoaderFactory: org.apache.accumulo.core.classloader.DefaultContextClassLoaderFactory
2021-03-26T17:48:14,259 [start.Main] ERROR: Thread 'tserver' died.
java.lang.IllegalStateException: Unable to load and initialize class: org.apache.accumulo.core.classloader.DefaultContextClassLoaderFactory
        at org.apache.accumulo.core.classloader.ClassLoaderUtil.initContextFactory(ClassLoaderUtil.java:55) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.AbstractServer.<init>(AbstractServer.java:53) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.TabletServer.<init>(TabletServer.java:239) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.TabletServer.main(TabletServer.java:233) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.TServerExecutable.execute(TServerExecutable.java:45) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.start.Main.lambda$execKeyword$0(Main.java:126) ~[accumulo-start-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodException: org.apache.accumulo.core.classloader.DefaultContextClassLoaderFactory.<init>()
        at java.lang.Class.getConstructor0(Class.java:3349) ~[?:?]
        at java.lang.Class.getDeclaredConstructor(Class.java:2553) ~[?:?]
        at org.apache.accumulo.core.classloader.ClassLoaderUtil.initContextFactory(ClassLoaderUtil.java:53) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
</pre>

**Comment by dlmarion** [comment]
Thats the default value for the property, right? You are saying that setting it causes the error?

**Comment by ctubbsii** [comment]
The default value is an empty string, and it is constructed specially when no user implementation is provided. The DefaultContextClassLoaderFactory implements our built-in behavior, which can change over time, and should not be configured by users. The current implementation uses the SiteConfiguration and delegates to the AccumuloVFSClassLoader to preserve the previous VFS class loading behavior until that is removed.

This isn't a bug. It's not intended to be exposed to, or configured by, users. It is a special implementation for internal use and does not have a no-arg constructor and cannot be instantiated like a user-provided factory.

**Comment by milleruntime** [comment]
> The default value is an empty string, and it is constructed specially when no user implementation is provided. The DefaultContextClassLoaderFactory implements our built-in behavior, which can change over time, and should not be configured by users. The current implementation uses the SiteConfiguration and delegates to the AccumuloVFSClassLoader to preserve the previous VFS class loading behavior until that is removed.

OK then I guess the bug is in the default behavior of the empty string configuration, which I am seeing in #1976. I will close this and continue the discussion on that ticket.
