### ISSUE TITLE
Investigate exception from new sanity check

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1999]
After adding a new sanity for the sets of files passed between the tablet and a planner, the sanity check is catching an overlap in two sets files that are supposed to be disjoint.  The problem is transient, but it does hint that there is a bug.  Need to investigate this.

```
2021-04-04T13:21:16,194 [threads.AccumuloUncaughtExceptionHandler] ERROR: Caught an Exception in Thread[CompactionPlanner-Worker-1,5,main]. Thread is dead.
java.lang.IllegalArgumentException: Compacting and candidates overlap [[F0000000.rf, 257 5], [F0000001.rf, 231 2]] [[F0000001.rf, 231 2], [F0000000.rf, 257 5]]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:441) ~[guava-30.1-jre.jar:?]
	at org.apache.accumulo.tserver.compactions.Compactable$Files.<init>(Compactable.java:80) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.tserver.tablet.CompactableImpl.getFiles(CompactableImpl.java:524) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.tserver.compactions.CompactionService.planCompaction(CompactionService.java:247) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.tserver.compactions.CompactionService.lambda$compact$4(CompactionService.java:233) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
```

**Comment by dlmarion** [comment]
I just ran into this while testing with fluo-uno. This might be a blocker to testing. I'm going to dig in and see what I can find.

**Comment by dlmarion** [comment]
I made a change locally which seems to work. The change is to use `candidates` instead of `Set.copyOf(selectedFiles)` [here](https://github.com/apache/accumulo/blob/1451-external-compactions-feature/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java#L526). I think the issue is that `selectedFiles` is being modified in another thread (while loading data into the table new files are created when mutations are flushed from memory). In most cases modification of `selectedFiles` is done within a `synchronized(this)` block, except in one method where the method has the `synchronized` modifier.
