### ISSUE TITLE
Broken or Flaky test: ShellServerIT

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#2070]
**ShellServerIT**

**Describe the failure observed**
ShellServerIT is failing with two errors consistently.

ShellServerIT.testPertableClasspath times out.
<details>
  <summary>Click to expand!</summary>
  `ERROR] org.apache.accumulo.test.ShellServerIT.testPertableClasspath  Time elapsed: 60.007 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 60 seconds
	at java.base@11.0.11/java.lang.Object.wait(Native Method)
	at java.base@11.0.11/java.lang.Object.wait(Object.java:328)
	at app//org.apache.accumulo.core.clientImpl.TabletServerBatchWriter.waitRTE(TabletServerBatchWriter.java:470)
	at app//org.apache.accumulo.core.clientImpl.TabletServerBatchWriter.close(TabletServerBatchWriter.java:340)
	at app//org.apache.accumulo.core.clientImpl.BatchWriterImpl.close(BatchWriterImpl.java:57)
	at app//org.apache.accumulo.shell.commands.InsertCommand.execute(InsertCommand.java:112)
	at app//org.apache.accumulo.shell.Shell.execCommand(Shell.java:779)
	at app//org.apache.accumulo.test.ShellServerIT$TestShell.exec(ShellServerIT.java:219)
	at app//org.apache.accumulo.test.ShellServerIT$TestShell.exec(ShellServerIT.java:229)
	at app//org.apache.accumulo.test.ShellServerIT$TestShell.exec(ShellServerIT.java:224)
	at app//org.apache.accumulo.test.ShellServerIT.testPertableClasspath(ShellServerIT.java:1752)
	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.11/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base@11.0.11/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.11/java.lang.Thread.run(Thread.java:829)
`
</details>

ShellServerIT.durability - java.lang.AssertionError: expected:<0> but was:<1>
<details>
  <summary>Click to expand!</summary>
  `[ERROR] org.apache.accumulo.test.ShellServerIT.durability  Time elapsed: 1.639 s  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.apache.accumulo.test.ShellServerIT$TestShell.assertGoodExit(ShellServerIT.java:269)
	at org.apache.accumulo.test.ShellServerIT$TestShell.exec(ShellServerIT.java:255)
	at org.apache.accumulo.test.ShellServerIT$TestShell.exec(ShellServerIT.java:248)
	at org.apache.accumulo.test.ShellServerIT.durability(ShellServerIT.java:585)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
`
**Testing Environment:**
 - Version of this project: 2.1.0-SNAPSHOT
 - First commit known to fail (or current commit):
 - OS: ubuntu
 - Java: openjdk version "11.0.11" 
 - Maven: Apache Maven 3.6.3
 - Other environment details:

**What have you tried already?**
A clear and concise description of any steps you've already taken in an attempt to troubleshoot.

**Additional context**
Add any other context about the problem or your testing environment here.

**Comment by EdColeman** [comment]
The issue with the durability test appears to be that the table is scheduled for deletion about as soon as it is created, but the test method is still in progress.  The table deletion was being performed as a test after action - but deleted all tables.  Moving the clean-up to afterclass so it executes once, at the end of the test seems to have fixed that issue.  
`
2021-05-01T18:28:12,663 [accumulo.audit] INFO : operation: permitted; user: root; client: 127.0.0.1:44432; action: createTable; targetTable: durability_56910565297912;
...
2021-05-01T18:28:12,685 [tables.TableManager] DEBUG: Creating ZooKeeper entries for new table durability_56910565297912 (ID: 1o) in namespace (ID: +default)
...
2021-05-01T18:28:12,713 [manager.EventCoordinator] INFO : Created table durability_56910565297912 
...
2021-05-01T18:28:13,454 [accumulo.audit] INFO : operation: permitted; user: root; client: 127.0.0.1:44432; action: deleteTable; targetTable: durability_56910565297912;
`

**Comment by EdColeman** [comment]
The Pertable test seems to be failing because of mis-configuration or change in the constraint.

from the surefire test log

`
2021-05-01T19:34:05,631 [Shell.audit] INFO : root@miniInstance testPertableClasspath> insert foo f q v
2021-05-01T19:34:16,394 [vfs.ContextManager] DEBUG: Managed Contexts: {FAKE=org.apache.accumulo.start.classloader.vfs.ContextManager$Context@71ca96f1}
2021-05-01T19:34:16,394 [vfs.ContextManager] DEBUG: Configured Contexts: [FAKE]
2021-05-01T19:34:16,394 [vfs.ContextManager] DEBUG: Closing contexts: {}
2021-05-01T19:34:34,149 [clientImpl.ThriftTransportPool] WARN : Server myhost:33667 (120000) had 20 failures in a short time period, will not complain anymore
2021-05-01T19:35:04,408 [shell.Shell] ERROR: java.lang.RuntimeException: java.lang.InterruptedException
2021-05-01T19:35:04,408 [shell.Shell] DEBUG: java.lang.RuntimeException: java.lang.InterruptedException
`

from the tserver log:
`
2021-05-01T19:34:05,637 [rpc.CustomNonBlockingServer$CustomFrameBuffer] ERROR: Unexpected throwable while invoking!
java.lang.AbstractMethodError: Receiver class FooConstraint does not define or inherit an implementation of the resolved method 'abstract java.util.List check(org.apache.accumulo.core.data.constraints.Constraint$Environment, org.apache.accumulo.core.data.Mutation)' of interface org.apache.accumulo.core.data.constraints.Constraint.
        at org.apache.accumulo.tserver.constraints.ConstraintChecker.check(ConstraintChecker.java:104) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
`
full trace
<details>
  <summary>Click to expand!</summary>

2021-05-01T19:34:05,637 [rpc.CustomNonBlockingServer$CustomFrameBuffer] ERROR: Unexpected throwable while invoking!
java.lang.AbstractMethodError: Receiver class FooConstraint does not define or inherit an implementation of the resolved method 'abstract java.util.List check(org.apache.accumulo.core.data.constraints.Constraint$Environment, org.apache.accumulo.core.data.Mutation)' of interface org.apache.accumulo.core.data.constraints.Constraint.
        at org.apache.accumulo.tserver.constraints.ConstraintChecker.check(ConstraintChecker.java:104) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.tablet.Tablet.prepareMutationsForCommit(Tablet.java:1063) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.ThriftClientHandler.update(ThriftClientHandler.java:958) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.accumulo.core.trace.TraceUtil.lambda$wrapService$6(TraceUtil.java:235) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at com.sun.proxy.$Proxy31.update(Unknown Source) ~[?:?]
        at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Processor$update.getResult(TabletClientService.java:2932) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Processor$update.getResult(TabletClientService.java:2911) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) ~[libthrift-0.12.0.jar:0.12.0]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) ~[libthrift-0.12.0.jar:0.12.0]
        at org.apache.accumulo.server.rpc.TimedProcessor.process(TimedProcessor.java:63) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518) [libthrift-0.12.0.jar:0.12.0]
        at org.apache.accumulo.server.rpc.CustomNonBlockingServer$CustomFrameBuffer.invoke(CustomNonBlockingServer.java:114) [accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.thrift.server.Invocation.run(Invocation.java:18) [libthrift-0.12.0.jar:0.12.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

</details>

**Comment by EdColeman** [comment]
The FooConstraints jar uses deprecated Constraints class. The jar has:
`
import org.apache.accumulo.core.constraints.Constraint;
import org.apache.accumulo.core.constraints.Constraint.Environment;

expected (since 2.1) (moved from core to data)

org.apache.accumulo.core.data.constraints.Constraint
org.apache.accumulo.core.data.constraints.Constraint.Environment
`
It should be possible to rebuild the jar using new packages, and that might get the test to pass - but not sure how to handle pre-2.1 code.

**Comment by ctubbsii** [comment]
@EdColeman I edited your description and comments above to use triple backticks for the code blocks, and to add blank lines between the `<details>` HTML tags and the markdown code blocks, so they rendered correctly.

**Comment by milleruntime** [comment]
> java.lang.AbstractMethodError: Receiver class FooConstraint does not define or inherit an implementation of the resolved method 'abstract java.util.List check(org.apache.accumulo.core.data.constraints.Constraint$Environment, org.apache.accumulo.core.data.Mutation)' of interface org.apache.accumulo.core.data.constraints.Constraint.
        at org.apache.accumulo.tserver.constraints.ConstraintChecker.check(ConstraintChecker.java:104)

This is a regression with the changes I made to the Constraints API. It was still supposed to work with existing constraints. I will look at this part. I am not sure why the `durability()` test would be failing.
