### ISSUE TITLE
NoSuchMethodException using HostRegexTableLoadBalancer

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2121]
The runtime class loading of the `HostRegexTableLoadBalancer` is broken. It is likely this happened when it was refactored during the move to SPI. This exception can be seen in the manager log when running `SuspendedTabletsIT`, which seems to timeout often for me locally but the test can still pass even with this exception.
<pre>
2021-05-27T10:39:11,473 [balancer.TableLoadBalancer] WARN : Failed to load table balancer class org.apache.accumulo.core.spi.balancer.HostRegexTableLoadBalancer for table !0
java.lang.NoSuchMethodException: org.apache.accumulo.core.spi.balancer.HostRegexTableLoadBalancer.<init>(org.apache.accumulo.core.data.TableId)
        at java.lang.Class.getConstructor0(Class.java:3349) ~[?:?]
        at java.lang.Class.getConstructor(Class.java:2151) ~[?:?]
        at org.apache.accumulo.core.spi.balancer.TableLoadBalancer.constructNewBalancerForTable(TableLoadBalancer.java:58) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.spi.balancer.TableLoadBalancer.getBalancerForTable(TableLoadBalancer.java:91) [accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.spi.balancer.TableLoadBalancer.getAssignments(TableLoadBalancer.java:115) [accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.Manager.getAssignments(Manager.java:1735) [accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.TabletGroupWatcher.getAssignmentsFromBalancer(TabletGroupWatcher.java:880) [accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.TabletGroupWatcher.flushChanges(TabletGroupWatcher.java:911) [accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.TabletGroupWatcher.run(TabletGroupWatcher.java:318) [accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
2021-05-27T10:39:11,474 [balancer.TableLoadBalancer] INFO : Using balancer org.apache.accumulo.core.spi.balancer.SimpleLoadBalancer for table !0
</pre>

**Comment by brianloss** [comment]
@milleruntime Do you get this error every time you run the test? Anything special about your environment or how you are running the test? I have not been able to reproduce locally on my machine.

**Comment by milleruntime** [comment]
> @milleruntime Do you get this error every time you run the test? Anything special about your environment or how you are running the test? I have not been able to reproduce locally on my machine.

Yes it seems to WARN with the exception every time, whether the test passes or not. I don't know of anything special in my environment. It happens whether I run the test in Intellij individually or on the command line with all the ITs.

**Comment by brianloss** [comment]
Oops, I was just not looking at the right logs. I see the error now. This wasn't caused by moving balancers to the SPI but rather by PR #1888 instead. The test is setting the property TABLE_LOAD_BALANCER to HostRegexTableLoadBalancer, which is wrong since HostRegexTableLoadBalancer is a TableLoadBalancer and is intended to be used only with the property MANAGER_TABLET_BALANCER. This didn't change--the class HostRegexTableLoadBalancer never had a constructor with a single TableId parameter. I'll have a PR in a bit to fix. Given that, I'm going to remove the blocker label from this issue.

**Comment by milleruntime** [comment]
> Oops, I was just not looking at the right logs. I see the error now. This wasn't caused by moving balancers to the SPI but rather by PR #1888 instead. The test is setting the property TABLE_LOAD_BALANCER to HostRegexTableLoadBalancer, which is wrong since HostRegexTableLoadBalancer is a TableLoadBalancer and is intended to be used only with the property MANAGER_TABLET_BALANCER. This didn't change--the class HostRegexTableLoadBalancer never had a constructor with a single TableId parameter. I'll have a PR in a bit to fix. Given that, I'm going to remove the blocker label from this issue.

Ah ok thanks for looking into this!
