### ISSUE TITLE
Compactors stop working when seeing an unknown compaction exception

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#2124]
When a compactor sees an UnknownCompactionIdException when reporting status, it seems to stop working.  Below is an exception from when this happened.  The line numbers may a be a bit off as this exception was observed when testing the external compactions PR before it was merged.

```
2021-05-25T22:55:06,091 [compaction.RetryableThriftCall] ERROR: Error in Thrift function, retrying ...
org.apache.accumulo.core.compaction.thrift.UnknownCompactionIdException: null
	at org.apache.accumulo.core.compaction.thrift.CompactionCoordinatorService$updateCompactionStatus_result$updateCompactionStatus_resultStandardScheme.read(CompactionCoordinatorService.java:4339) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.core.compaction.thrift.CompactionCoordinatorService$updateCompactionStatus_result$updateCompactionStatus_resultStandardScheme.read(CompactionCoordinatorService.java:4325) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.core.compaction.thrift.CompactionCoordinatorService$updateCompactionStatus_result.read(CompactionCoordinatorService.java:4275) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:88) ~[libthrift-0.12.0.jar:0.12.0]
	at org.apache.accumulo.core.compaction.thrift.CompactionCoordinatorService$Client.recv_updateCompactionStatus(CompactionCoordinatorService.java:149) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.core.compaction.thrift.CompactionCoordinatorService$Client.updateCompactionStatus(CompactionCoordinatorService.java:131) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.compactor.Compactor$2.execute(Compactor.java:390) ~[accumulo-compactor-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.compactor.Compactor$2.execute(Compactor.java:385) ~[accumulo-compactor-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.server.compaction.RetryableThriftCall.run(RetryableThriftCall.java:107) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.compactor.Compactor.updateCompactionState(Compactor.java:399) ~[accumulo-compactor-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.compactor.Compactor.run(Compactor.java:714) ~[accumulo-compactor-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by dlmarion** [comment]
I don't believe the Compactor stops working in this case. I believe it will retry for some amount of time and then throw a RetriesExceededException. The Compactor will move onto the next compaction after this. In this case, the Coordinator does not know about the external compaction id for which the Compactor is running. It's most likely the case that the Coordinator was restarted and then it could not communicate with the Compactor when it was restarted.

**Comment by keith-turner** [comment]
> I don't believe the Compactor stops working in this case.

Ok so the problem is less severe than I thought.  Seems like it still worthwhile keeping this issues open because compaction work is lost and it may be worth exploring making this more resilient.

**Comment by keith-turner** [comment]
Wondering if it would make sense to change status reports from compactor to coordinator to async thrift messages and remove the UnknownCompactionIdException.  However I am not sure if this could lead to inconsistent status within the coordinator.

**Comment by dlmarion** [comment]
I'm thinking that we can just remove the UnknownCompactionIdException. It's thrown in 4 cases, 3 in the Coordinator (`compactionCompleted`, `compactionFailed`, and `updateCompactionStatus`) when the compaction does not exist in the RUNNING list. If the compaction is not in the RUNNING list the first time it's called, then it's likely never going to exist. However, in `compactionCompleted` and `compactionFailed`, the compactionFinalizer is called before the error is thrown. The 4th location is in the Compactor, when the Coordinator is trying to cancel the compaction, I think we should leave that one.
