### ISSUE TITLE
VerifySerialRecoveryIT failure

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2173]
This is due to recent changes to sorted log recovery in #2117. There is a bug in the new recovery code with the row byte encoding improperly encoding tabletIds greater than 127.

<pre>
java.lang.RuntimeException: Error recovering tablet 1;a24391d90602477b;a071870ae421babc from log files
        at org.apache.accumulo.tserver.tablet.Tablet.<init>(Tablet.java:407) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.AssignmentHandler.run(AssignmentHandler.java:160) [accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.ActiveAssignmentRunnable.run(ActiveAssignmentRunnable.java:63) [accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.htrace.wrappers.TraceRunnable.run(TraceRunnable.java:57) [htrace-core-3.2.0-incubating.jar:3.2.0-incubating]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.IOException: java.lang.IllegalStateException: tabletId -128 for 1;a24391d90602477b;a071870ae421babc is negative
        at org.apache.accumulo.tserver.log.TabletServerLogger.recover(TabletServerLogger.java:540) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.TabletServer.recover(TabletServer.java:1153) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.tablet.Tablet.<init>(Tablet.java:366) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        ... 6 more
Caused by: java.lang.IllegalStateException: tabletId -128 for 1;a24391d90602477b;a071870ae421babc is negative
        at com.google.common.base.Preconditions.checkState(Preconditions.java:707) ~[guava-30.1.1-jre.jar:?]
        at org.apache.accumulo.tserver.log.SortedLogRecovery.findMaxTabletId(SortedLogRecovery.java:120) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.log.SortedLogRecovery.findLogsThatDefineTablet(SortedLogRecovery.java:147) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.log.SortedLogRecovery.recover(SortedLogRecovery.java:291) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.log.TabletServerLogger.recover(TabletServerLogger.java:538) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.TabletServer.recover(TabletServer.java:1153) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.tablet.Tablet.<init>(Tablet.java:366) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        ... 6 more
</pre>

**Comment by ctubbsii** [comment]
I made some comments at https://github.com/apache/accumulo/pull/2117#pullrequestreview-690052589 and https://github.com/apache/accumulo/pull/2117#pullrequestreview-690053323 that might be related to this problem.
