### ISSUE TITLE
Failed to reconfigure compaction services

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2311]
I am getting this error while trying to run external compactions using Uno. 
<pre>
2021-10-08T14:30:10,916 [compactions.CompactionManager] ERROR: Failed to reconfigure compaction services 
java.lang.RuntimeException: Failed to create or update compaction service cs1 with planner:org.apache.accumulo.core.spi.compaction.DefaultCompactionPlanner options:{executors=[{"name":"small","type":"external","maxSize":"16M","queue":"MikeQ"},{"name":"large","type":"external","queue":"MikeQ"}]}
        at org.apache.accumulo.tserver.compactions.CompactionManager.lambda$checkForConfigChanges$1(CompactionManager.java:394) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.util.HashMap.forEach(HashMap.java:1336) ~[?:?]
        at org.apache.accumulo.tserver.compactions.CompactionManager.checkForConfigChanges(CompactionManager.java:375) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.compactions.CompactionManager.mainLoop(CompactionManager.java:278) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.compactions.CompactionManager.lambda$start$3(CompactionManager.java:420) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:130) ~[guava-30.1.1-jre.jar:?]
        at org.apache.accumulo.tserver.compactions.CompactionService$CpInitParams$1.getExternalExecutor(CompactionService.java:135) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.spi.compaction.DefaultCompactionPlanner.init(DefaultCompactionPlanner.java:183) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.compactions.CompactionService.<init>(CompactionService.java:159) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.compactions.CompactionManager.lambda$checkForConfigChanges$1(CompactionManager.java:384) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        ... 5 more
</pre>

I was using CI from accumulo-testing with these properties modified:
<pre>
test.ci.common.accumulo.server.props=\
tserver.compaction.major.service.cs1.planner=org.apache.accumulo.core.spi.compaction.DefaultCompactionPlanner \
tserver.compaction.major.service.cs1.planner.opts.executors=\
[{"name":"small","type":"external","maxSize":"16M","queue":"MikeQ"},\
{"name":"large","type":"external","queue":"MikeQ"}]

# Accumulo table properties to set when creating table
test.ci.common.accumulo.table.props=\
table.compaction.dispatcher=org.apache.accumulo.core.spi.compaction.SimpleCompactionDispatcher \
table.compaction.dispatcher.opts.service=cs1
</pre>

This was working for me previously so it is probably just something I did with the configuration.

**Comment by dlmarion** [comment]
The compaction service and its configuration are used in the tablet server. I'm not sure that the inability to reconfigure it and the use of external compaction processes are related. Has anyone tried to reconfigure it w/out using external compactions?

**Comment by DomGarguilo** [comment]
> Has anyone tried to reconfigure it w/out using external compactions?

Just double checked and it seems to be working fine.

**Comment by keith-turner** [comment]
> Oh, interesting. If it does cause problems (which so far it looks like it does weird things) then we should definitely check and error when configured that way.

I can look into this and see what the behavior is and if any additional validation of config is needed.
