### ISSUE TITLE
Broken or Flaky test: ExternalCompactionMetricsIT.testMetrics

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#2406]
**Describe the bug**
It looks ExternalCompactionMetricsIT.testMetrics timed out

**To Reproduce**
I was unable to reproduce this error.

**Additional context**
Here is the link to the failed run: https://ci-builds.apache.org/job/Accumulo/job/main/org.apache.accumulo$accumulo-test/247/testReport/junit/org.apache.accumulo.test.compaction/ExternalCompactionMetricsIT/testMetrics/

<details open>
<summary>Stacktrace</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 1800 seconds
	at java.base@11.0.12/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.12/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.12/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	at java.base@11.0.12/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
	at app//org.apache.accumulo.test.compaction.ExternalCompactionMetricsIT.testMetrics(ExternalCompactionMetricsIT.java:147)
	at java.base@11.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.12/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.12/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base@11.0.12/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.12/java.lang.Thread.run(Thread.java:834)
```

</details>

<details open>
<summary>Standard out</summary>

```
2021-12-30T04:53:14,828 [conf.AccumuloClusterPropertyConfiguration] DEBUG: No properties file found in accumulo.it.properties
2021-12-30T04:53:14,833 [conf.AccumuloClusterPropertyConfiguration] INFO : Using MINI cluster type from system properties
2021-12-30T04:53:14,834 [conf.AccumuloMiniClusterConfiguration] DEBUG: SASL is not enabled
2021-12-30T04:53:23,818 [miniclusterImpl.MiniAccumuloClusterImpl] INFO : Starting MAC against instance miniInstance and zookeeper(s) localhost:44137.
2021-12-30T04:53:28,087 [zookeeper.ZooSession] DEBUG: Connecting to localhost:44137 with timeout 30000 with auth
2021-12-30T04:53:28,105 [common.X509Util] INFO : Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
2021-12-30T04:53:32,515 [rpc.SaslConnectionParams] DEBUG: Kerberos krb5 configuration not found, setting default realm to empty
2021-12-30T04:53:37,772 [logging.InternalLoggerFactory] DEBUG: Using SLF4J as the default logging framework
```

</details>

It appears the test got stuck in this loop at line 147:
https://github.com/apache/accumulo/blob/12fe9633f6cdcac7a964d8fdfcec8c615aaf1629/test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionMetricsIT.java#L146-L150

Maybe the `LinkedBlockingQueue<Metric> queueMetrics` was blocking, waiting for metrics in the queue that never appeared.

**Comment by dlmarion** [comment]
So, this test runs with MAC and configures Accumulo to send metrics over UDP using the StatsD protocol. All of the Accumulo server processes send the metrics to a StatsD sink running in the IT process. I'm wondering if there was an issue with MAC in this case.
