### ISSUE TITLE
NPE in MiniAccumuloClusterImplTest

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2431]
The test passes but I saw this NullPointerException in the test output:
<pre>
2022-01-26T07:42:15,439 [zookeeper.ClientCnxn] ERROR: Error while calling watcher 
java.lang.NullPointerException: null
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:535) [zookeeper-3.5.9.jar:3.5.9]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:510) [zookeeper-3.5.9.jar:3.5.9]
</pre>

**Comment by ctubbsii** [comment]
I have a fix incoming.
