### ISSUE TITLE
Broken or Flaky test: ExternalCompaction_2_IT and ExternalCompaction_3_IT

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#2463]
**Test name(s)**
 - org.apache.accumulo.test.compaction.ExternalCompaction_2_IT.testDeleteTableCancelsExternalCompaction
 - org.apache.accumulo.test.compaction.ExternalCompaction_3_IT.testCoordinatorRestartsDuringCompaction

**Describe the failure observed**
These tests frequently time out, and never finish, even when given an excessive amount of time to finish. I have also seem them frequently take down my testing environment because they eventually cause Jenkins to be killed by the oom-killer. Even if they survive the oom-killer, when the test eventually times out, sometimes they leave lots of processes around, which causes further instability in subsequent tests.

**Testing Environment:**
```
Executing Maven:  -B -f /home/jenkins/jenkins-agent/workspace/Accumulo/main/pom.xml -V -e -ntp clean verify -Dstyle.color=always -Dfailsafe.skipAfterFailureCount=10 -Dfailsafe.rerunFailingTestsCount=1 -Dsurefire.forkCount=2 -Dtimeout.factor=3
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /usr/local/asfpackages/maven/apache-maven-3.8.4
Java version: 11.0.12, vendor: Oracle Corporation, runtime: /usr/local/asfpackages/java/oraclejdk-11.0.12
Default locale: en_US, platform encoding: ISO-8859-1
OS name: "linux", version: "4.15.0-162-generic", arch: "amd64", family: "unix"
```

**What have you tried already?**
I've already fixed #2455 and #2454 which have been observed with these tests. I looked at the code and saw that there's at least one issue with the Compactors trying indefinitely in an infinite retry loop to connect with the coordinator. If the coordinator dies, that could cause the Compactor to hang indefinitely, and the test to hang because of it. If the coordinator just isn't up yet, the compactor's constant retrying might cause a problem with CPU load, preventing things from working well (although that's probably a stretch). I looked at the code in these tests and saw that they were doing something unique for starting/stopping processes that's different from how other services are managed by MiniAccumuloCluster. So, there could be a problem there. At the very least, the new server types should be known to Mini's ServerType enum.

**Additional context**
Most recently, I saw these fail on ASF's Jenkins: https://ci-builds.apache.org/job/Accumulo/job/main/267/

**Comment by ctubbsii** [comment]
Saw this again today. It died after this output:

<details>
<summary>Click to expand</summary>

```
[ERROR] Tests run: 5, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 1,287.943 s <<< FAILURE! - in org.apache.accumulo.test.compaction.ExternalCompaction_3_IT
[ERROR] org.apache.accumulo.test.compaction.ExternalCompaction_3_IT.testCoordinatorRestartsDuringCompaction  Time elapsed: 600.009 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 600 seconds
	at java.base@11.0.14/java.lang.Thread.sleep(Native Method)
	at app//org.apache.accumulo.fate.util.UtilWaitThread.sleep(UtilWaitThread.java:33)
	at app//org.apache.accumulo.test.compaction.ExternalCompaction_3_IT.testCoordinatorRestartsDuringCompaction(ExternalCompaction_3_IT.java:178)
	at java.base@11.0.14/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.14/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.14/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.14/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base@11.0.14/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.14/java.lang.Thread.run(Thread.java:829)

[ERROR] org.apache.accumulo.test.compaction.ExternalCompaction_3_IT.testCoordinatorRestartsDuringCompaction  Time elapsed: 600.009 s  <<< ERROR!
java.lang.Exception: Appears to be stuck in thread Time-limited test-SendThread(localhost:40337)
	at java.base@11.0.14/sun.nio.ch.EPoll.wait(Native Method)
	at java.base@11.0.14/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:120)
	at java.base@11.0.14/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
	at java.base@11.0.14/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136)
	at app//org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:347)
	at app//org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)

[ERROR] org.apache.accumulo.test.compaction.ExternalCompaction_3_IT.testCoordinatorRestartsDuringCompaction  Time elapsed: 600.002 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 600 seconds
	at java.base@11.0.14/java.lang.Thread.sleep(Native Method)
	at app//org.apache.accumulo.fate.zookeeper.ZooCache$ZooRunnable.retry(ZooCache.java:299)
	at app//org.apache.accumulo.fate.zookeeper.ZooCache.getChildren(ZooCache.java:360)
	at app//org.apache.accumulo.fate.zookeeper.ZooCache.getLockData(ZooCache.java:570)
	at app//org.apache.accumulo.core.clientImpl.ClientContext.getManagerLocations(ClientContext.java:421)
	at app//org.apache.accumulo.core.clientImpl.ClientContext.getManagerLocations(ClientContext.java:406)
	at app//org.apache.accumulo.core.clientImpl.ManagerClient.getConnection(ManagerClient.java:59)
	at app//org.apache.accumulo.core.clientImpl.ManagerClient.getConnectionWithRetry(ManagerClient.java:49)
	at app//org.apache.accumulo.core.clientImpl.TableOperationsImpl.waitForFateOperation(TableOperationsImpl.java:305)
	at app//org.apache.accumulo.core.clientImpl.TableOperationsImpl.doFateOperation(TableOperationsImpl.java:375)
	at app//org.apache.accumulo.core.clientImpl.TableOperationsImpl.doFateOperation(TableOperationsImpl.java:359)
	at app//org.apache.accumulo.core.clientImpl.TableOperationsImpl.doTableFateOperation(TableOperationsImpl.java:1700)
	at app//org.apache.accumulo.core.clientImpl.TableOperationsImpl.create(TableOperationsImpl.java:248)
	at app//org.apache.accumulo.test.compaction.ExternalCompactionTestUtils.createTable(ExternalCompactionTestUtils.java:144)
	at app//org.apache.accumulo.test.compaction.ExternalCompactionTestUtils.createTable(ExternalCompactionTestUtils.java:134)
	at app//org.apache.accumulo.test.compaction.ExternalCompaction_3_IT.testCoordinatorRestartsDuringCompaction(ExternalCompaction_3_IT.java:137)
	at java.base@11.0.14/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.14/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.14/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.14/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base@11.0.14/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.14/java.lang.Thread.run(Thread.java:829)

[INFO] Running org.apache.accumulo.test.compaction.ExternalCompaction_2_IT
```

</details>
[ExternalCompaction_2_and_3_failure_logs.tar.gz](https://github.com/apache/accumulo/files/8028586/ExternalCompaction_2_and_3_failure_logs.tar.gz)

**Comment by ctubbsii** [comment]
[failsafe-reports.tar.gz](https://github.com/apache/accumulo/files/8028599/failsafe-reports.tar.gz)

**Comment by milleruntime** [comment]
I also saw 2 and 3 timeout when running all the ITs in Github Actions in my fork. They passed when I ran them locally.

**Comment by ctubbsii** [comment]
It's not just timeouts. It's filling up memory and getting killed by my kernel's OOM killer. I think there's a more serious problem in the code, probably more than just reliability problems with the tests. I saw lots of errors in the logs that did not look expected errors from the test coverage... like missing root tablet file after compaction and other exceptions. I've attached the logs and the failsafe error reports and output.

**Comment by ctubbsii** [comment]
Since the changes in #2490 , I've seen two successful passes in Jenkins where `ExternalCompaction_2_IT` passes in 60 seconds and `ExternalCompaction_3_IT` passes in 90 seconds, no flakes. Two runs is not enough to prove increased stability, but it definitely adds confidence in the conclusion that it's more stable now.

**Comment by dlmarion** [comment]
Coincidentally, FateIT also passed in those two runs.

**Comment by ctubbsii** [comment]
> Coincidentally, FateIT also passed in those two runs.

True. However, it failed locally for me several times after this got merged. It's definitely unrelated. Can discuss on #2474
