### ISSUE TITLE
TableOfflineException for +rep

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2653]
**Describe the bug**
The Monitor is reporting a `TableOfflineException` shortly after starting a new cluster. I am not sure if this can be addressed or not. It might be OK to have it reported once.

<pre>
org.apache.accumulo.core.client.TableOfflineException: Table accumulo.replication (+rep) is offline
	at org.apache.accumulo.core.clientImpl.ClientContext.requireNotOffline(ClientContext.java:602)
	at org.apache.accumulo.core.clientImpl.ClientContext.createBatchScanner(ClientContext.java:611)
	at org.apache.accumulo.monitor.rest.replication.ReplicationResource.getReplicationInformation(ReplicationResource.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
</pre>

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1
 - OS: Ubuntu
 - Others: Uno cluster, JDK 11

**Comment by ctubbsii** [comment]
Does this only happen when you try to navigate to the replication page on the monitor? If so, that's expected. But, the replication resource rest endpoint could be smarter and check if the table is offline first.

If it's happening even when you don't navigate to that page, then it'd be surprising.

**Comment by ctubbsii** [comment]
I think this should be an easy fix. I know somebody who might be interested in fixing this. Are you interested in fixing this, @tchaie ?

**Comment by milleruntime** [comment]
> Does this only happen when you try to navigate to the replication page on the monitor? If so, that's expected. But, the replication resource rest endpoint could be smarter and check if the table is offline first.
> 
> If it's happening even when you don't navigate to that page, then it'd be surprising.

Yeah, I think it only happens when you navigate to the `Replication` page.

**Comment by tchaie** [comment]
> I think this should be an easy fix. I know somebody who might be interested in fixing this. Are you interested in fixing this, @tchaie ?

Sure, I will look into this. You can assign to me.

**Comment by ctubbsii** [comment]
@tchaie Cool. Let us know if you have any questions.
