### ISSUE TITLE
TProtocolException: Service name not found in message name: startScan

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2660]
I saw this Exception in the tserver when it started up. It is being logged as a WARN.
<pre>
2022-04-28T09:56:33,406 [rpc.CustomNonBlockingServer$CustomFrameBuffer] WARN : Exception while invoking!
org.apache.thrift.protocol.TProtocolException: Service name not found in message name: startScan.  Did you forget to use a TMultiplexProtocol in your client?
        at org.apache.thrift.TMultiplexedProcessor.process(TMultiplexedProcessor.java:116) ~[libthrift-0.15.0.jar:0.15.0]
        at org.apache.accumulo.server.rpc.TimedProcessor.process(TimedProcessor.java:54) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:524) ~[libthrift-0.15.0.jar:0.15.0]
        at org.apache.accumulo.server.rpc.CustomNonBlockingServer$CustomFrameBuffer.invoke(CustomNonBlockingServer.java:129) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.thrift.server.Invocation.run(Invocation.java:18) ~[libthrift-0.15.0.jar:0.15.0]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]

</pre>

**Comment by milleruntime** [comment]
Hmm looks like I was using an outdated version of `accumulo-testing`. After updating to the latest, it is not showing up now.
