### ISSUE TITLE
NPE in Fate command

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2736]
Running the `fate` command in the shell `fate print` with only one sub command will give:
<pre>
2022-05-26T09:32:06,812 [shell.Shell] DEBUG: java.lang.NullPointerException
java.lang.NullPointerException: null
	at org.apache.accumulo.shell.commands.FateCommand.printTx(FateCommand.java:223) ~[accumulo-shell-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.shell.commands.FateCommand.execute(FateCommand.java:178) ~[accumulo-shell-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.shell.Shell.execCommand(Shell.java:774) ~[accumulo-shell-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.shell.Shell.start(Shell.java:593) ~[accumulo-shell-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.shell.Shell.execute(Shell.java:524) ~[accumulo-shell-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.start.Main.lambda$execKeyword$0(Main.java:126) ~[accumulo-start-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
</pre>

It works if you put anything as the 3rd argument: `fate -print 1234`

**Comment by Manno15** [comment]
I believe in PR #2215, I did fix this. I did not realize it was something
that happened against main though.
