### ISSUE TITLE
Invalid Path in TabletGroupWatcher

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2763]
The deleteRows test in ShellServerIT is failing due to recent change #2750 
<pre>
2022-06-09T10:42:04,829 [manager.EventCoordinator] INFO : Merge state of 1k;row7;row5 set to MERGING
2022-06-09T10:42:04,829 [manager.Manager] DEBUG: Deleting tablets for 1k;row7;row5
2022-06-09T10:42:04,830 [manager.Manager] DEBUG: Found following tablet 1k<;row7
2022-06-09T10:42:04,830 [manager.Manager] DEBUG: Making file deletion entries for 1k;row7;row5
2022-06-09T10:42:04,831 [manager.Manager] DEBUG: Finished gathering information from 1 of 1 servers in 0.00 seconds
2022-06-09T10:42:04,833 [manager.Manager] ERROR: Unable merge metadata table records
org.apache.accumulo.core.client.AccumuloException: java.lang.IllegalArgumentException: Invalid path provided, no scheme in t-000008q
        at org.apache.accumulo.manager.TabletGroupWatcher.deleteTablets(TabletGroupWatcher.java:694) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.TabletGroupWatcher.updateMergeState(TabletGroupWatcher.java:594) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.TabletGroupWatcher.run(TabletGroupWatcher.java:341) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
Caused by: java.lang.IllegalArgumentException: Invalid path provided, no scheme in t-000008q
        at org.apache.accumulo.core.metadata.ValidationUtil.validate(ValidationUtil.java:47) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.metadata.ValidationUtil.validate(ValidationUtil.java:41) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.metadata.ServerAmpleImpl.createDeleteMutation(ServerAmpleImpl.java:208) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.metadata.ServerAmpleImpl.putGcFileAndDirCandidates(ServerAmpleImpl.java:136) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.TabletGroupWatcher.deleteTablets(TabletGroupWatcher.java:666) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        ... 2 more
</pre>

**Comment by milleruntime** [comment]
Other ITs related that are also failing: DeleteRowsSplitIT, DeleteRowsIT, and CloneTestIT
