### ISSUE TITLE
Broken or Flaky test: NamespacesIT (verifySystemPropertyInheritance,verifyIteratorInheritance)

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#2867]
**Test name(s)**
 - NamespacesIT.verifySystemPropertyInheritance
 - NamespacesIT.verifyIteratorInheritance

**Describe the failure observed**

It looks like these tests are failing after #2834 

<details>
  <summary>Test outputs</summary>

```
[ERROR] org.apache.accumulo.test.NamespacesIT.verifySystemPropertyInheritance  Time elapsed: 4.959 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:179)
	at org.apache.accumulo.test.NamespacesIT._verifySystemPropertyInheritance(NamespacesIT.java:845)
	at org.apache.accumulo.test.NamespacesIT.verifySystemPropertyInheritance(NamespacesIT.java:817)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$4(AssertTimeout.java:138)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

[ERROR] org.apache.accumulo.test.NamespacesIT.verifyIteratorInheritance  Time elapsed: 1.969 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:179)
	at org.apache.accumulo.test.NamespacesIT.verifyIteratorInheritance(NamespacesIT.java:353)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$4(AssertTimeout.java:138)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

**Testing Environment:**
 - First commit known to fail (or current commit): fb3aeb961393023d6a652d3f51be2e42ec2d1134
 - OS: Pop!_OS 22.04 LTS
 - Java: 11
 - 3.6.3

**What have you tried already?**
Rerunning the test results in the same result - the test fails every time.

**Comment by EdColeman** [comment]
Did you test with the changes in https://github.com/apache/accumulo/pull/2864 ?

**Comment by DomGarguilo** [comment]
> Did you test with the changes in #2864 ?

Not until just now - didn't see that. Looks like these tests pass with those changes, thanks.
