### ISSUE TITLE
Manager failed to startup due to FateMetrics NPE

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2968]
I have an Uno cluster with 2 tservers that I was using for RWalk testing. I went to restart the whole cluster and the Manager failed to start up due to a NullPointerException in FateMetrics:
<pre>
2022-09-27T09:09:51,263 [start.Main] ERROR: Thread 'manager' died.
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
        at org.apache.accumulo.fate.ReadOnlyStore$ReadOnlyRepoWrapper.<init>(ReadOnlyStore.java:75) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.fate.ReadOnlyStore.top(ReadOnlyStore.java:92) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.fate.AdminUtil.getTransactionStatus(AdminUtil.java:382) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.fate.AdminUtil.getTransactionStatus(AdminUtil.java:227) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.metrics.fate.FateMetricValues.getFromZooKeeper(FateMetricValues.java:116) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.metrics.fate.FateMetrics.update(FateMetrics.java:91) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.metrics.fate.FateMetrics.registerMetrics(FateMetrics.java:153) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.metrics.MetricsUtil.initializeProducers(MetricsUtil.java:122) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.metrics.ManagerMetrics.init(ManagerMetrics.java:41) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.Manager.run(Manager.java:1053) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
</pre>

**Comment by DomGarguilo** [comment]
Are you able to reproduce this exception or did it just happen once?

**Comment by milleruntime** [comment]
> Are you able to reproduce this exception or did it just happen once?

Well the exception prevented the Manger from starting up but I think it requires ZK to be in a certain state to reproduce. There isn't much logged in the code so I am not exactly sure of what needs to happen. From the state of my test cluster and looking at the code, it seemed that their was a Fate TX in ZK without a `top`. The ZooStore method that gets the `top` transaction for Fate, allows for returning of null but the way we are wrapping ZooStore in this situation, it doesn't work. I open a fix to revert this change in https://github.com/apache/accumulo/pull/2971

**Comment by milleruntime** [comment]
@EdColeman I saw the same NPE trying to call `accumulo admin fate --summary`.
<pre>
02:58:35 {main} ~/workspace/uno/install/logs/accumulo$ accumulo admin fate --summary
2022-09-27T14:58:50,218 [conf.SiteConfiguration] INFO : Found Accumulo configuration on classpath at /home/mpmill4/workspace/uno/install/accumulo-2.1.0-SNAPSHOT/conf/accumulo.properties
2022-09-27T14:58:51,205 [metrics.MetricsUtil] INFO : Metric producer PropStoreMetrics initialize
DUDE get top for: tx_FATE[44e352e4e798b1eb] txName = TABLE_COMPACT
DUDE find top for: /accumulo/34a151cb-5f96-4e44-b0ab-265f4a660d9b/fate/tx_44e352e4e798b1eb
2022-09-27T14:58:51,346 [util.Admin] ERROR: null
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
	at org.apache.accumulo.fate.ReadOnlyStore$ReadOnlyRepoWrapper.<init>(ReadOnlyStore.java:75) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.fate.ReadOnlyStore.top(ReadOnlyStore.java:92) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.fate.AdminUtil.getTransactionStatus(AdminUtil.java:383) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.fate.AdminUtil.getStatus(AdminUtil.java:261) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.server.util.Admin.summarizeFateTx(Admin.java:863) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.server.util.Admin.executeFateOpsCommand(Admin.java:816) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.server.util.Admin.execute(Admin.java:396) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.start.Main.lambda$execKeyword$0(Main.java:122) ~[accumulo-start-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
</pre>

**Comment by milleruntime** [comment]
I think there might be a bug in ReadOnlyStore, in that it assumes a call to `top()` in it's underlying store (ZooStore) can't be null.
This can be seen in 1.10:
https://github.com/apache/accumulo/blob/5363d781d3c7f304765c1bdef93969e84f1d934f/fate/src/main/java/org/apache/accumulo/fate/ReadOnlyStore.java#L89

The ReadOnlyRepoWrapper constructor above requires that the Repo returned from the call to `top()` be non-null. But the impl code in ZooStore, clearly has code to handle the case when `top()` returns null:
https://github.com/apache/accumulo/blob/b11a03615d583a3f7cc6bebd975d98d3552b83cd/fate/src/main/java/org/apache/accumulo/fate/ZooStore.java#L257-L259


ReadOnlyStore was only used in limited places (deprecated FateAdmin and upgrade code) in previous versions so its likely this went unnoticed. For some reason, we started using ReadOnlyStore in other places in the Fate code and I am starting to think that this was a bad idea. I have one fix for this in https://github.com/apache/accumulo/pull/2971 but there are other places in the code that it is used that should be addressed.

**Comment by milleruntime** [comment]
> Are you able to reproduce this exception or did it just happen once?

I was able to reproduce this on a fresh cluster with the fix to Ample. All it takes is to have at least one Fate Tx with a null `top`, so either in the FAILED or SUCCESSFUL state. I had 4 RW Bulk jobs running on Uno with 2 tservers and then stopped and started servers.
<pre>
root@uno> fate -print
...
TABLE_BULK_IMPORT2 txid: 2e8275045e4e78bf  status: FAILED             locked: []              locking: []              op: null            created: 2022-09-27T20:30:25.603Z
TABLE_COMPACT   txid: 339ee3184c45d5ae  status: SUCCESSFUL         locked: []              locking: []              op: null            created: 2022-09-27T20:34:00.145Z
TABLE_BULK_IMPORT2 txid: 2ef40d89abbb6295  status: SUCCESSFUL         locked: []              locking: []              op: null            created: 2022-09-27T20:31:35.409Z
TABLE_BULK_IMPORT2 txid: 2e7b49accfe75012  status: SUBMITTED          locked: []              locking: [R:3]           op: PrepBulkImport  created: 2022-09-27T20:39:34.952Z
TABLE_BULK_IMPORT2 txid: 3aeed3ff61f05cc7  status: SUBMITTED          locked: []              locking: [R:1]           op: PrepBulkImport  created: 2022-09-27T20:39:52.12Z
TABLE_BULK_IMPORT2 txid: 0756c354d0015692  status: FAILED             locked: []              locking: []              op: null            created: 2022-09-27T20:31:36.41Z
</pre>

**Comment by EdColeman** [comment]
The switch to using the ReadOnlyRepo was to enforce places that were reading FATEs for status / metrics were not performing updates (and to enforce that) with the assumption (I guess wrong) that they were equivalent.  

Switching back may be okay, but the null returned by top in ZooStore will need to be correctly handled or we will have just moved the NPE to another location.

**Comment by milleruntime** [comment]
> The switch to using the ReadOnlyRepo was to enforce places that were reading FATEs for status / metrics were not performing updates.

As long as the type declared is `ReadOnlyTStore` and not the fully functioning `TStore`, then we are fine. 

> the null returned by top in ZooStore will need to be correctly handled or we will have just moved the NPE to another location.

This is true. It appears the code previously just printed the output of `top()` and didn't try to use it. I am not sure if this is still true.
