### ISSUE TITLE
FateServiceHandler process started before Fate is ready

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2980]
When the Manager starts up, one of the first things it does is start the FateServiceHandler process. This process will quickly try to access the `manager.fate` object to do the work it needs to do. This object will be null and can cause many NullPointerExceptions before the `Fate` object is constructed by the Manager. For locking purposes it is important that the thrift process be started first but their may be room for improvement so that the logs don't get spammed with these messages.

**Comment by ctubbsii** [comment]
Is log spam the only consequence to this?

**Comment by milleruntime** [comment]
> Is log spam the only consequence to this?

AFAIK yes. It is just odd and not very assuring to have Errors immediately after starting up a server process.

**Comment by ctubbsii** [comment]
I can take a look at this.

**Comment by milleruntime** [comment]
It looks to be a race condition too since these errors don't show up on a clean newly setup cluster. I think the happen when the Manager has other things to take care at startup, before creating the Fate object.

**Comment by ctubbsii** [comment]
I took a look at this, and the only thing I've seen is fate operations that would have triggered this. There shouldn't be any fate operations running prior to this being initialized. Do you have a stack trace? I have not seen this error. The manager also even has an explicit check and throws an exception if it detects that fate was started prior to upgrades being complete. Is this an upgrade error, or some other startup situation?

**Comment by milleruntime** [comment]
> There shouldn't be any fate operations running prior to this being initialized. Do you have a stack trace? 

That's what I thought as well. I will try to reproduce the error but its just each of the Thrift APIs in FateServiceHandler giving NPEs on the fate object.

**Comment by milleruntime** [comment]
Here is the first occurrence of the error at startup:
<pre>
2022-09-30T11:06:45,099 [manager.Manager] DEBUG: Acquired manager lock
2022-09-30T11:06:45,100 [manager.EventCoordinator] INFO : State changed from INITIAL to HAVE_LOCK
2022-09-30T11:06:45,102 [metrics.MetricsUtil] INFO : initializing metrics, enabled:false, class:
2022-09-30T11:06:45,105 [threads.ThreadPools] DEBUG: Creating ScheduledThreadPoolExecutor for replicationMetricsPoller with 1 threads
2022-09-30T11:06:45,106 [metrics.MetricsUtil] INFO : Metric producer ReplicationMetrics initialize
2022-09-30T11:06:45,106 [metrics.ManagerMetrics] INFO : Registered replication metrics module
2022-09-30T11:06:45,165 [accumulo.audit] INFO : operation: permitted; user: root; client: 127.0.0.1:50314; action: authenticate;
2022-09-30T11:06:45,166 [thrift.ProcessFunction] ERROR: Internal error processing waitForFateOperation
java.lang.NullPointerException: null
        at org.apache.accumulo.manager.FateServiceHandler.waitForFateOperation(FateServiceHandler.java:706) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.accumulo.core.trace.TraceUtil.lambda$wrapService$0(TraceUtil.java:206) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at com.sun.proxy.$Proxy36.waitForFateOperation(Unknown Source) ~[?:?]
        at org.apache.accumulo.core.manager.thrift.FateService$Processor$waitForFateOperation.getResult(FateService.java:560) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.manager.thrift.FateService$Processor$waitForFateOperation.getResult(FateService.java:539) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) ~[libthrift-0.16.0.jar:0.16.0]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) ~[libthrift-0.16.0.jar:0.16.0]
        at org.apache.thrift.TMultiplexedProcessor.process(TMultiplexedProcessor.java:138) ~[libthrift-0.16.0.jar:0.16.0]
        at org.apache.accumulo.server.rpc.TimedProcessor.process(TimedProcessor.java:54) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:524) ~[libthrift-0.16.0.jar:0.16.0]
        at org.apache.accumulo.server.rpc.CustomNonBlockingServer$CustomFrameBuffer.invoke(CustomNonBlockingServer.java:129) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.thrift.server.Invocation.run(Invocation.java:18) ~[libthrift-0.16.0.jar:0.16.0]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
</pre>

**Comment by ctubbsii** [comment]
> Here is the first occurrence of the error at startup:

Was there anything special about this startup occurrence? Was it an upgrade or a fresh install? Was it a single node, or a cluster? I'm just not sure what circumstances can cause this.
