### ISSUE TITLE
SortedLogRecoveryTest failures

### ISSUE THREAD

**Issue by jmark99** [apache/accumulo#3017]
**Describe the bug**
While attempting to run the Sunny profile,  the SortedLogRecoveryTests are failing. These tests are failing on my local development envrionment and on the Apache Jenkins server, but are passing on a Terraform created cluster that I had created.

The error first appears after commit b14df03bd7eee697fa9002832f03c2aaa7442695 that was added September 29th.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Running against the main branch of Accumulo repository.
 - OS:  Ubuntu 21.10

**To Reproduce**

Run the following test:

`
mvn clean -DfailIfNoTests=false -Dtest=org.apache.accumulo.tserver.log.SortedLogRecoveryTest test -am -pl server/tserver
`

**Expected behavior**
All tests should pass.

The stacktrace is listed below:
`
[ERROR] Errors: 
[ERROR]   SortedLogRecoveryTest.testSkipSuccessfulCompaction:392->recover:162->recover:203 » IllegalState First log entry is not OPEN /home/user/dev/accumulo/server/tserver/target/junit12172321873108158988/testSkipSuccessfulCompaction/testlog

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.474 s <<< FAILURE! - in org.apache.accumulo.tserver.log.SortedLogRecoveryTest
[ERROR] org.apache.accumulo.tserver.log.SortedLogRecoveryTest.testSkipSuccessfulCompaction  Time elapsed: 0.888 s  <<< ERROR!
java.lang.IllegalStateException: First log entry is not OPEN /home/user/dev/accumulo/server/tserver/target/junit12172321873108158988/testSkipSuccessfulCompaction/testlog
        at org.apache.accumulo.tserver.log.RecoveryLogsIterator.validateFirstKey(RecoveryLogsIterator.java:174)             
        at org.apache.accumulo.tserver.log.RecoveryLogsIterator.<init>(RecoveryLogsIterator.java:85)                    
        at org.apache.accumulo.tserver.log.SortedLogRecovery.findMaxTabletId(SortedLogRecovery.java:107)             
        at org.apache.accumulo.tserver.log.SortedLogRecovery.findLogsThatDefineTablet(SortedLogRecovery.java:147)    
        at org.apache.accumulo.tserver.log.SortedLogRecovery.recover(SortedLogRecovery.java:291)                    
        at org.apache.accumulo.tserver.log.SortedLogRecoveryTest.recover(SortedLogRecoveryTest.java:203)                     
        at org.apache.accumulo.tserver.log.SortedLogRecoveryTest.recover(SortedLogRecoveryTest.java:162)                            
        at org.apache.accumulo.tserver.log.SortedLogRecoveryTest.testSkipSuccessfulCompaction(SortedLogRecoveryTest.java:392)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                           
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)          
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
       at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.lambda$execute$1(JUnitPlatformProvider.java:234)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:228)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:131)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   SortedLogRecoveryTest.testSkipSuccessfulCompaction:392->recover:162->recover:203 » IllegalState First log entry is not OPEN /home/user/dev/accumulo/server/tserver/target/
junit12172321873108158988/testSkipSuccessfulCompaction/testlog
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
`

**Comment by dlmarion** [comment]
@jmark99 - I can't get this to fail on my local machine, but I was wondering if you could try the following. Change SortedLogRecoverTest.testSkipSuccessfulCompaction lin 392 from:
```
    List<Mutation> mutations = recover(logs, extent);
```
to
```
    List<Mutation> mutations = recover(logs, extent, entries.size());
```

**Comment by dlmarion** [comment]
Talked with Mark via Slack, putting my notes here for others:

```
So, that's interesting. Here was my thought:

1. SortedLogRecoveryTest.bufferSize = 5 (line 83)
2. SortedLogRecoveryTest.testSkipSuccessfulCompaction adds 6 KeyValue objects to the entries map (line 384)
3. SortedLogRecoveryTest.testSkipSuccessfulCompaction calls recover(Map, KeyExtent) line 392, which uses the default buffersize (5)
4. SortedLogRecoveryTest.recover iterates over the input Map and calls LogServer.writeBuffer() using the input bufferSize (5)
5. LogSorter.writeBuffer converts the input buffer into a SortedMap (TreeMap) of Keys (line 260), then writes the map to the WAL (line 279)

There are a couple of places here (4, 5) where maybe the sort order is wrong on your machine for some unknown reason. Given that increasing the buffer size to 6 allows the test to pass, then that points to the issue being at step 4

I would be curious if you can dump the contents of buffer (SortedLogRecoveryTest line 186) before the call to logSorter.writeBuffer (lines 191 and 195) when using the default bufferSize.

If the OPEN is not in the first buffer, then that's the issue

If the OPEN is in the first buffer, then the issue must be the sorting at step 5
```

**Comment by jmark99** [comment]
A fix was found after adding some extensive logging. It was assumed the  `getFiles` method within RecoveryLogsIterator the list of  logFiles lexicographical order by filename. Therefore, the `validateFirstKey` method retrieved the first LogFile and checked to see if it was in the proper format. On my Ubuntu system and presumably the Apache Jenkins server, the files are not returned in that order. Therefore, `validateFirstKey` would fail when checking the first key of the file it selected because it was not, in fact' the actual first key. 

Updating `getFiles` to return the logFiles in sorted order resolves the issue. See #3021 for the suggested fix.

The issue was introduced by the following change within RecoveryLogsIterator. The `logFiles.get(0)' call caused the issue for my development environment as the logFiles were not in the assumed order.

<pre>
private void validateFirstKey(ServerContext context, CryptoService cs, FileSystem fs,
      Path fullLogPath) {
      List<Path> logFiles, Path fullLogPath) throws IOException {
    try (var scanner =
    try (FileSKVIterator fileIter = FileOperations.getInstance().newReaderBuilder()
        RFile.newScanner().from(logFiles.stream().map(Path::toString).toArray(String[]::new))
        .forFile(logFiles.get(0).toString(), fs, fs.getConf(), cs)
            .withFileSystem(fs).withTableProperties(context.getConfiguration()).build()) {
        .withTableConfiguration(context.getConfiguration()).seekToBeginning().build()) {
      Iterator<Entry<Key,Value>> iterator = scanner.iterator();
      Iterator<Entry<Key,Value>> iterator = new IteratorAdapter(fileIter);
</pre>
