### ISSUE TITLE
External Compaction cancellation due to tablet split is very verbose

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3023]
External compactions are cancelled [here](https://github.com/apache/accumulo/blob/main/server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java#L218) when a Tablet is split or merged. Calling JOB_HOLDER.cancel() in this case creates a lot of logging which ends up in the Monitor. This doesn't seem to be an exceptional case here, we might want to look at tuning the logging in this case and other cases where JOB_HOLDER.cancel is called.

Here's what the log looked like:

```
2022-10-14T15:00:07,822 [compaction.FileCompactor] ERROR: Interrupted while waiting for data to be acknowledged by pipeline
java.io.InterruptedIOException: Interrupted while waiting for data to be acknowledged by pipeline
        at org.apache.hadoop.hdfs.DataStreamer.waitForAckedSeqno(DataStreamer.java:937) ~[hadoop-client-api-3.3.4.jar:?]
        at org.apache.hadoop.hdfs.DFSOutputStream.flushInternal(DFSOutputStream.java:778) ~[hadoop-client-api-3.3.4.jar:?]
        at org.apache.hadoop.hdfs.DFSOutputStream.closeImpl(DFSOutputStream.java:888) ~[hadoop-client-api-3.3.4.jar:?]
        at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:847) ~[hadoop-client-api-3.3.4.jar:?]
        at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77) ~[hadoop-client-api-3.3.4.jar:?]
        at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106) ~[hadoop-client-api-3.3.4.jar:?]
        at org.apache.accumulo.core.file.streams.RateLimitedOutputStream.close(RateLimitedOutputStream.java:54) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.file.rfile.bcfile.BCFile$Writer.close(BCFile.java:368) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.file.rfile.RFile$Writer.close(RFile.java:635) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.compaction.FileCompactor.compactLocalityGroup(FileCompactor.java:393) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.compaction.FileCompactor.call(FileCompactor.java:234) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.compactor.Compactor.lambda$createCompactionJob$7(Compactor.java:569) ~[accumulo-compactor-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
2022-10-14T15:00:07,874 [server.GarbageCollectionLogger] DEBUG: gc G1 Young Generation=18.05(+0.08) secs G1 Old Generation=0.00(+0.00) secs freemem=81,075,656(-64,866,976) totalmem=268,435,456
2022-10-14T15:00:07,878 [compaction.FileCompactor] WARN : name=RFile.index
org.apache.accumulo.core.file.rfile.bcfile.MetaBlockAlreadyExists: name=RFile.index
        at org.apache.accumulo.core.file.rfile.bcfile.BCFile$Writer.prepareMetaBlock(BCFile.java:386) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.file.rfile.bcfile.BCFile$Writer.prepareMetaBlock(BCFile.java:410) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.file.rfile.RFile$Writer.close(RFile.java:606) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.compaction.FileCompactor.call(FileCompactor.java:275) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.compactor.Compactor.lambda$createCompactionJob$7(Compactor.java:569) ~[accumulo-compactor-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
2022-10-14T15:00:07,878 [compactor.Compactor] ERROR: Compaction failed
org.apache.accumulo.server.compaction.FileCompactor$CompactionCanceledException: null
        at org.apache.accumulo.server.compaction.FileCompactor.compactLocalityGroup(FileCompactor.java:401) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.compaction.FileCompactor.call(FileCompactor.java:234) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.compactor.Compactor.lambda$createCompactionJob$7(Compactor.java:569) ~[accumulo-compactor-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
2022-10-14T15:00:07,885 [compactor.Compactor] INFO : Cancelling compaction ECID:00c58155-52e5-4948-b2df-77c082cffd1d that no longer has a metadata entry at 1;1ccd3;199999999999999c
2022-10-14T15:00:07,885 [compactor.Compactor] WARN : Compaction thread was interrupted, sending CANCELLED state
```

And the section of the monitor showing logs:

![image](https://user-images.githubusercontent.com/567911/195882334-7654ba66-6cab-4965-af6f-8284e9afb674.png)

**Comment by DomGarguilo** [comment]
It looks like I may have encountered something similar while running continuous ingest on branch 2.1.0-rc0 with a 10 node cluster
![image](https://user-images.githubusercontent.com/47725857/196984711-18ec7c29-aaa7-49b5-b362-285a886c3f5a.png)

**Comment by cshannon** [comment]
I started looking into this and there are 3 places where the stack traces are showing up, two of them in `FileCompactor` when `FileSKVWriter` is closed and 1 in `Compactor`. 

In `Compactor`, I think we can definitely handle that by just catching the `CompactionCanceledException` and logging the message as a debug instead of error and full stack trace. We could log it as info but there's already info messages indicating the compaction is goign to be cancelled before cancel is called on the JOB_HOLDER. This also is in line with the existing behavior of CompactableImpl.  https://github.com/apache/accumulo/blob/d5a35f2f59bf6c35369f1032189812f98021e3d2/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java#L1292-L1293

For the other two cases where errors are logged it's a bit tricky. There's no guarantee that the errors causing the file writer to fail closing are related to compaction being cancelled and could be another serious issue. I do think that logging the entire stack trace is a bit verbose either way and at the very least maybe only log the error message and keep the stack trace at debug level.

I will submit a PR shortly with the proposed logging changes and then can discuss if the logging level changes makes sense or not.
