### ISSUE TITLE
Seeing "AccumuloException: Problem with metadata table" when repeatedly calling `listSplits()`

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#3333]
**Describe the bug**
I was running [a jshell script](https://gist.github.com/DomGarguilo/b4972ee7c917d5680501e63998abb7ba) that ingested some data into accumulo then cloned the table, set the split threshold of that table to `1M` and then repeatedly checked the splits in this loop:
```java
    int count = 0;
    while (count < 1200) {
        int splitCount = client.tableOperations().listSplits(clonedTableName).size();
        if (splitCount != previousSplitCount) {
            System.out.println("Split count: " + splitCount + " at " + (now - System.currentTimeMillis()));
            previousSplitCount = splitCount;
        }
        count++;
        Thread.sleep(100);
    }
```

<details><summary>Output of the script including the error</summary>
<p>

```
Created initial table
Writing 30000 rows and 1000 columns into table 'table'
..............................Ingested data into initial table
Cloned table created
Setting split threshold to 1M at 1682361297076
Split count: 1 at -27114
Split count: 2 at -57212
Split count: 3 at -57827
Split count: 4 at -87390
2023-04-24T14:36:24,839 [admin.TableOperations] INFO : org.apache.accumulo.core.client.AccumuloException: Problem with metadata table, it has a hole 2014 != 1676 ... retrying ...
org.apache.accumulo.core.client.AccumuloException: Problem with metadata table, it has a hole 2014 != 1676
	at org.apache.accumulo.core.metadata.TableMetadataServicer.validateEntries(TableMetadataServicer.java:136) ~[accumulo-core-2.1.0.jar:2.1.0]
	at org.apache.accumulo.core.metadata.TableMetadataServicer.getTabletLocations(TableMetadataServicer.java:106) ~[accumulo-core-2.1.0.jar:2.1.0]
	at org.apache.accumulo.core.clientImpl.TableOperationsImpl._listSplits(TableOperationsImpl.java:669) ~[accumulo-core-2.1.0.jar:2.1.0]
	at org.apache.accumulo.core.clientImpl.TableOperationsImpl.listSplits(TableOperationsImpl.java:658) ~[accumulo-core-2.1.0.jar:2.1.0]
	at REPL.$JShell$48.do_it$($JShell$48.java:19) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:209) ~[jdk.jshell:?]
	at jdk.jshell.execution.RemoteExecutionControl.invoke(RemoteExecutionControl.java:116) ~[jdk.jshell:?]
	at jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:119) ~[jdk.jshell:?]
	at jdk.jshell.execution.ExecutionControlForwarder.processCommand(ExecutionControlForwarder.java:144) ~[jdk.jshell:?]
	at jdk.jshell.execution.ExecutionControlForwarder.commandLoop(ExecutionControlForwarder.java:262) ~[jdk.jshell:?]
	at jdk.jshell.execution.Util.forwardExecutionControl(Util.java:76) ~[jdk.jshell:?]
	at jdk.jshell.execution.Util.forwardExecutionControlAndIO(Util.java:137) ~[jdk.jshell:?]
	at jdk.jshell.execution.RemoteExecutionControl.main(RemoteExecutionControl.java:70) ~[jdk.jshell:?]
Split count: 7 at -90759
2023-04-24T14:36:54,930 [admin.TableOperations] INFO : org.apache.accumulo.core.client.AccumuloException: Problem with metadata table, it has a hole 1845 != 1676 ... retrying ...
org.apache.accumulo.core.client.AccumuloException: Problem with metadata table, it has a hole 1845 != 1676
	at org.apache.accumulo.core.metadata.TableMetadataServicer.validateEntries(TableMetadataServicer.java:136) ~[accumulo-core-2.1.0.jar:2.1.0]
	at org.apache.accumulo.core.metadata.TableMetadataServicer.getTabletLocations(TableMetadataServicer.java:106) ~[accumulo-core-2.1.0.jar:2.1.0]
	at org.apache.accumulo.core.clientImpl.TableOperationsImpl._listSplits(TableOperationsImpl.java:669) ~[accumulo-core-2.1.0.jar:2.1.0]
	at org.apache.accumulo.core.clientImpl.TableOperationsImpl.listSplits(TableOperationsImpl.java:658) ~[accumulo-core-2.1.0.jar:2.1.0]
	at REPL.$JShell$48.do_it$($JShell$48.java:19) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:209) ~[jdk.jshell:?]
	at jdk.jshell.execution.RemoteExecutionControl.invoke(RemoteExecutionControl.java:116) ~[jdk.jshell:?]
	at jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:119) ~[jdk.jshell:?]
	at jdk.jshell.execution.ExecutionControlForwarder.processCommand(ExecutionControlForwarder.java:144) ~[jdk.jshell:?]
	at jdk.jshell.execution.ExecutionControlForwarder.commandLoop(ExecutionControlForwarder.java:262) ~[jdk.jshell:?]
	at jdk.jshell.execution.Util.forwardExecutionControl(Util.java:76) ~[jdk.jshell:?]
	at jdk.jshell.execution.Util.forwardExecutionControlAndIO(Util.java:137) ~[jdk.jshell:?]
	at jdk.jshell.execution.RemoteExecutionControl.main(RemoteExecutionControl.java:70) ~[jdk.jshell:?]
Split count: 11 at -120827

```

I also saw this exception occur once:

```
2023-04-24T15:57:09,512 [admin.TableOperations] INFO : org.apache.accumulo.core.client.AccumuloException: Problem with metadata table, first entry for table 7- 7;1339;117 - has non null prev end row ... retrying ...
org.apache.accumulo.core.client.AccumuloException: Problem with metadata table, first entry for table 7- 7;1339;117 - has non null prev end row
	at org.apache.accumulo.core.metadata.TableMetadataServicer.validateEntries(TableMetadataServicer.java:119) ~[accumulo-core-2.1.0.jar:2.1.0]
	at org.apache.accumulo.core.metadata.TableMetadataServicer.getTabletLocations(TableMetadataServicer.java:106) ~[accumulo-core-2.1.0.jar:2.1.0]
	at org.apache.accumulo.core.clientImpl.TableOperationsImpl._listSplits(TableOperationsImpl.java:669) ~[accumulo-core-2.1.0.jar:2.1.0]
	at org.apache.accumulo.core.clientImpl.TableOperationsImpl.listSplits(TableOperationsImpl.java:658) ~[accumulo-core-2.1.0.jar:2.1.0]
	at REPL.$JShell$48.do_it$($JShell$48.java:18) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:209) ~[jdk.jshell:?]
	at jdk.jshell.execution.RemoteExecutionControl.invoke(RemoteExecutionControl.java:116) ~[jdk.jshell:?]
	at jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:119) ~[jdk.jshell:?]
	at jdk.jshell.execution.ExecutionControlForwarder.processCommand(ExecutionControlForwarder.java:144) ~[jdk.jshell:?]
	at jdk.jshell.execution.ExecutionControlForwarder.commandLoop(ExecutionControlForwarder.java:262) ~[jdk.jshell:?]
	at jdk.jshell.execution.Util.forwardExecutionControl(Util.java:76) ~[jdk.jshell:?]
	at jdk.jshell.execution.Util.forwardExecutionControlAndIO(Util.java:137) ~[jdk.jshell:?]
	at jdk.jshell.execution.RemoteExecutionControl.main(RemoteExecutionControl.java:70) ~[jdk.jshell:?]

```

</p>
</details> 

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.0
 - OS: Pop!_OS 22.04 LTS

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. [download the jshell script](https://gist.github.com/DomGarguilo/b4972ee7c917d5680501e63998abb7ba)
2. start an accumulo instance (I used uno)
3. run the script: `accumulo jshell myScript.jsh`

**Comment by keith-turner** [comment]
I looked into this and opened a PR.  We could have probably just changed the logging from info to debug, but looking at the code I thought switching to use Ample had a few advantages.  The Ample code will not retry on really unexpected cases and when there is a concurrent split it backtracks to the last good tablet instead of rescanning the entire table.  The Ample code is shorter also.  We may be able to have a follow on issue to replace all calls MetadataServicer.getTabletLocations with Ample

**Comment by DomGarguilo** [comment]
@keith-turner, were you able to reproduce this? If so, which branch were you running on.
