### ISSUE TITLE
Flaky test: GarbageCollectorTrashEnabledCustomPolicyIT

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3487]
**Test name(s)**
 - GarbageCollectorTrashEnabledCustomPolicyIT.testTrashHadoopEnabledAccumuloEnabled

**Describe the failure observed**
```
[ERROR] org.apache.accumulo.test.functional.GarbageCollectorTrashEnabledCustomPolicyIT.testTrashHadoopEnabledAccumuloEnabled  Time elapsed: 18.113 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
	at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
	at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:31)
	at org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:228)
	at org.apache.accumulo.test.functional.GarbageCollectorTrashEnabledCustomPolicyIT.testTrashHadoopEnabledAccumuloEnabled(GarbageCollectorTrashEnabledCustomPolicyIT.java:96)
```

**Testing Environment:**
 - Version of this project: 2.1.1-RC1

**What have you tried already?**
N/A

**Additional context**
This test passes on other machines, so it's likely a timing issue. Looking at the test, `flush(tableName)` is called two lines before.

https://github.com/apache/accumulo/blob/7c5bbc6e90af44b959e8c6f0a2807a7dda4b61ce/test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorTrashEnabledCustomPolicyIT.java#L94-L96

This version of `flush` does not wait for the flush to complete. Instead, I think that `flush(tableName, null, null, true)` should replace all occurrences of `flush(tableName)` in the new GarbageCollector tests.

**Comment by ctubbsii** [comment]
I'd really love to change the behavior of flush to be synchronous, and have a separate flushAsync method.
