### ISSUE TITLE
Error thrown when switching from SAFE_MODE to NORMAL manager state

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#3716]
**Describe the bug**
While testing the changes for #3711 I was using `accumulo org.apache.accumulo.manager.state.SetGoalState`. Every time I switch the goal state from `SAFE_MODE` to `NORMAL` the following shows up in the logs:
```
2023-08-22T13:30:51,611 [manager.EventCoordinator] INFO : State changed from NORMAL to SAFE_MODE
2023-08-22T13:30:51,744 [manager.EventCoordinator] INFO : [Normal Tablets]: 1 tablets are UNASSIGNED
2023-08-22T13:30:51,744 [manager.EventCoordinator] INFO : [Metadata Tablets]: 2 tablets are HOSTED
2023-08-22T13:31:11,805 [manager.EventCoordinator] INFO : State changed from SAFE_MODE to NORMAL
2023-08-22T13:31:11,805 [manager.Manager] ERROR: Error occurred reading / switching manager goal state. Will continue with attempt to update status
java.lang.IllegalStateException: Access to Fate should not have been initialized prior to the Manager finishing upgrades. Please save all logs and file a bug.
	at org.apache.accumulo.manager.Manager.setManagerState(Manager.java:310) ~[accumulo-manager-2.1.2-SNAPSHOT.jar:2.1.2-SNAPSHOT]
	at org.apache.accumulo.manager.Manager$StatusThread.run(Manager.java:767) ~[accumulo-manager-2.1.2-SNAPSHOT.jar:2.1.2-SNAPSHOT]
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.2-SNAPSHOT.jar:2.1.2-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

The goal state always seems to switch correctly. I'm not too sure whats going on here or if this is truly a bug but wanted to double check.

The error is thrown here:
https://github.com/apache/accumulo/blob/fcaf4d35a67089b60b87f19f7f1a32e1d74a75df/server/manager/src/main/java/org/apache/accumulo/manager/Manager.java#L308-L315

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.3-SNAPSHOT (fcaf4d35a67089b60b87f19f7f1a32e1d74a75df)

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. setup accumulo with uno
2. set the goal state to safe mode: `accumulo org.apache.accumulo.manager.state.SetGoalState SAFE_MODE`
3. set the goal state back to normal: `accumulo org.apache.accumulo.manager.state.SetGoalState NORMAL`

**Comment by ctubbsii** [comment]
We attempted to fix a similar issue in #2990. I think maybe we skipped a spot. The code shouldn't be checking fateRef directly, but rather through the fate() method created in #2990, which blocks for a small period of time while we wait for the fate object to be ready. I'll open a PR for this.
