### ISSUE TITLE
Broken or Flaky test: ManagerRepairsDualAssignmentIT

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#3762]
**ManagerRepairsDualAssignmentIT**

**Describe the failure observed**

The ManagerRepairsDualAssignmentIT seems to be failing with some regularity.  The issue was first seen on a Jenkins run and has failed about 50% of the time running locally.

```
[ERROR] org.apache.accumulo.test.ManagerRepairsDualAssignmentIT.test -- Time elapsed: 15.79 s <<< ERROR!
java.lang.RuntimeException: java.io.EOFException: Socket is closed by peer.
        at org.apache.accumulo.core.clientImpl.TabletServerBatchReaderIterator.hasNext(TabletServerBatchReaderIterator.java:198)
        at org.apache.accumulo.server.manager.state.MetaDataTableScanner.hasNext(MetaDataTableScanner.java:125)
        at org.apache.accumulo.test.ManagerRepairsDualAssignmentIT.test(ManagerRepairsDualAssignmentIT.java:114)

```

<details>
  <summary>Full trace</summary>

```[ERROR] org.apache.accumulo.test.ManagerRepairsDualAssignmentIT.test -- Time elapsed: 15.79 s <<< ERROR!
java.lang.RuntimeException: java.io.EOFException: Socket is closed by peer.
        at org.apache.accumulo.core.clientImpl.TabletServerBatchReaderIterator.hasNext(TabletServerBatchReaderIterator.java:198)
        at org.apache.accumulo.server.manager.state.MetaDataTableScanner.hasNext(MetaDataTableScanner.java:125)
        at org.apache.accumulo.test.ManagerRepairsDualAssignmentIT.test(ManagerRepairsDualAssignmentIT.java:114)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.api.AssertTimeoutPreemptively.lambda$submitTask$3(AssertTimeoutPreemptively.java:95)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.EOFException: Socket is closed by peer.
        at org.apache.accumulo.core.clientImpl.TabletServerBatchReaderIterator.doLookup(TabletServerBatchReaderIterator.java:918)
        at org.apache.accumulo.core.clientImpl.TabletServerBatchReaderIterator$QueryTask.run(TabletServerBatchReaderIterator.java:402)
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

```

</details>

**Testing Environment:**
 - 2.1.3-SNAPSHOT (cac52251fd) - but started a few commits earlier.

**Comment by EdColeman** [comment]
When the test fails, it seems to be an issue with understanding that the server died (well, killed intentionally by the test in this case)

The manager sees that it cannot connect and the connection is refused.
```
2023-09-21T14:47:50,210 [manager.Manager] TRACE: Got status from ip-xx-xx-xx-xx:46553[1000082d6390005] in 4 ms
2023-09-21T14:47:50,208 [manager.Manager] DEBUG: unable to get tablet server status ip-xx-xx-xx-xx:44915[1000082d6390004]
org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
```
but it still tries to get tablet info from the "dead" server:
```2023-09-21T14:47:50,312 [manager.Manager] ERROR: Error processing table state for store Normal Tablets
java.lang.RuntimeException: java.io.EOFException: Socket is closed by peer.
        at org.apache.accumulo.core.clientImpl.TabletServerBatchReaderIterator.hasNext(TabletServerBatchReaderIterator.java:198) ~[accumulo-core-2.1.3-SNAPSHOT.jar:2.1.3-SNAPSHOT]
        at org.apache.accumulo.server.manager.state.MetaDataTableScanner.hasNext(MetaDataTableScanner.java:125) ~[accumulo-server-base-2.1.3-SNAPSHOT.jar:2.1.3-SNAPSHOT]
        at org.apache.accumulo.manager.TabletGroupWatcher.run(TabletGroupWatcher.java:219) [accumulo-manager-2.1.3-SNAPSHOT.jar:2.1.3-SNAPSHOT]

...

2023-09-21T14:47:50,312 [manager.Manager] ERROR: Error processing table state for store Metadata Tablets
java.lang.RuntimeException: java.io.EOFException: Socket is closed by peer.
        at org.apache.accumulo.core.clientImpl.TabletServerBatchReaderIterator.hasNext(TabletServerBatchReaderIterator.java:198) ~[accumulo-core-2.1.3-SNAPSHOT.jar:2.1.3-SNAPSHOT]
        at org.apache.accumulo.server.manager.state.MetaDataTableScanner.hasNext(MetaDataTableScanner.java:125) ~[accumulo-server-base-2.1.3-SNAPSHOT.jar:2.1.3-SNAPSHOT]
        at org.apache.accumulo.manager.TabletGroupWatcher.run(TabletGroupWatcher.java:219) [accumulo-manager-2.1.3-SNAPSHOT.jar:2.1.3-SNAPSHOT]

```

When the test passes:

It recognizes the "dead" server and then starts the recovery / reassignment sequences as expected.

```
2023-09-21T14:38:46,312 [manager.Manager] DEBUG: Finished gathering information from 1 of 2 servers in 0.01 seconds
2023-09-21T14:38:46,312 [manager.Manager] DEBUG: not balancing because the balance information is out-of-date [ip-xx-xx-xx-xx:39049[100007a633d0005]]
2023-09-21T14:38:51,524 [manager.Manager] WARN : Lost servers [ip-xx-xx-xx-xx:39049[100007a633d0005]]
2023-09-21T14:38:51,524 [manager.EventCoordinator] INFO : There are now 1 tablet servers

```
There does not seem to be a correlation between the tablets that get assigned to the server that is killed.  In one case, the root tablet was there, but on the next run / failure the root was assigned to the server that keeps running.  Seems similar to the metadata assignments - I don't see a pattern between tablet assignments on failures or successes.

**Comment by ctubbsii** [comment]
Upon further investigation, it looks like this was specifically caused by the attempt to mitigate the errors from Thrift's max message size issue, which would retry indefinitely. That mitigation was added in b1b2557f949e9212a1b1ca9b65f2d66c01a69edb for #3737 to address #3731.

However, in this case, we actually do want to retry, because it's a transient failure, not a fatal one.

The problem is that we cannot distinguish between the transient failures of the socket being closed because a server died, and the non-transient failures of hitting the Thrift max message size.

Given that Accumulo is intended to be robust against transient network outages, and the Thrift max message size is mitigated with configuration to increase the size of the max message, I'm thinking we're going to need to revert the categorization of EOFException as being a fatal error that was done in b1b2557f949e9212a1b1ca9b65f2d66c01a69edb, because it's better that we not fail to resume a scan, just because of a transient network failure. @dlmarion , what do you think?

Also, related: I'd like @keith-turner 's opinion on whether we should even be using the framed transport, which creates all these headaches for us in the first place. I'm also curious if @dlmarion or @keith-turner know whether the framed transport should be used for client sockets at all. From the javadoc on TTransportFactory, it reads as if the wrapping is really expected to only be used in servers. However, we use it to wrap client transports with it in our ThriftUtil class, and I'm not sure that's the right thing. I'm not even sure why we're using the framed transport at all.

**Comment by dlmarion** [comment]
Good find @ctubbsii . Regarding reverting the EOFException changes, that certainly seems like a targeted solution here. I don't believe that removing that will have any negative effects on the other things done in #3737. Regarding the framed transport question, I'm not sure what capability it's providing to us.

**Comment by keith-turner** [comment]
> Also, related: I'd like @keith-turner 's opinion on whether we should even be using the framed transport, which creates all these headaches for us in the first place.


Accumulo uses THsHaServer as its default thrift server and it [requires this](https://github.com/apache/thrift/blob/bc9c04d8049d7d5f5cf4e63a25226c1fb8c930bf/lib/java/src/main/java/org/apache/thrift/server/THsHaServer.java#L31)

**Comment by ctubbsii** [comment]
> > Also, related: I'd like @keith-turner 's opinion on whether we should even be using the framed transport, which creates all these headaches for us in the first place.
> 
> Accumulo uses THsHaServer as its default thrift server and it [requires this](https://github.com/apache/thrift/blob/bc9c04d8049d7d5f5cf4e63a25226c1fb8c930bf/lib/java/src/main/java/org/apache/thrift/server/THsHaServer.java#L31)

But it shouldn't be required for client sockets, right?

**Comment by ctubbsii** [comment]
Since we're only using the framed transport because we have to, I'm wondering if we should just always set the max message size to the maximum value possible. If we're only using this transport because we have to for the server type, and not because actually want to make use of its features, like size limitations, then it'd probably be easier if we just removed the configuration option, and always set the max size possible.

**Comment by ctubbsii** [comment]
> Since we're only using the framed transport because we have to, ...

I created #3791 as a new issue for this.
