### ISSUE TITLE
Compactor fails to start

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3782]
Saw the following while doing testing on the elasticity branch and it caused a compactor to exit. I suspect the compactor started before the manager and there was no address for the manager in ZK yet, however not sure that is the actual cause.  Also not sure if this a bug in main or 2.1

```
 2023-09-27T11:44:42,835 [compactor.Compactor] ERROR: Unhandled error occurred in Compactor
java.lang.NullPointerException: null
        at org.apache.accumulo.core.util.AddressUtil.parseAddress(AddressUtil.java:36) ~[classes/:?]
        at org.apache.accumulo.core.lock.ServiceLockData.getAddress(ServiceLockData.java:160) ~[classes/:?]
        at org.apache.accumulo.core.util.compaction.ExternalCompactionUtil.findCompactionCoordinator(ExternalCompactionUtil.java:111) ~[classes/:?]
        at org.apache.accumulo.compactor.Compactor.getCoordinatorClient(Compactor.java:462) ~[classes/:?]
        at org.apache.accumulo.compactor.Compactor.lambda$getNextJob$3(Compactor.java:436) ~[classes/:?]
        at org.apache.accumulo.server.compaction.RetryableThriftCall.run(RetryableThriftCall.java:100) ~[classes/:?]
        at org.apache.accumulo.compactor.Compactor.getNextJob(Compactor.java:452) ~[classes/:?]
        at org.apache.accumulo.compactor.Compactor.run(Compactor.java:627) [classes/:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) [classes/:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by ctubbsii** [comment]
This bug seems to have been introduced in #3189, which was added in 3.0.0. So, it doesn't affect 2.1 at all.
`ServiceLockData.getAddress()` calls `ServiceLockData.getAddressString()`, which can be null.

**Comment by ctubbsii** [comment]
Most of my patch is just handling the null case properly. If the null case is happening when it's not supposed to (which I don't think is the case), my patch doesn't fix it, but that situation should be more obvious after my patch is applied if we continue to see problems.

**Comment by keith-turner** [comment]
Looking through the code I think the changes in #3788 will cause [this code](https://github.com/apache/accumulo/blob/8cd7c59412887b4d06b40610e51412293fca870d/server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java#L463) to now throw TTransportException which will cause other code to retry.  So the compactor should no longer die and should retry until there is a service address in ZK.
