### ISSUE TITLE
Broken or Flaky test: CompletableFutureUtilTest.testIterateUntil

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#3790]
**Test name(s)**
 - org.apache.accumulo.core.util.CompletableFutureUtilTest.testIterateUntil

**Describe the failure observed**

I saw a StackOverflowError error while running the full build to test #3787, but I can't reproduce it and it seems completely unrelated. It does seem worth looking into, if this can happen under some circumstances, though.

I saw the following stack trace pattern kept repeating until the test died:

```
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at org.apache.accumulo.core.util.CompletableFutureUtil$1.apply(CompletableFutureUtil.java:71)
	at org.apache.accumulo.core.util.CompletableFutureUtil$1.apply(CompletableFutureUtil.java:65)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
```

**Testing Environment:**
 - Version of this project: 2.1.3-SNAPSHOT
 - First commit known to fail (or current commit): Seen with #3787 (committed as 84d034589d4454cadcf72c0f668393d342f64325), which was based on 2.1.3-SNAPSHOT at commit af47a2f0bd6e231ae898ef61c77d1157d4f1a94a, but seems unrelated
 - OS: Fedora 38 "linux", version: "6.5.5-200.fc38.x86_64", arch: "amd64", family: "unix"
 - Java: 11.0.20, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.20.0.8-1.fc38.x86_64
 - Maven: Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)

**What have you tried already?**
I reran the test several times, and could not reproduce the issue.

**Additional context**
N/A

**Comment by ctubbsii** [comment]
I saw this again in the main branch with 5488a7c74b8b1dc29df37be5dcaa7bace658ba10 in a Jenkins instance (I've only ever seen it on Jenkins). I can't seem to reproduce it manually when I run it directly.

**Comment by ctubbsii** [comment]
Haven't seen it in awhile.
