### ISSUE TITLE
Investigate what happens when importing a table from 2.1 to 3.1 

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3849]
The changes in #3761 changed how files were serialized in the metadata table.  If a table is exported from 2.1 it may have the old file serialization format.  If that table is imported into a 3.1 instance, what happens when it processes the old file serialization format?

**Comment by EdColeman** [comment]
I'll take a look.  I have a first pass at the upgrade sequence working, just need some polish before I submit a PR.

**Comment by EdColeman** [comment]
It fails.

```
2023-10-18T19:52:20,982 [fate.Fate] WARN : Failed to execute Repo FATE[4c0f82faa60423a2]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path 
```

<details>

  <summary>Full trace</summary>
  
2023-10-18T19:52:20,982 [fate.Fate] WARN : Failed to execute Repo FATE[4c0f82faa60423a2]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:?]
	at org.apache.accumulo.core.metadata.StoredTabletFile.deserialize(StoredTabletFile.java:187) ~[accumulo-core-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
	at org.apache.accumulo.core.metadata.StoredTabletFile.<init>(StoredTabletFile.java:63) ~[accumulo-core-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
	at org.apache.accumulo.core.metadata.StoredTabletFile.of(StoredTabletFile.java:160) ~[accumulo-core-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
	at org.apache.accumulo.manager.tableOps.tableImport.PopulateMetadataTable.call(PopulateMetadataTable.java:132) ~[accumulo-manager-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
	at org.apache.accumulo.manager.tableOps.tableImport.PopulateMetadataTable.call(PopulateMetadataTable.java:60) ~[accumulo-manager-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
	at org.apache.accumulo.manager.tableOps.TraceRepo.call(TraceRepo.java:60) ~[accumulo-manager-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
	at org.apache.accumulo.core.fate.Fate$TransactionRunner.run(Fate.java:100) ~[accumulo-core-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:?]
	... 16 more

</details>

**Comment by keith-turner** [comment]
> importtable fails.

We could actually have ITs excercise importing data from older versions.  Could export a table from an older version and save the data in test resources and import that data in an IT.

**Comment by cshannon** [comment]
One of the items on the list in https://github.com/apache/accumulo/issues/3766 was to test import with ranges so maybe we can test this as well with the old format once we decide the best way to handle the conversion.
