### ISSUE TITLE
Tablet.updateTabletDataFile failing

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3889]
A failure in `Tablet.updateTabletDataFile` is causing minor compactions to fail. Noticed this when running some of the failing ITs, in this case `RestartIT.killedTabletServer`. I have seen this fail for the root table as well, so it's not just user tables.
```
2023-10-24T20:18:48,816 [tablet.Tablet] ERROR: Failed to free tablet memory on 1<<
java.lang.IllegalStateException: null
        at org.apache.accumulo.tserver.tablet.TabletMemory.finalizeMinC(TabletMemory.java:116) ~[classes/:?]
        at org.apache.accumulo.tserver.tablet.Tablet.minorCompact(Tablet.java:390) [classes/:?]
        at org.apache.accumulo.tserver.tablet.MinorCompactionTask.run(MinorCompactionTask.java:114) [classes/:?]
        at org.apache.accumulo.tserver.tablet.Tablet.minorCompactNow(Tablet.java:528) [classes/:?]
        at org.apache.accumulo.tserver.AssignmentHandler.run(AssignmentHandler.java:178) [classes/:?]
        at org.apache.accumulo.tserver.ActiveAssignmentRunnable.run(ActiveAssignmentRunnable.java:63) [classes/:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) [classes/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) [classes/:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2023-10-24T20:18:48,825 [tablet.MinorCompactionTask] ERROR: Unknown error during minor compaction for extent: 1<<
java.lang.RuntimeException: Exception occurred during minor compaction on 1<<
        at org.apache.accumulo.tserver.tablet.Tablet.minorCompact(Tablet.java:386) ~[classes/:?]
        at org.apache.accumulo.tserver.tablet.MinorCompactionTask.run(MinorCompactionTask.java:114) [classes/:?]
        at org.apache.accumulo.tserver.tablet.Tablet.minorCompactNow(Tablet.java:528) [classes/:?]
        at org.apache.accumulo.tserver.AssignmentHandler.run(AssignmentHandler.java:178) [classes/:?]
        at org.apache.accumulo.tserver.ActiveAssignmentRunnable.run(ActiveAssignmentRunnable.java:63) [classes/:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) [classes/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) [classes/:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalStateException: Unable to write minor compaction.  1<< ip-1.2.3.4:42301[10001e1eecb001c] org.apache.accumulo.core.metadata.schema.MetadataTime@673b4b26
        at org.apache.accumulo.tserver.tablet.Tablet.updateTabletDataFile(Tablet.java:1356) ~[classes/:?]
        at org.apache.accumulo.tserver.tablet.Tablet.bringMinorCompactionOnline(Tablet.java:1483) ~[classes/:?]
        at org.apache.accumulo.tserver.tablet.Tablet.minorCompact(Tablet.java:373) ~[classes/:?]
        ... 9 more

```

**Comment by keith-turner** [comment]
Looked into this and found what the problem was. When the tablet minor compacts after log recovery its requiring the tablet server to be the current location.  However in the log recovery case, the tablet server is still the future location.  Looking into fixing.
