### ISSUE TITLE
Enable building on jdk17+

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#3967]
Currently cannot fully build Accumulo with jdk17 when error prone is activated.  

```
INFO] --- compiler:3.11.0:compile (default-compile) @ accumulo-start ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 4 source files with javac [debug deprecation release 11] to target/classes
An exception has occurred in the compiler (17.0.8.1). Please file a bug against the Java compiler via the Java bug reporting page (https://bugreport.java.com) after checking the Bug Database (https://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
java.lang.IllegalAccessError: class com.google.errorprone.BaseErrorProneJavaCompiler (in unnamed module @0x7a54fc29) cannot access class com.sun.tools.javac.api.BasicJavacTask (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x7a54fc29
	at com.google.errorprone.BaseErrorProneJavaCompiler.addTaskListener(BaseErrorProneJavaCompiler.java:95)
	at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:34)

```

I was able to build, test and run in uno.  I did try a newer version of error prone (2.23.0, currently we have 2.20.0) but that did not fix anything.

Looking into the issue, error prone points to a built environment error (or change required) but I did not see an obvious change that would allow error prone to run.

**Comment by EdColeman** [comment]
Will be fixed with #3970
