### ISSUE TITLE
Hadoop2 Metrics does not retry sending if metrics server is down

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#407]
Original issue: https://issues.apache.org/jira/browse/ACCUMULO-4849

```
2018-03-16 11:01:14,726 [impl.MetricsSystemImpl] WARN : Error creating sink 'graphite'
org.apache.hadoop.metrics2.impl.MetricsConfigException: Error creating plugin: org.apache.hadoop.metrics2.sink.GraphiteSink
at org.apache.hadoop.metrics2.impl.MetricsConfig.getPlugin(MetricsConfig.java:203)
at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.newSink(MetricsSystemImpl.java:529)
at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.configureSinks(MetricsSystemImpl.java:501)
at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.configure(MetricsSystemImpl.java:480)
at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.start(MetricsSystemImpl.java:189)
at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.init(MetricsSystemImpl.java:164)
at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.init(DefaultMetricsSystem.java:54)
at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.initialize(DefaultMetricsSystem.java:50)
at org.apache.accumulo.server.metrics.MetricsSystemHelper$MetricsSystemHolder.<clinit>(MetricsSystemHelper.java:46)
at org.apache.accumulo.server.metrics.MetricsSystemHelper.getInstance(MetricsSystemHelper.java:50)
at org.apache.accumulo.tserver.metrics.TabletServerMetricsFactory.<init>(TabletServerMetricsFactory.java:45)
at org.apache.accumulo.tserver.TabletServer.<init>(TabletServer.java:401)
at org.apache.accumulo.tserver.TabletServer.main(TabletServer.java:3086)
at org.apache.accumulo.tserver.TServerExecutable.execute(TServerExecutable.java:43)
at org.apache.accumulo.start.Main.lambda$execKeyword$0(Main.java:122)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.metrics2.MetricsException: Error creating connection, localhost:2004
at org.apache.hadoop.metrics2.sink.GraphiteSink$Graphite.connect(GraphiteSink.java:160)
at org.apache.hadoop.metrics2.sink.GraphiteSink.init(GraphiteSink.java:64)
at org.apache.hadoop.metrics2.impl.MetricsConfig.getPlugin(MetricsConfig.java:199)
... 15 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at java.net.Socket.connect(Socket.java:538)
at java.net.Socket.<init>(Socket.java:434)
at java.net.Socket.<init>(Socket.java:211)
at org.apache.hadoop.metrics2.sink.GraphiteSink$Graphite.connect(GraphiteSink.java:152)
... 17 more
```

**Comment by ctubbsii** [comment]
It seems like this issue is specific to the GraphiteSink, which can fail to initialize if it can't connect. I don't think this would be an issue with a different sink, perhaps one that receives metrics and asynchronously passes them along.

We could perhaps retry initializing the whole metrics system again if it fails the first time, but initializing in a loop seems wrong to me... especially since the connection could still be lost later, and at any time. If anything is to be done about this, I think it'd be best to contribute improvements to the GraphiteSink, or encourage people to use a different (better) sink.

**Comment by ctubbsii** [comment]
Closing this based on last comments and age of ticket.
