### ISSUE TITLE
Elasticity Broken or Flaky test: WALSunnyDayIT.test()

### ISSUE THREAD

**Issue by kevinrr888** [apache/accumulo#4251]
**Test name(s)**
 - WALSunnyDayIT.test()

**Describe the failure observed**
WALSunnyDayIT.test() is no longer working in the elasticity branch. Times out/fails

**Comment by cshannon** [comment]
I thought this might be the same issue as #4209 that was fixed in #4248 because the test is starting/stopping servers, but I tested locally with the latest after the fix was merged and it's still timing out for me so this needs to be looked at more to see if it's something related or different.

**Comment by cshannon** [comment]
I'm seeing similar threads hung in the Manager to #4209 that look to be related to the test stopping the tablet server so the Manager can't scan and seems to be stuck waiting on the `ClientTabletCache`. Both TabletGroupWatcher and Fate threads are waiting. The test is waiting for metadata table to come back (stuck trying to scan the table) after starting the server again but it seems like it's stuck forever which may be because the Manager is stuck so the Tserver can't come back. 

```
"Fate work finder" #67 daemon prio=5 os_prio=0 cpu=120.97ms elapsed=68.39s tid=0x00007f66a4106b30 nid=0x2e7eb waiting on condition  [0x00007f6720246000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(java.base@17.0.10/Native Method)
        at java.lang.Thread.sleep(java.base@17.0.10/Thread.java:344)
        at java.util.concurrent.TimeUnit.sleep(java.base@17.0.10/TimeUnit.java:446)
        at com.google.common.util.concurrent.Uninterruptibles.sleepUninterruptibly(Uninterruptibles.java:406)
        at org.apache.accumulo.core.clientImpl.RootClientTabletCache.findTablet(RootClientTabletCache.java:149)
        at org.apache.accumulo.core.clientImpl.ClientTabletCache.findTablet(ClientTabletCache.java:120)
        at org.apache.accumulo.core.clientImpl.ClientTabletCacheImpl.lookupTablet(ClientTabletCacheImpl.java:712)
        at org.apache.accumulo.core.clientImpl.ClientTabletCacheImpl.lookupTabletLocationAndCheckLock(ClientTabletCacheImpl.java:891)
        at org.apache.accumulo.core.clientImpl.ClientTabletCacheImpl._findTablet(ClientTabletCacheImpl.java:881)
        at org.apache.accumulo.core.clientImpl.ClientTabletCacheImpl.findTablets(ClientTabletCacheImpl.java:340)
        at org.apache.accumulo.core.clientImpl.ClientTabletCacheImpl.findTablets(ClientTabletCacheImpl.java:450)
        at org.apache.accumulo.core.clientImpl.ClientTabletCacheImpl.processInvalidated(ClientTabletCacheImpl.java:933)
        at org.apache.accumulo.core.clientImpl.ClientTabletCacheImpl.processInvalidatedAndCheckLock(ClientTabletCacheImpl.java:898)
        at org.apache.accumulo.core.clientImpl.ClientTabletCacheImpl._findTablet(ClientTabletCacheImpl.java:862)
        at org.apache.accumulo.core.clientImpl.ClientTabletCacheImpl.findTablet(ClientTabletCacheImpl.java:552)
        at org.apache.accumulo.core.clientImpl.ThriftScanner.getNextScanAddress(ThriftScanner.java:559)
        at org.apache.accumulo.core.clientImpl.ThriftScanner.scan(ThriftScanner.java:662)
        at org.apache.accumulo.core.clientImpl.ScannerIterator.readBatch(ScannerIterator.java:159)
        - locked <0x00000000f4761588> (a org.apache.accumulo.core.clientImpl.ThriftScanner$ScanState)
        at org.apache.accumulo.core.clientImpl.ScannerIterator.getNextBatch(ScannerIterator.java:177)
        at org.apache.accumulo.core.clientImpl.ScannerIterator.hasNext(ScannerIterator.java:111)
        at java.util.Iterator.forEachRemaining(java.base@17.0.10/Iterator.java:132)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(java.base@17.0.10/Spliterators.java:1845)
        at java.util.stream.AbstractPipeline.copyInto(java.base@17.0.10/AbstractPipeline.java:509)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@17.0.10/AbstractPipeline.java:499)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(java.base@17.0.10/ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(java.base@17.0.10/ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(java.base@17.0.10/AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(java.base@17.0.10/ReferencePipeline.java:596)
        at org.apache.accumulo.core.fate.AbstractFateStore.runnable(AbstractFateStore.java:175)
        at org.apache.accumulo.core.logging.FateLogger$1.runnable(FateLogger.java:125)
        at org.apache.accumulo.core.fate.Fate$WorkFinder.run(Fate.java:93)
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52)
        at java.lang.Thread.run(java.base@17.0.10/Thread.java:840)

   Locked ownable synchronizers:
        - <0x00000000f1231a48> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00000000f124a2a8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
```        

```
"Watching Normal Tablets" #53 daemon prio=5 os_prio=0 cpu=120.39ms elapsed=68.40s tid=0x00007f66a40e6a30 nid=0x2e7df waiting on condition  [0x00007f6720d51000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.10/Native Method)
        - parking to wait for  <0x00000000f124a2a8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(java.base@17.0.10/LockSupport.java:211)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.10/AbstractQueuedSynchronizer.java:715)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(java.base@17.0.10/AbstractQueuedSynchronizer.java:1027)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(java.base@17.0.10/ReentrantReadWriteLock.java:738)
        at org.apache.accumulo.core.clientImpl.ClientTabletCacheImpl.findTablets(ClientTabletCacheImpl.java:417)
        at org.apache.accumulo.core.clientImpl.ClientTabletCache.binRanges(ClientTabletCache.java:174)
        at org.apache.accumulo.core.clientImpl.SyncingClientTabletCache.binRanges(SyncingClientTabletCache.java:97)
        at org.apache.accumulo.core.clientImpl.TimeoutClientTabletCache.binRanges(TimeoutClientTabletCache.java:110)
        at org.apache.accumulo.core.clientImpl.TabletServerBatchReaderIterator.binRanges(TabletServerBatchReaderIterator.java:275)
        at org.apache.accumulo.core.clientImpl.TabletServerBatchReaderIterator.lookup(TabletServerBatchReaderIterator.java:249)
        - locked <0x00000000f44f2c40> (a org.apache.accumulo.core.clientImpl.TabletServerBatchReaderIterator)
        at org.apache.accumulo.core.clientImpl.TabletServerBatchReaderIterator.<init>(TabletServerBatchReaderIterator.java:172)
        at org.apache.accumulo.core.clientImpl.TabletServerBatchReader.iterator(TabletServerBatchReader.java:118)
        at org.apache.accumulo.server.manager.state.TabletManagementScanner.<init>(TabletManagementScanner.java:95)
        at org.apache.accumulo.server.manager.state.MetaDataStateStore.iterator(MetaDataStateStore.java:63)
        at org.apache.accumulo.server.manager.state.LoggingTabletStateStore.iterator(LoggingTabletStateStore.java:60)
        at org.apache.accumulo.server.manager.state.TabletStateStore.iterator(TabletStateStore.java:62)
        at org.apache.accumulo.manager.TabletGroupWatcher.run(TabletGroupWatcher.java:681)

   Locked ownable synchronizers:
        - None
```

**Comment by keith-turner** [comment]
Created #4255 as a fix for this.  Below are some notes from debugging this.  After the test got stuck, noticed the tserver could not recover its write ahead logs.  The following warn was from the tserver logs

```
2024-02-12T10:09:39,395 53 [tserver.AssignmentHandler] WARN : exception trying to assign tablet +r<< null
java.lang.RuntimeException: Error recovering tablet +r<< from log files
        at org.apache.accumulo.tserver.tablet.Tablet.<init>(Tablet.java:292) ~[classes/:?]
        at org.apache.accumulo.tserver.AssignmentHandler.run(AssignmentHandler.java:140) ~[classes/:?]
        at org.apache.accumulo.tserver.TabletClientHandler.lambda$loadTablet$8(TabletClientHandler.java:948) ~[classes/:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) [classes/:?]
        at java.base/java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.IOException: Unable to find recovery files for extent +r<< logEntry: file:/home/accumulo/git/accumulo/test/target/mini-tests/org.apache.accumulo.test.functional.WALSunnyDayIT_test/accumulo/wal/host1+46715/a04ee587-bf44-4667-b0e1-68b4460e369f
        at org.apache.accumulo.tserver.TabletServer.recover(TabletServer.java:903) ~[classes/:?]
        at org.apache.accumulo.tserver.tablet.Tablet.<init>(Tablet.java:258) ~[classes/:?]
        ... 4 more
```

Was wondering if the GC had deleted the walog, took a look in the GC logs and did not see evidence of that.

```
accumulo@host1:~/git/accumulo/test/target/mini-tests/org.apache.accumulo.test.functional.WALSunnyDayIT_test/logs$ grep GarbageCollectWriteAheadLogs *
SimpleGarbageCollector_426288884.out:2024-02-12T10:09:21,906 31 [gc.GarbageCollectWriteAheadLogs] INFO : Fetched 3 files for 1 servers in 0.01 seconds
SimpleGarbageCollector_426288884.out:2024-02-12T10:09:21,948 31 [gc.GarbageCollectWriteAheadLogs] INFO : 1 log entries scanned in 0.04 seconds
SimpleGarbageCollector_426288884.out:2024-02-12T10:09:21,949 31 [gc.GarbageCollectWriteAheadLogs] DEBUG: Removing UNREFERENCED WAL file:/home/accumulo/git/accumulo/test/target/mini-tests/org.apache.accumulo.test.functional.WALSunnyDayIT_test/accumulo/wal/host1+46715/f9934e85-cb37-4f91-8a97-30fd194b4e81
SimpleGarbageCollector_426288884.out:2024-02-12T10:09:21,952 31 [gc.GarbageCollectWriteAheadLogs] INFO : 1 total logs removed from 1 servers in 0.00 seconds
SimpleGarbageCollector_426288884.out:2024-02-12T10:09:21,952 31 [gc.GarbageCollectWriteAheadLogs] INFO : 0 recovery logs removed
SimpleGarbageCollector_426288884.out:2024-02-12T10:09:21,970 31 [gc.GarbageCollectWriteAheadLogs] INFO : 0 markers removed in 0.02 seconds
```

Also looked and found the wals existed in the file system.

```
accumulo@host1:~/git/accumulo/test/target/mini-tests/org.apache.accumulo.test.functional.WALSunnyDayIT_test/accumulo/wal/host1+46715$ ls -al
total 164
drwxr-xr-x 2 accumulo accumulo      4 Feb 12 10:09 .
drwxr-xr-x 3 accumulo accumulo      3 Feb 12 10:09 ..
-rwxr-xr-x 1 accumulo accumulo 136688 Feb 12 10:09 a04ee587-bf44-4667-b0e1-68b4460e369f
-rwxr-xr-x 1 accumulo accumulo     86 Feb 12 10:09 bc70a463-1bb4-4659-b38f-25cf11b5bbf0
```

So what was missing was the sorted version of the files, those had never been created.  For the manager to initiate log sort, the TabletGroupWatcher should see the TabletManagementIterator return `ManagementAction.NEEDS_VOLUME_REPLACEMENT` for the root tablet.  Looking in the manager logs, never saw this.  It was only returning `NEEDS_LOCATION_UPDATE`.

```
2024-02-12T10:09:37,272 49 [manager.Manager] TRACE: [Root Table] Shutting down all Tservers: false, dependentCount: 0 Extent: +r<<, state: HOSTED, goal: HOSTED actions:[NEEDS_LOCATION_UPDATE]
2024-02-12T10:09:38,260 102 [bulkVer2.TabletRefresher] DEBUG: Sleeping for 1000ms before retrying operation : compaction:+r<< waiting for 1 tservers to refresh their tablets metadata 
2024-02-12T10:09:39,178 49 [manager.Manager] TRACE: [Root Table] Shutting down all Tservers: false, dependentCount: 0 Extent: +r<<, state: ASSIGNED_TO_DEAD_SERVER, goal: HOSTED actions:[NEEDS_LOCATION_UPDATE]
2024-02-12T10:09:39,195 49 [tablet.location] DEBUG: Unassigned +r<< with 1 walogs
2024-02-12T10:09:39,306 49 [manager.Manager] TRACE: [Root Table] Shutting down all Tservers: false, dependentCount: 0 Extent: +r<<, state: UNASSIGNED, goal: HOSTED actions:[NEEDS_LOCATION_UPDATE]
2024-02-12T10:09:39,310 49 [tablet.location] DEBUG: Assigned +r<< to host1:41953[1000019a115001c]
2024-02-12T10:09:39,414 49 [manager.Manager] TRACE: [Root Table] Shutting down all Tservers: false, dependentCount: 0 Extent: +r<<, state: ASSIGNED, goal: HOSTED actions:[NEEDS_LOCATION_UPDATE]
```

Looked at the TabletManagementIterator source and noticed special code block for when manager state is not normal.  The test sets the manager state to SAFE_MODE, so this was uncovering the bug.
