### ISSUE TITLE
ComprehensiveIT sometimes hangs

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#4375]
The ComprehensiveIT seems to hang sometimes - this was seen while looking at other issues and not at current head, so may not be reproducible.  It did hang in successive runs of 162b8effb1  and 171a1e144c.

The following is from 162b8effb1

In the manager log.  
<details open>
  <summary>Failed to find namespace ID from name: compns</summary>

```
2024-03-14T20:55:07,974 [clientImpl.Namespaces] DEBUG: Failed to find namespace ID from name: compns
org.apache.accumulo.core.client.NamespaceNotFoundException: Namespace compns does not exist (getNamespaceId() failed to find namespace)
        at org.apache.accumulo.core.clientImpl.Namespaces.getNamespaceId(Namespaces.java:120) ~[accumulo-core-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at org.apache.accumulo.core.clientImpl.Namespaces.lookupNamespaceId(Namespaces.java:132) [accumulo-core-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.tableOps.Utils.checkNamespaceDoesNotExist(Utils.java:209) [accumulo-manager-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.tableOps.namespace.create.PopulateZookeeperWithNamespace.call(PopulateZookeeperWithNamespace.java:53) [accumulo-manager-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.tableOps.namespace.create.PopulateZookeeperWithNamespace.call(PopulateZookeeperWithNamespace.java:32) [accumulo-manager-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.tableOps.TraceRepo.call(TraceRepo.java:60) [accumulo-manager-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at org.apache.accumulo.core.fate.Fate$TransactionRunner.run(Fate.java:101) [accumulo-core-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) [accumulo-core-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) [accumulo-core-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
```
</details>

And again with 

<details open>
  <summary>Namespace compns2 does not exist</summary>

```
2024-03-14T20:55:08,351 [clientImpl.Namespaces] DEBUG: Failed to find namespace ID from name: compns2
org.apache.accumulo.core.client.NamespaceNotFoundException: Namespace compns2 does not exist (getNamespaceId() failed to find namespace)
        at org.apache.accumulo.core.clientImpl.Namespaces.getNamespaceId(Namespaces.java:120) ~[accumulo-core-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at org.apache.accumulo.core.clientImpl.Namespaces.lookupNamespaceId(Namespaces.java:132) [accumulo-core-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.tableOps.Utils.checkNamespaceDoesNotExist(Utils.java:209) [accumulo-manager-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.tableOps.namespace.rename.RenameNamespace.call(RenameNamespace.java:62) [accumulo-manager-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.tableOps.namespace.rename.RenameNamespace.call(RenameNamespace.java:36) [accumulo-manager-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.tableOps.TraceRepo.call(TraceRepo.java:60) [accumulo-manager-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at org.apache.accumulo.core.fate.Fate$TransactionRunner.run(Fate.java:101) [accumulo-core-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) [accumulo-core-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) [accumulo-core-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
```
</details>

**Comment by ctubbsii** [comment]
Might be OBE. I haven't seen this in awhile.
