### ISSUE TITLE
Possible tablet refresh causes scan on metadata table to fail

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#4441]
Stack trace below found in log during SplitMillion IT. The client in this case was scanning the metadata table and the tablet server hosting the metadata table logged this error. Around the same time the metadata table had compacted and a tablet metadata refresh operation occurred, which could be the cause of this.

```
java.lang.IllegalStateException: Called next() when there is no top
        at org.apache.accumulo.core.iteratorsImpl.system.HeapIterator.next(HeapIterator.java:72) ~[classes/:?]
        at org.apache.accumulo.core.iterators.WrappingIterator.next(WrappingIterator.java:101) ~[classes/:?]
        at org.apache.accumulo.tserver.MemKeyConversionIterator.next(MemKeyConversionIterator.java:73) ~[classes/:?]
        at org.apache.accumulo.core.iteratorsImpl.system.SourceSwitchingIterator.readNext(SourceSwitchingIterator.java:179) ~[classes/:?]
        at org.apache.accumulo.core.iteratorsImpl.system.SourceSwitchingIterator.next(SourceSwitchingIterator.java:149) ~[classes/:?]
        at org.apache.accumulo.core.iterators.WrappingIterator.next(WrappingIterator.java:101) ~[classes/:?]
        at org.apache.accumulo.core.iterators.SkippingIterator.next(SkippingIterator.java:37) ~[classes/:?]
        at org.apache.accumulo.core.iterators.WrappingIterator.next(WrappingIterator.java:101) ~[classes/:?]
        at org.apache.accumulo.core.iteratorsImpl.system.HeapIterator.next(HeapIterator.java:75) ~[classes/:?]
        at org.apache.accumulo.core.iteratorsImpl.system.StatsIterator.next(StatsIterator.java:51) ~[classes/:?]
        at org.apache.accumulo.core.iteratorsImpl.system.DeletingIterator.next(DeletingIterator.java:65) ~[classes/:?]
        at org.apache.accumulo.core.iteratorsImpl.system.ColumnFamilySkippingIterator.consume(ColumnFamilySkippingIterator.java:66) ~[classes/:?]
        at org.apache.accumulo.core.iterators.ServerSkippingIterator.next(ServerSkippingIterator.java:46) ~[classes/:?]
        at org.apache.accumulo.core.iterators.ServerFilter.next(ServerFilter.java:51) ~[classes/:?]
        at org.apache.accumulo.core.iterators.SynchronizedServerFilter.next(SynchronizedServerFilter.java:51) ~[classes/:?]
        at org.apache.accumulo.core.iterators.WrappingIterator.next(WrappingIterator.java:101) ~[classes/:?]
        at org.apache.accumulo.core.iterators.user.VersioningIterator.skipRowColumn(VersioningIterator.java:103) ~[classes/:?]
        at org.apache.accumulo.core.iterators.user.VersioningIterator.next(VersioningIterator.java:60) ~[classes/:?]
        at org.apache.accumulo.core.iterators.user.RowFilter.skipRows(RowFilter.java:118) ~[classes/:?]
        at org.apache.accumulo.core.iterators.user.RowFilter.seek(RowFilter.java:191) ~[classes/:?]
        at org.apache.accumulo.core.iteratorsImpl.system.SourceSwitchingIterator.readNext(SourceSwitchingIterator.java:165) ~[classes/:?]
        at org.apache.accumulo.core.iteratorsImpl.system.SourceSwitchingIterator.seek(SourceSwitchingIterator.java:237) ~[classes/:?]
        at org.apache.accumulo.tserver.tablet.TabletBase.nextBatch(TabletBase.java:280) ~[classes/:?]
```

**Comment by dlmarion** [comment]
I'm going to close this as it could be OBE. We can re-open or open a new issue if we see new errors in testing.
