### ISSUE TITLE
LogSorter InputStream closes prematurely

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#497]
Some time ago, LogSorter was modified to handle partial headers and the FSDataInputStream in sort() was moved to a try-with-resources.  It appears this change caused the FSDataInputStream to close prematurely, before the finally can call the close() method.  The close method gets the bytesCopied before closing the input so this probably results in bytesCopied in the Monitor to always be -1.  I think this happens every time a WAL is sorted on recovery, showing this error:
<pre>
2018-05-23 14:19:55,298 [log.LogSorter] ERROR: Error during cleanup sort/copy 2841a75d-8086-4fdb-a736-5f0bf60ff42e
java.io.IOException: Stream is closed!
        at org.apache.hadoop.fs.BufferedFSInputStream.getPos(BufferedFSInputStream.java:56)
        at org.apache.hadoop.fs.FSDataInputStream.getPos(FSDataInputStream.java:72)
        at org.apache.accumulo.tserver.log.LogSorter$LogProcessor.close(LogSorter.java:198)
        at org.apache.accumulo.tserver.log.LogSorter$LogProcessor.sort(LogSorter.java:169)
        at org.apache.accumulo.tserver.log.LogSorter$LogProcessor.process(LogSorter.java:96)
        at org.apache.accumulo.server.zookeeper.DistributedWorkQueue$1.run(DistributedWorkQueue.java:109)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at java.lang.Thread.run(Thread.java:748)
</pre>

We could move the FSDataInputStream back to a regular try/catch or refactor the sort method to close things properly.

**Comment by ctubbsii** [comment]
@milleruntime @keith-turner  Is this another WAL bug which needs to be fixed for 1.9.2? It wasn't marked as a blocker, so I removed the 1.9.2 label, in prep for an RC1, but on second thought I want to make sure it really isn't something we want to make sure is fixed for 1.9.2.

**Comment by milleruntime** [comment]
At the time I opened it, it seemed like a non-consequential, minor bug that probably has been around for a while.  I am not sure if @keith-turner has seen it or if it still exists after the latest WAL changes.

**Comment by milleruntime** [comment]
I ran 1.9.2-rc2 locally in uno, forcing recovery and did not see this error.  It is possible @keith-turner 's fixes to the WAL also fixed this error.

**Comment by milleruntime** [comment]
I haven't seen this error in a while so I belive it was squashed.
