### ISSUE TITLE
Broken  test: ExternalCompaction_1_IT.testPartialCompaction timing out

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#5052]
Test is succeeding on it's own, but when you run all the tests in the class it times out. In my runs `testGetActiveCompactions` runs before `testPartialCompactions` and both tests use the same group, `QUEUE8` to execute compactions. Jstacking the Compactor process for that group, the Compactor is doing the following:

```
	at java.lang.Thread.sleep(java.base@11.0.23/Native Method)
	at org.apache.accumulo.test.functional.SlowIterator.next(SlowIterator.java:58)
	at org.apache.accumulo.server.compaction.FileCompactor.compactLocalityGroup(FileCompactor.java:535)
	at org.apache.accumulo.server.compaction.FileCompactor.call(FileCompactor.java:337)
	at org.apache.accumulo.compactor.Compactor$2.run(Compactor.java:573)
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52)
	at java.lang.Thread.run(java.base@11.0.23/Thread.java:829)
```

`testGetActiveCompactions` is the only test in the IT class that uses ` SlowIterator`, and at the very end of the `testGetActiveCompactions` it cancels the compaction. The compaction cancellation must not be working.

**Comment by dlmarion** [comment]
I think #5026 caused this, but this test is not failing in 2.1 or main branches for some reason. The `testGetActiveCompactions` method creates a table with a lot of files (it's calling BatchWriter.flush in a loop). When the test cancels the user compaction, a bunch of system compactions are generated to get the number of files for the tablets below the threshold. Since the following test method is using the same compactor queue, the compactor process is busy compacting the tablets from the previous test and never gets around to compacting the tablets for the current test method, and it times out.
