### ISSUE TITLE
New bulk importer fails if directory contains files other than RFiles

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#518]
This may be intended behavior... I'm not sure.
I tried to convert some bulk import code from AuditMessageIT:

```java
auditConnector.tableOperations().importDirectory(THIRD_TEST_TABLE_NAME, exportDir.toString(), failDir.toString(), false);
```
to:
```java
auditConnector.tableOperations().addFilesTo(THIRD_TEST_TABLE_NAME).from(exportDir.toString()).load();
```

The former works fine with the `export` directory containing:
```
distcp.txt
exportMetadata.zip
tmp/
```
However, the latter failed because it did not recognize the `zip` file format. I'm not sure why this test is trying to bulk import from an `exportTable` directory, but it works fine using the old method (which seems to silently ignore unrecognized files... although I can't find the relevant filtering code).

Do we want the new bulk importer to ignore unrecognized files like the old method did, or not?

**Comment by ctubbsii** [comment]
Using an empty directory for this test gets a little further along... it creates the `loadmap.json` file, but then fails because the file list is empty:

```java
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was END_ARRAY at line 1 column 3 path $[0]
  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
  at com.google.gson.Gson.fromJson(Gson.java:887)                                                   
  at org.apache.accumulo.core.client.impl.BulkSerialize$LoadMappingIterator.next(BulkSerialize.java:150)
  at org.apache.accumulo.core.client.impl.BulkSerialize$LoadMappingIterator.next(BulkSerialize.java:118)
  at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)                
  at org.apache.accumulo.master.tableOps.bulkVer2.PrepBulkImport.checkForMerge(PrepBulkImport.java:110)
  at org.apache.accumulo.master.tableOps.bulkVer2.PrepBulkImport.checkForMerge(PrepBulkImport.java:174)
  at org.apache.accumulo.master.tableOps.bulkVer2.PrepBulkImport.call(PrepBulkImport.java:182)         
  at org.apache.accumulo.master.tableOps.bulkVer2.PrepBulkImport.call(PrepBulkImport.java:66)          
  at org.apache.accumulo.master.tableOps.TraceRepo.call(TraceRepo.java:54)                          
  at org.apache.accumulo.fate.Fate$TransactionRunner.run(Fate.java:73)                              
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                
  at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)                     
  at java.lang.Thread.run(Thread.java:748)                                                          
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was END_ARRAY at line 1 column 3 path $[0]
  at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)                             
  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
  ... 14 more
```

**Comment by ctubbsii** [comment]
@milleruntime I don't think there's a test for this issue, so I'm not sure what test your talking about.

**Comment by milleruntime** [comment]
You mention AuditMessageIT failing when you changed it to use the new API.

**Comment by ctubbsii** [comment]
Oh. Sorry for the confusion. That's where I first noticed this issue, but I fixed that to avoid reusing the same directory. The reported behavior still exists, and could affect users of the new API. We don't have a test case for this and I'm not sure what the expected behavior should be. I don't know if it is common to import rfiles from a directory with other stuff in it or whether it should recurse to find more rfiles, or have some other behavior.

**Comment by milleruntime** [comment]
No problem.  I actually just saw this error when testing the new bulk import shell command.  I saw the error happen when you pass an empty directory.  

I think we should just print a debug if the directory is empty or if there other files present.  It seems like an empty directory or having other files present (because of Map Reduce) is not abnormal behavior.
