### ISSUE TITLE
Tablet assignment thread gets stuck

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#543]
Received this exception while running continuous ingest on Accumulo 1.9 with heavy tserver agitation.

```
Assignment for !0;~< has been running for at least 1031221ms
	java.lang.Exception: Assignment of !0;~<
		at sun.misc.Unsafe.park(Native Method)
		at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
		at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
		at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
		at org.apache.accumulo.tserver.tablet.Tablet.removeInUseLogs(Tablet.java:2465)
		at org.apache.accumulo.tserver.TabletServer$12.removeInUse(TabletServer.java:3413)
		at org.apache.accumulo.tserver.TabletServer.findOldestUnreferencedWals(TabletServer.java:3370)
		at org.apache.accumulo.tserver.TabletServer.markUnusedWALs(TabletServer.java:3421)
		at org.apache.accumulo.tserver.TabletServer.minorCompactionFinished(TabletServer.java:3245)
		at org.apache.accumulo.tserver.tablet.DatafileManager.bringMinorCompactionOnline(DatafileManager.java:459)
		at org.apache.accumulo.tserver.tablet.Tablet.minorCompact(Tablet.java:914)
		at org.apache.accumulo.tserver.tablet.MinorCompactionTask.run(MinorCompactionTask.java:90)
		at org.apache.accumulo.tserver.tablet.Tablet.minorCompactNow(Tablet.java:1047)
		at org.apache.accumulo.tserver.TabletServer$AssignmentHandler.run(TabletServer.java:2388)
		at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
		at org.apache.accumulo.tserver.ActiveAssignmentRunnable.run(ActiveAssignmentRunnable.java:64)
		at org.apache.htrace.wrappers.TraceRunnable.run(TraceRunnable.java:57)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
		at java.lang.Thread.run(Thread.java:748)
```

**Comment by keith-turner** [comment]
This is stuck in the code added in #539

**Comment by keith-turner** [comment]
I think I know what is happening, a non-metadata tablet is holding its logLock while trying to write to a metadata tablet that is not online.  The metadata tablet loads, recovers, and then minor compacts.  After the metadata tablet minor compacts it attempts to do book keeping for WALs and this process tries to lock all other tablets logLocks.  This results in deadlock.
