### ISSUE TITLE
Seeing NPE in rfile-info in 2.0.0-SNAP

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#676]
Seeing the following NPE in master when running rfile-info. Running accumulo built from 
caf75c15deffe1e0041d2242a350988a17641e58 with local changes from #675

```
$ accumulo rfile-info /accumulo/tables/3/t-000005l/A00000am.rf
Reading file: hdfs://localhost:8020/accumulo/tables/3/t-000005l/A00000am.rf
No on disk encryption detected.
RFile Version            : 8

Locality group           : <DEFAULT>
	Num   blocks           : 2,172
	Index level 0          : 68,056 bytes  1 blocks
	First key              : 73333378a7c00468 0921:707c [] 1538599801516 false
	Last key               : 79999982c534792e 78c2:67e0 [] 1538599767359 false
	Num entries            : 2,018,247
	Column families        : <UNKNOWN>

2018-10-03 17:06:31,101 [start.Main] ERROR: Thread 'rfile-info' died.
java.lang.NullPointerException
	at com.beust.jcommander.JCommander.expandArgs(JCommander.java:430)
	at com.beust.jcommander.JCommander.parse(JCommander.java:340)
	at com.beust.jcommander.JCommander.parse(JCommander.java:319)
	at org.apache.accumulo.core.cli.Help.parseArgs(Help.java:34)
	at org.apache.accumulo.core.cli.ConfigOpts.parseArgs(ConfigOpts.java:93)
	at org.apache.accumulo.core.file.rfile.bcfile.PrintInfo.main(PrintInfo.java:73)
	at org.apache.accumulo.core.file.rfile.PrintInfo.execute(PrintInfo.java:187)
	at org.apache.accumulo.start.Main.lambda$execKeyword$0(Main.java:129)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by milleruntime** [comment]
I can take a look at this.

**Comment by ctubbsii** [comment]
I saw a bug in your PR. Try again with the updates I pushed to your PR in #675

**Comment by keith-turner** [comment]
> I saw a bug in your PR. Try again with the updates I pushed to your PR in #675

This bug was not caused by #675, I was just documenting what version of Accumulo I was running when I saw the bug.
