### ISSUE TITLE
accumulo 1.9.2  TabletClientService:sendBaseOneway method not found

### ISSUE THREAD

**Issue by MrDLontheway** [apache/accumulo#739]
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Client.sendBaseOneway(Ljava/lang/String;Lorg/apache/thrift/TBase;)V
	at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Client.send_closeScan(TabletClientService.java:303)
	at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Client.closeScan(TabletClientService.java:295)
	at org.apache.accumulo.core.client.impl.ThriftScanner.getBatchFromServer(ThriftScanner.java:122)
	at org.apache.accumulo.core.metadata.MetadataLocationObtainer.lookupTablet(MetadataLocationObtainer.java:105)
	at org.apache.accumulo.core.client.impl.TabletLocatorImpl.lookupTabletLocation(TabletLocatorImpl.java:506)
	at org.apache.accumulo.core.client.impl.TabletLocatorImpl.lookupTabletLocationAndCheckLock(TabletLocatorImpl.java:688)
	at org.apache.accumulo.core.client.impl.TabletLocatorImpl._locateTablet(TabletLocatorImpl.java:673)
	at org.apache.accumulo.core.client.impl.TabletLocatorImpl.locateTablet(TabletLocatorImpl.java:476)
	at org.apache.accumulo.core.client.impl.TabletLocatorImpl.lookupTabletLocation(TabletLocatorImpl.java:503)
	at org.apache.accumulo.core.client.impl.TabletLocatorImpl.lookupTabletLocationAndCheckLock(TabletLocatorImpl.java:688)
	at org.apache.accumulo.core.client.impl.TabletLocatorImpl._locateTablet(TabletLocatorImpl.java:678)
	at org.apache.accumulo.core.client.impl.TabletLocatorImpl.binRanges(TabletLocatorImpl.java:303)
	at org.apache.accumulo.core.client.impl.TabletLocatorImpl.binRanges(TabletLocatorImpl.java:384)
	at org.apache.accumulo.core.client.mapreduce.AbstractInputFormat.getSplits(AbstractInputFormat.java:810)
	at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:113)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1929)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:927)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:926)
	at org.apache.spark.api.java.JavaRDDLike$class.collect(JavaRDDLike.scala:339)
	at org.apache.spark.api.java.AbstractJavaRDDLike.collect(JavaRDDLike.scala:46)
	at com.wxstc.dl.MyAccumuloSpark.main(MyAccumuloSpark.java:54)

TabletClientService.java:303

when Associated with the source code then I didn't find it

**Comment by milleruntime** [comment]
Thanks for the stacktrace @MrDLontheway .  I see you are running a Map Reduce job using Spark.  Any more information you can provide?

**Comment by ctubbsii** [comment]
This could be a thrift version mismatch. Perhaps multiple versions of
thrift are on the class path?

**Comment by MrDLontheway** [comment]
i use spark 1.6 and hadoop 2.6 accumulo 1.9.2

@milleruntime 
`package com.wxstc.dl;

import com.boozallen.cognition.spark.accumulo.AccumuloSpark;
import com.wxstc.dl.accumulo.AccumuloConnector;
import org.apache.accumulo.core.client.ClientConfiguration;
import org.apache.accumulo.core.client.mapreduce.AccumuloInputFormat;
import org.apache.accumulo.core.client.security.tokens.PasswordToken;
import org.apache.accumulo.core.data.Key;
import org.apache.accumulo.core.data.Value;
import org.apache.accumulo.core.security.Authorizations;
import org.apache.accumulo.core.util.PeekingIterator;
import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.mapreduce.Job;
import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaPairRDD;
import org.apache.spark.api.java.JavaSparkContext;
import scala.Tuple2;

import java.io.IOException;
import java.util.List;
import java.util.Map;


public class MyAccumuloSpark {
    public static void main(String[] args) throws Exception {
//        SparkSession spark = SparkSession.builder().master("local[*]").appName("Test").getOrCreate();
//        final JavaSparkContext ctx = JavaSparkContext.fromSparkContext(spark.sparkContext());

        SparkConf conf = new SparkConf().setAppName("Test").setMaster("local[*]");
//		conf.set("spark.driver.extraClassPath", "/data/ojdbc14-10.2.0.3.0.jar");
//        conf.set("spark.executor.extraClassPath", "/data/ojdbc14-10.2.0.3.0.jar");
        JavaSparkContext sparkContext = new JavaSparkContext(conf);

        Job job = new Job(sparkContext.hadoopConfiguration());
        AccumuloInputFormat.setScanAuthorizations(job, new Authorizations("vis22","vis1"));
        AccumuloInputFormat.setConnectorInfo(job, "root", new PasswordToken("123456"));
        AccumuloInputFormat.setZooKeeperInstance(job,
                ClientConfiguration.loadDefault().withInstance(AccumuloConnector.instanceName).withZkHosts(AccumuloConnector.zooServers));
        AccumuloInputFormat.setInputTableName(job,"table1");

//        JavaPairRDD<Text, PeekingIterator<java.util.Map.Entry<Key, Value>>> accrdd = sparkContext.newAPIHadoopRDD(sparkContext.hadoopConfiguration(),
//                AccumuloInputFormat.class, Text.class,PeekingIterator<java.util.Map.Entry<Key, Value>>);

        JavaPairRDD<Key, Value> keyValueJavaPairRDD = sparkContext.newAPIHadoopRDD(job.getConfiguration(),
                AccumuloInputFormat.class, Key.class, Value.class);
        List<Tuple2<Key, Value>> collect = keyValueJavaPairRDD.collect();

        for (Tuple2<Key, Value> t2:
        collect) {
            Key k = t2._1;
            Value b = t2._2;
            System.out.println("key:"+k.toString());
            System.out.println("Value:"+b.toString());
        }
        sparkContext.stop();
    }

}
`

**Comment by ctubbsii** [comment]
@MrDLontheway I think the problem is likely your class path has an incorrect version of Thrift, or multiple versions of Thrift. Check your class path. Accumulo 1.9.2 requires thrift 0.9.3.

**Comment by MrDLontheway** [comment]
@ctubbsii thanks
