### ISSUE TITLE
Commons config update broke Initialize

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#757]
I saw this error trying to initialize current 1.9 branch:
<pre>
java.util.ServiceConfigurationError: org.apache.accumulo.start.spi.KeywordExecutable: Provider org.apache.accumulo.server.init.Initialize could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.apache.accumulo.start.Main.checkDuplicates(Main.java:237)
	at org.apache.accumulo.start.Main.getExecutables(Main.java:228)
	at org.apache.accumulo.start.Main.main(Main.java:84)
Caused by: java.lang.NoSuchMethodError: org.apache.commons.configuration.MapConfiguration.<init>(Ljava/util/Properties;)V
	at org.apache.accumulo.core.conf.Property.precomputeDefaultValue(Property.java:969)
	at org.apache.accumulo.core.conf.Property.<clinit>(Property.java:1345)
	at org.apache.accumulo.server.init.Initialize.<clinit>(Initialize.java:165)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)

</pre>

**Comment by milleruntime** [comment]
@busbey I think your update to commons config here 06d80292d869edc495bf691c0d43be52dc0dcdca may be the cause of this error.

**Comment by milleruntime** [comment]
I tested with Hadoop 2.8.4 and 2.7.6.  It looks like Accumulo is trying to use Hadoop's commons-configuration-1.6.jar

**Comment by busbey** [comment]
thanks for the heads up. reviewing a bit later today. Maybe I don't see it locally because I'm using Hadoop 3?

**Comment by ctubbsii** [comment]
> It looks like Accumulo is trying to use Hadoop's commons-configuration-1.6.jar

If that's all it is, we could probably just add the version we're using to our tarball, and use that in our default class path... unless, of course, some hadoop library code we're using would break by doing so.

**Comment by busbey** [comment]
sorry last week got a bit nuts. on my end. I agree that @ctubbsii 's suggestion is the way to go. Anyone have suggestions on what I use to test this out? Barring suggestions I'll basically spin up a Hadoop 2 and Hadoop 3 based 1.9.2 install using Unos and run CI for a bit.
