### ISSUE TITLE
Exception while creating RFiles for Bulk import

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#784]
I encountered the following exception while running the Bulk import random walk test. The test completed successfully so this exception may have no negative effects.
```
2018-11-28 16:20:42,179 [randomwalk.bulk.BulkPlusOne] DEBUG: Creating hdfs://localhost:8020/tmp/bulk_e1468262-6efd-4a62-94d6-8272cb5b8dc2/part_
4.rf
2018-11-28 16:20:42,251 [hadoop.hdfs.DataStreamer] WARN : Caught exception
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Thread.join(Thread.java:1252)
        at java.lang.Thread.join(Thread.java:1326)
        at org.apache.hadoop.hdfs.DataStreamer.closeResponder(DataStreamer.java:986)
        at org.apache.hadoop.hdfs.DataStreamer.endBlock(DataStreamer.java:640)
        at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:810)
```

**Comment by Manno15** [comment]
@mikewalch Do you know if this exception still occurs? I couldn't reproduce it in my tests.

**Comment by mikewalch** [comment]
> @mikewalch Do you know if this exception still occurs? I couldn't reproduce it in my tests.

Feel free to close it then.

**Comment by Manno15** [comment]
> Feel free to close it then.

I don't actually have the permissions to close issues.
