### ISSUE TITLE
AccumuloInputFormat.fetchColumns should accept empty collection

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#888]
It currently throws exception:
```
java.lang.IllegalArgumentException: Specified collection of fetch columns is empty.
	at org.apache.accumulo.hadoopImpl.mapreduce.InputFormatBuilderImpl.fetchColumns(InputFormatBuilderImpl.java:103)
	at org.apache.accumulo.examples.mapreduce.TableToFile.main(TableToFile.java:88)
```
Accepting an empty collection makes it easier to use builder (you don't need to handle different cases in the builder)

**Comment by jzgithub1** [comment]
I will work on this issue

**Comment by mikewalch** [comment]
See #901
