### ISSUE TITLE
Fix or remove execWithStdout

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#908]
I recently ran [ExamplesIT](https://github.com/apache/accumulo-examples/blob/master/src/test/java/org/apache/accumulo/examples/ExamplesIT.java)  in the accumulo-examples repo. It produced the following error

```
java.io.FileNotFoundException: ./accumulo-examples/target/mini-tests/org.apache.accumulo.examples.ExamplesIT_testWordCount/logs/WordCount_1766172129.out (No such file or directory)
	at org.apache.accumulo.examples.ExamplesIT.goodExec(ExamplesIT.java:432)
	at org.apache.accumulo.examples.ExamplesIT.testWordCount(ExamplesIT.java:385)
```

The problem is occurring in [ClusterControl.execWithStdout](https://github.com/apache/accumulo/blob/2d634f2a330e8f1b7f925b744770f65da0eab037/minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterControl.java#L99) which call [this code](https://github.com/apache/accumulo/blob/2d634f2a330e8f1b7f925b744770f65da0eab037/minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java#L289) in MiniAccumuloClusterImpl.  The `ProcessBuilder.hashCode()` is used rather than the `Process.hashCode()` so the ClusterControl code cannot find the log file using `Process.hashCode()`

**Comment by keith-turner** [comment]
https://github.com/apache/accumulo/pull/897#issuecomment-455696981
